### ISSUE TITLE
walkthrough: Meadow step is not generated properly

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1001]
### One-liner
When I run `walkthrough meadow` it generates the wrong snapshot step in the dag and in the meadow code (the extension is missing).

### Environment

- `python -V`: Python 3.11.1
- Operating system: macOS Ventura 13.3.1
- Working with local, staging or live: None (or local)

### Context & details
Discussed [in Slack](https://owid.slack.com/archives/C46U9LXRR/p1681403070391469). The snapshot step needed in the dag and in the code lacks the extension (in this case, csv). If it is added manually things run back to normal. https://github.com/owid/etl/pull/1000

![image](https://user-images.githubusercontent.com/63430031/231828908-d0bf274e-8583-46b6-bb57-b7d7b7a0dc53.png)
![image](https://user-images.githubusercontent.com/63430031/231828949-7884739d-9274-4357-8056-421674bf639e.png)

**Comment by lucasrodes** [comment]
@paarriagadap 
Any chance you forgot to enter the extension in the extension field? By default, it shows "csv" (greyed out), but you actually need to type it.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/18101289/232081496-58281dcd-64c1-4d58-97e9-0cd5e42e5d2b.png">

**Comment by paarriagadap** [comment]
@lucasrodes No, it was [saved on the snapshot](https://github.com/owid/etl/blob/cc8c3dc02849c879f01c4419644248890a407d01/snapshots/equaldex/2023-04-13/equaldex.csv.dvc)

**Comment by paarriagadap** [comment]
I just ran it again in the `create-equaldex-dataset` branch and I had the same thing:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/63430031/232084863-81245804-1e11-4e00-8b05-e742de5a7a99.png">

**Comment by lucasrodes** [comment]
This has now been resolved after chatting with Pablo.

`walkthrough meadow` needs the user to input the extension of the snapshot file. Even if the Snapshot dvc file has a field specifying the extension, it is not enough.

Note that we may have the case where there are multiple snapshot dvc files, with the same name, but different extensions. Therefore, we need to specify the extension in Meadow.
