### ISSUE TITLE
Archive `data://garden/sdg/latest/sdg`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1009]
We assemble all data from https://sdg-tracker.org/ into `garden/sdg/latest/sdg` dataset. Dependencies are created by a [notebook](https://github.com/owid/etl/blob/master/etl/steps/data/garden/sdg/latest/generate_sdg_mapping.ipynb) and then manually copied into `main.yml`. That's not great because if someone changes SDG tracker, we have to rerun the script. This usually happens only after someone archives dataset and ETL stops working. Then we rerun the notebook and wait for the next failure...

Since this dataset is not used by anyone (as far as I know), how about we just archive it and see if anyone complains? @spoonerf what do you think? (@bnjmacdonald someone mentioned that you've been using it too?)

**Comment by spoonerf** [comment]
Hey @Marigold!

It does seem like this causes some headaches at the moment. 

I think the main argument for keeping it is that it might be useful to provide downloads of data for the SDG Tracker. For example, if a user wanted to download all the data for Goal 7 then this would be useful for enabling that. This was a function that we previously wanted to provide but I'm not sure we still do. 

@mathisonian do you think that providing data downloads is something that could be useful in the new SDG Tracker? If not then I think it is probably best to archive it.

**Comment by Marigold** [comment]
@spoonerf we could unarchive (and improve it) it if we find use for it. That'll at least give us feedback on whether anyone uses it.

**Comment by spoonerf** [comment]
Good point - let's archive it and see what happens!
