### ISSUE TITLE
docs: weird formatting on the Getting Started page

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#1046]
### One-liner
The formatting on the [Getting Started](https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/getting-started/index.md) page seems to be a bit off, for me anyway.  

### Context & details
It loads like this for me - with very large icons

![Screenshot 2023-04-27 at 08 55 25](https://user-images.githubusercontent.com/10774728/234797098-9ec9006d-825e-4b1c-a2cd-647599491a5d.png)

**Comment by Marigold** [comment]
Looks like a bat-signal, but calling for OWID.

**Comment by lucasrodes** [comment]
Seems like the URL that you shared is not the correct one. The tutorial for adding data lives here now: https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/

Is that URL coming from the notion documentation of the crash course?

Ideally the docs should display a "Not found" message, will investigate why is not so

**Comment by lucasrodes** [comment]
Okay, I think you refer to the "Getting started" URLs appearing in

- https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/walkthrough/
- https://docs.owid.io/projects/etl/en/latest/tutorials/adding-data/manual/

If so, I solved this in https://github.com/owid/etl/pull/1048

**Comment by spoonerf** [comment]
Yep that was the issue @lucasrodes #1048 should solve it!
