### ISSUE TITLE
fasttrack: KeyError: 'data_url'

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1057]
I am trying to import a dataset via fast-track. The URL of the dataset is this one: https://docs.google.com/spreadsheets/d/e/2PACX-1vQ0XtprK8CrjzrwpeZSPjPiuGmuCgwkHtwXs8jXKkHOuCN8UTmWQDgu11wkj9o5xtO5T5_woseQ8waJ/pub?output=csv

<img width="809" alt="image" src="https://user-images.githubusercontent.com/18101289/235543495-820bd5ca-2e51-405a-8c93-a581a72fbaae.png">

I think that the format of the dataset is correct, but I might be missing something

**Comment by Marigold** [comment]
@lucasrodes my bad, I forgot to include it in the template. Here's [a fix](https://github.com/owid/etl/pull/1061)

**Comment by lucasrodes** [comment]
It is working now, thanks!
