### ISSUE TITLE
Group datasets into "channels" when publishing

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#106]
## Problem

Right now, we have a pattern where every dataset we care about will have two versions in the ETL, an unharmonized one in `meadow` and a harmonized one in `garden`. So when you search for a dataset, it is not clear at first glance which one you should use.

Secondly, the open numbers datasets are so many that they overwhelm the search results.

## Proposed solution

- We group datasets into _channels_ based on their folder inside the `data/` directory
    - We should have `garden`, `meadow` and `open_numbers` channels initially
- A dataset doesn't know which channel it came from, but it is stored as a categorical variable in the published index
- When you search the catalog, you search `"garden"` by default; but you can also select any other channel, or `"all"`
    - `catalog.channels` should be a list of the options

With this solution, you should be able find data quickly, and default to the best version of the data that we have.

## Steps

* [x] Move open_numbers out of meadow and into its own folder (and update scripts)
* [ ] Move reference into garden (and update scripts)
* [ ] Index and publish channels individually
* [ ] Add channels and lazy loading to owid-catalog-py

**Comment by Marigold** [comment]
All is pretty clear, a couple of questions
1. should we move `open_numbers` from `meadow` into its own `open_numbers` folder? (so that the folder structure aligns with channel definitions) We'd end up with channels: `garden`, `meadow`, `open_numbers`, `examples` (and possibly `backported`). _I think yes_
2. `reference` datasets have their own folder, I'd load them by default together with `garden`

I guess that lazy loading of channels and better logging to show why is it taking so long are in scope of this.

**Comment by larsyencken** [comment]
> 1. should we move `open_numbers` from `meadow` into its own `open_numbers` folder? (so that the folder structure aligns with channel definitions) We'd end up with channels: `garden`, `meadow`, `open_numbers`, `examples` (and possibly `backported`). _I think yes_

I agree, open numbers deserves its own whole channel.

> 2. `reference` datasets have their own folder, I'd load them by default together with `garden`

I'm happy with this too, though I increasingly think we should end up making it just another standard step in garden that depends on an initial walden snapshot, rather than something checked-in to git.

> I guess that lazy loading of channels and better logging to show why is it taking so long are in scope of this.

Seems like it would make sense. I'd probably break it into multiple steps. Something like:

- Move `open_numbers` out of meadow and into its own folder (and update scripts)
- Move `reference` into `garden` (and update scripts)
- Index and publish channels individually
- Add channels and lazy loading to `owid-catalog-py`

**Comment by larsyencken** [comment]
Feel free to edit the issue description and put your todo list there
