### ISSUE TITLE
walkthrough: walkthrough charts does not respect "Timeline selection" in chart revisions

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1064]
### One-liner
Walkthrough charts, when submitting chart revisions, does not respect the "Timeline selection" of the old chart (this has been an old issue with the chart revision tool).

### Environment
- `python -V`: 3.9.4
- Operating system: MacOs 11.6.4
- Working with local, staging or live: live

### Context & details
This is an old issue, and it happens with a few of the charts of [the Global Carbon Budget dataset](https://owid.cloud/admin/datasets/5990). For example, this chart:
![Screen Shot 2023-05-03 at 10 54 19](https://user-images.githubusercontent.com/12246978/235872376-d0e4dcee-1068-4686-befd-0f3a4649a2a5.png)
has a custom value in "Timeline selection". But the new suggested chart does not respect it, and assumes the latest year in the data:
![Screen Shot 2023-05-03 at 10 56 19](https://user-images.githubusercontent.com/12246978/235872655-47cbb7a5-9d24-4d7b-9c01-aa6b9ed039c8.png)

**Comment by lucasrodes** [comment]
This is likely solved in the new version of the chart revision tool. Let me know if that's the case when you work on chart revisions, @pabloarosado.
