### ISSUE TITLE
fasttrack: pandas.errors.ParserError: Error tokenizing data

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1068]
Trying to import this spreadsheet https://docs.google.com/spreadsheets/d/1SXkPBCWup8Mj_wBIlffyh65gArvCsMKUGDTnY0ISpoM/edit?usp=sharing with fast-track, but getting the following internal error:

![image](https://user-images.githubusercontent.com/18101289/235975255-1b6a71cd-ae4f-4880-a274-2ba472c1a5c8.png)

**Comment by Marigold** [comment]
Eh, shoot. The new field `data_url` in `dataset_meta` sheet is not what it seems at first sight. It's used to load external CSV if you can't fit it to `data` sheet. I removed it from your sheet and from template. Can you try again, please?

**Comment by lucasrodes** [comment]
Works, thanks <3 !
