### ISSUE TITLE
data(fao): data cleaning for food explorer belongs in earlier garden steps

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#110]
The `food_explorer` Jupyter notebook does some cleaning up of item codes and filtering by flags, steps that actually belong in `faostat_qcl` and `faostat_fbsh` garden steps.

The reason for this is that, if we want to put this data into grapher from those garden steps, we will need to do all that cleaning again. 

Philisophically, we also want garden to be our "best clean version" of the data, so the cleaning should happen in those garden steps.

**Comment by Marigold** [comment]
We should move population for former countries (Czechoslovakia, USSR, ...) from `food_explorer` somewhere upstream, too.

**Comment by larsyencken** [comment]
Closing this one since @pabloarosado is redoing all the FAO work, which will cover this too.
