### ISSUE TITLE
Add Covid data to ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1100]
Right now, covid data is pushed directly to `data_values` in MySQL. It's fast to do so, but leaves no trace in ETL and prevents us from deprecating `data_values`.

We generate all covid data as CSVs, so we could just write a simple snapshot script that will upload the file to S3 and then empty steps that would get it to grapher.

## Remaining migration steps:

* [x] Some datasets like [COVID-19 - Variants](https://owid.cloud/admin/datasets/5338) have prohibited redistribution, set it on new datasets in admin too (we can't set it from ETL)
* [x] Run chart revisions on all COVID datasets
* [x] Remove code that handles upserts to MySQL from covid-19-data repo https://github.com/owid/covid-19-data/pull/2807
* [ ] #1475 -> split to new issue

**Comment by Marigold** [comment]
This is actually a work in progress. The first COVID dataset has been [migrated here](https://github.com/owid/etl/pull/1236).

**Comment by larsyencken** [comment]
Based on our discussion today, we said that this would be Mojmir's focus this week.

**Comment by larsyencken** [comment]
Nice! You rock!
