### ISSUE TITLE
walkthrough: snapshot doesn't generate `version` properly

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1102]
### One-liner
When using `walkthrough snapshot`, the date saved as `version` is not saved properly in the metadata

### Environment

- `python -V`: Python 3.11.1
- Operating system: macOS Ventura 13.3.1 (a)
- Working with local, staging or live: NA

### Context & details
After running walkthrough snapshot the metadata file is saved with an error: the date for `version` is not enclosed between quotes, as
<img width="547" alt="image" src="https://github.com/owid/etl/assets/63430031/ae95200e-6c29-4fba-9008-5f695360dda7">

It needs to be modified by hand to work properly.

**Comment by lucasrodes** [comment]
Hi @paarriagadap, thanks for reporting!
For me it is working. Are you able to reproduce this? Like, which values are you using for each field in Walkthrough?

**Comment by paarriagadap** [comment]
Hi @lucasrodes! I record a video. I didn't include license yet, but I also tried adding data in those fields and the problem persists.

https://github.com/owid/etl/assets/63430031/561da0cc-c127-4e7b-9f87-b843d2b51cbf

I'm copying the metadata from https://github.com/owid/etl/pull/1103

**Comment by lucasrodes** [comment]
@mojmir, unsure where this error is coming from. I'm trying to fix this in https://github.com/owid/etl/pull/1105.


This is the PR where I added the quotation marks: https://github.com/owid/etl/commit/dc183009c504e33bc0d1d5330f2bcf56302020eb#diff-a0df081b05db14e4d482543a85499615f58f44a0380eb940e5a54dfc504c9d43

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/pull/1110
