### ISSUE TITLE
data: multiple datasets do not follow snake_case naming standards

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#111]
As a convention for making data very easy to work with, we want datasets, tables and columns to use `snake_case` variable names.

I'd propose we clean them up, and then modify the `Table` and `Dataset` methods so that they enforce this on save, giving a nice error message if it's violated.

**Comment by Marigold** [comment]
+1 to this, I never know whether to use `-` or `_`, some asserts would certainly help

**Comment by larsyencken** [comment]
This is more important than I thought, since we already generate heaps of datasets that aren't compliant and will only create more.

I tried briefly to load our catalog into `duckdb` and the poor naming conventions became a problem quickly.

I spotted living planet, GHO, and FAO as all having not-ideal naming conventions. Better that we fix it sooner!

**Comment by Marigold** [comment]
On it, my brain barely works on Fridays anyway, so this is an ideal task!
