### ISSUE TITLE
Update `pyright` type checker

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1113]
I'm a bit annoyed that VSCode is showing me tons of type errors, while running `make check-typing` or just `pyright` shows everything is all right. The reason is that we use outdated `pyright` version. I thought I'd just upgrade it and fix a few errors, but I got **1223 errors** with the newest version...

Most of these errors were caused by mixing `Table` class with pandas functions. Commands like `assign`, `pivot` or `merge` all return `DataFrame` object (it's possible that metadata still works though, even if type checker thinks it's a different object). To fix them all we'd have to either:

1. Have replacements for all functions & methods with proper type hints, e.g.
```python
def pivot(*args, **kwargs) -> Table: 
    return pd.pivot(*args, **kwargs)
```
2. Cast to `Table` after every operation, e.g.
```python
tb = cast(Table, pd.pivot(...))
```
3. Use `# type: ignore` pretty much everywhere

Upgrading pyright and fixing all these would force us to use `Table` object, though I'm not sure if that's realistic (this would be annoying especially for old datasets).

cc @pabloarosado as this is somehow relevant to your efforts

**Comment by pabloarosado** [comment]
Thanks @Marigold. I think options 2 and 3 are quite annoying, and will create unnecessary code in all new data steps. So in my view, the only options are:
0. Reverting the walkthrough changes so that we use again dataframes by default (for now).
1. Create a module `catalog.transformations` (or any other name) with all common functions with the right types (as you suggested), but actually returning tables:
```
def pivot(*args, **kwargs) -> Table: 
    return Table(pd.pivot(*args, **kwargs))
```
Then in a future PR (what I'm working on now) we can improve these functions to keep metadata and have processing info.

What do you think?

**Comment by pabloarosado** [comment]
I've just scanned all snapshots, meadow, garden and grapher steps and found the following uses of `pd.`, excluding `pd.DataFrame` (there's some noise, but the main uses are clear):
| function                          |   count |
|:----------------------------------|--------:|
| pd.merge                          |     320 |
| pd.concat                         |     214 |
| pd.read_csv                       |     209 |
| pd.NA,                            |     134 |
| pd.read_excel                     |      66 |
| pd.Series                         |      37 |
| pd.MultiIndex.from_product        |      16 |
| pd.to_datetime                    |      15 |
| pd.Timestamp                      |      11 |
| pd.NA                             |      10 |
| pd.ExcelFile                      |       9 |
| pd.read_sql                       |       8 |
| pd.isnull                         |       7 |
| pd.to_numeric                     |       7 |
| pd.notnull                        |       6 |
| pd.read_feather                   |       5 |
| pd.read_json                      |       4 |
| pd.Int64Dtype                     |       4 |
| pd.unique                         |       4 |
| pd.set_option                     |       2 |
| pd.DateOffset                     |       2 |
| pd.isna                           |       2 |
| pd.NA will be used.               |       2 |
| pd.Series) -> np.ndarray[Any, np. |       2 |
| pd.StringDtype                    |       1 |
| pd.Series, catalog.Variable]) ->  |       1 |
| pd.option_context                 |       1 |
| pd.pivot                          |       1 |
| pd.Series,                        |       1 |
| pd.Series).stack                  |       1 |
| pd.json_normalize                 |       1 |
| pd.Series = units.str.contains    |       1 |
| pd.RangeIndex                     |       1 |
| pd.read_table                     |       1 |
| pd.NA)                            |       1 |
| pd.melt                           |       1 |
| pd.MultiIndex.from_arrays         |       1 |
| pd.to_numeric, errors="coerce")   |       1 |
| pd.get_dummies                    |       1 |

For a moment I was surprised that `melt` and `pivot` are only used once. But they are most of the time used as methods of a table (e.g. `tb.melt(...)`) which already returns a table.

**Comment by lucasrodes** [comment]
Thanks for bringing this up, @Marigold!

Ideally, solution 1. would be my preferred. Maybe we should define a decorator ensuring the output is a `Table` object?

In your sample code, @pabloarosado,

> ```python
> def pivot(*args, **kwargs) -> Table: 
>     return Table(pd.pivot(*args, **kwargs))
> ```

the returned object could potentially not have metadata, right?

Actually, we might be interested in defining wrapper functions around `pandas` default functions to track what transformations we have applied. Even if at table level, these might still be useful.

**Comment by pabloarosado** [comment]
Hey @lucasrodes correct: to begin with, the returned object will lose its metadata. But at least it lets us keep working with Table objects in data steps.
On the next iteration (which is what I'm working on now) we would add some logic to those functions so that metadata is respected. However, I'm not sure if the best way is via wrapper functions, or simply editing those functions. If you think about it, the way we handle metadata differs from one function to another.

**Comment by Marigold** [comment]
It might be also possible to monkey patch methods like `pd.merge`, `pd.concat`, ... to return `Table` if given `Table` object. I'm not sure if that would work, it's the darkest black magic out there (monkey patching with `@overload` is our fast track to hell...). Although if you plan to do some custom metadata magic in those functions, then having special module is better than monkey patching.

**Comment by pabloarosado** [comment]
After some tests and conversations, I think that this issue only affects us if we decide to upgrade pyright to its latest version. If we keep using 1.1.288 we don't have any typing issues. In fact, `pd.merge`, `pd.concat`, `pd.pivot` and `pd.melt` seem to respect the type of its first argument (e.g. if you merge `pd.merge(tb, df)`, the output is a table). So for now we don't have to change anything to start working with tables.
