### ISSUE TITLE
walkthrough: Introduce variable mapping quality indicator in `walkthrough charts`

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#1131]
### One-liner
In the `walkthrough charts`' _Map variables_ section it could be nice to have an indicator of the precision of the matching, to guide through good or bad matches.

### Environment

- `python -V`: Python 3.11.1
- Operating system: macOS Ventura 13.3.1 (a)
- Working with local, staging or live: staging

### Context & details
I was testing a fix for https://github.com/owid/etl/issues/819 using the new `walkthrough charts` on staging with two completely different datasets. The platform automatically matched 10 variables, but none of them are actually even similar, so this extreme case might show the need for reinstating a mapping accuracy indicator (as it was available on the previous version of the platform)
![image](https://github.com/owid/etl/assets/63430031/9edf0152-4268-4d27-9229-51477dfaa852).

When there are multiple variables to assign the chances of missing a bad match increase, so adding the accuracy somewhere (as a number or with colors) might reduce this risk.

**Comment by lucasrodes** [comment]
Thanks for raising this. Potential solution for this: #1136
