### ISSUE TITLE
Explicitly pass `population` and `regions` to `geo` module instead of implicitly loading them

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1143]
Our [geo](https://github.com/owid/etl/blob/master/etl/data_helpers/geo.py#L50) module provides useful functions for region aggregations and these functions need `population` and `regions` datasets to work properly. The problem is that these datasets are currently optional and load the latest dataset by default. That can be problematic in two ways:
1. Step dependencies can use different version of regions / population
2. Updating regions / population can cause unexpected changes to datasets

There are more ways how to fix this:
1. Explicitly pass both population and regions to these functions
2. Create `state` for every step which would contain all dependencies and use them in `geo` module (`state` could be saved in a global variable, as a dictionary / class in some module or in ENV. This is fine since every step runs in a separate process)
3. Similar to 1., but wrap all datasets in key_indicators (i.e. add regions there) and explicitly pass only a single dataset

The ultimate goal is to get rid of functions `geo._load_population`, `geo._load_countries_regions` and `geo._load_income_groups`

cc @pabloarosado

**Comment by Marigold** [comment]
I believe this is still a problem. Keeping it open as nice to have.

**Comment by danyx23** [comment]
@Marigold @larsyencken when talking about it in the issue triage we just said that it is not very important to fix this for the old datasets. Going forward it would be good to raise a warning if the function is used that loads the population or regions data implicitly. The question is if we want to raise the warning for old datasets - is it possible to only raise warnings if the version is newer than a certain date?

**Comment by larsyencken** [comment]
Yes, the ETL already has a `strict` mode which defaults to auto, but you can force it with `--strict/--no-strict` arguments. We are currently saying everything after 2023-06-01 should be strict mode. We could raise a warning if not in strict mode, and an error if you are in strict mode.

**Comment by danyx23** [comment]
@larsyencken ok cool - I think that is something that should be simple to do and quite useful. I think an error if in strict mode is mandatory, the warning for older ones should maybe depend a little on how many warnings this raises - several hundred warnings wouldn't be useful
