### ISSUE TITLE
Covid datasets are still using Timor instead of East Timor

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1183]
We recently [renamed](https://github.com/owid/etl/pull/1077) Timor -> East Timor. Covid datasets like [COVID-19 - Vaccinations](https://owid.cloud/admin/datasets/5234) are still using the old naming. We should either change country names in covid scripts too or migrate all covid datasets to ETL and then rename it. @lucasrodes is it straightforward to Timor -> East Timor and Faeroe Islands -> Faroe Islands or should I prioritise covid migration?

**Comment by lucasrodes** [comment]
Thanks for raising this, @Marigold. I'll update the scripts accordingly ー should be doable!

**Comment by danyx23** [comment]
@Marigold is this still true? Lucas said that he thinks this is no longer the case with the move of the COVID pipeline to the ETL? Could you clarify where this would have to still be changed?

In a brief check we saw that the COVID explorer still shows Timor - is this what you mean or is that a separate issue?

**Comment by Marigold** [comment]
We have COVID in ETL now, but haven't run chart revision on the new datasets yet. It's fixed there. I plan to do that this week, so closing this.
