### ISSUE TITLE
Transferring charts from staging environments to live

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1230]
We are still doing manual deployments for the sake of convenience, especially when dealing with new datasets. The combination of manual and automatic deployments works pretty well for us, but conducting manual deployments against production environments is always somewhat risky.

With automated staging servers, we can create and review charts there. However, the problem lies in the fact that there's no way to transfer these charts to the live environment once we merge and deploy a dataset. We could potentially develop a tool (perhaps starting with a CLI, or even implementing a button in the admin interface, or a simple PyWebIO application) that would enable the transfer of staging charts to the live environment, pending approval. Variable IDs in the charts would need to be remapped, since they could differ between the staging and live environments. However, we can match them based on their namespace, version, and short name.

**Comment by danyx23** [comment]
This needs a bit more discussion but we should try to get it to be ready to be worked on soon. Putting this on the discussion list for 2023-08-03

**Comment by Marigold** [comment]
Duplicate of https://github.com/owid/etl/issues/1749
