### ISSUE TITLE
Merge functions `copy_metadata` and `copy_metadata_from` in `catalog.tables`

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1269]
Currently (after mergin [this PR](https://github.com/owid/etl/pull/1251)), `Table` has both a `copy_metadata_from` and a `copy_metadata` method.

* `copy_metadata_from` is fast (it avoid deep copies) but doesn't copy variables metadata, and does changes in place.
* `copy_metadata` copies variables metadata and has an `inplace` argument, but it's slow (it uses deep copies).

Both functions would need to be merged, combining features and avoiding issues.

**Comment by Marigold** [comment]
@pabloarosado are you working on this? I could implement this pretty easily after we merge https://github.com/owid/etl/pull/1455. Any preference from `copy_metadata_from` and `copy_metadata` names?

**Comment by pabloarosado** [comment]
@Marigold I'm not working on that, but I'm changing a few things on `variables` and `tables` at the moment. I'll create a PR very soon. Maybe after that, if you want, you can look into that.
I'd prefer the shorter version, `copy_metadata` which has been used more times than the other.
