### ISSUE TITLE
Improve performance of function `get_unique_sources_from_table`

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1270]
As suggested by Mojmir, we could improve function `tables.get_unique_sources_from_table`: 
Dataclasses support equality operator, so instead of converting to dict and then to objects again (which could affect performance), you could do something like this
```python
unique_sources = []
for source in sources:
    if source not in unique_sources:
        unique_sources.append(source)
```

**Comment by Marigold** [comment]
@pabloarosado I've done a comparison between our old nightly run and [the new run](https://buildkite.com/our-world-in-data/etl-full-private-rebuild-weekly/builds/311). It's a bit slower, but not a big deal.

Here's the [comparison in a sheet](https://docs.google.com/spreadsheets/d/1JvT2wpHs1VTAaA20o8Ro7Ui2ZUUYbKiyaftSKebSQh4/edit?usp=sharing). We could use it to choose candidates for optimisation like `data://garden/faostat/2023-06-12/faostat_ti`
