### ISSUE TITLE
Stop merging sources, add an N:M relationship for variables <-> sources

### ISSUE THREAD

**Issue by danyx23** [owid/etl#1310]
When we decided to add Origin next to Source it was unclear if we should also change our database so that there can be multiple Sources for a single indicator/variable. As we now want to track whether sources have been created from Origin, we will need to stop merging Sources before inserting them into the database

**Comment by Marigold** [comment]
My hunch tells me that this might get tricky and quickly turn into quite an effort. We should think about alternatives first (if there are any) and try to find a solution that doesn't involve making such architectural change to our DB.

**Comment by danyx23** [comment]
Decided not to do this after some discussions
