### ISSUE TITLE
Create staging environment for ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#136]
> One problem that has come up multiple times already with the etl is the inability to use "staging" data.
This has come up multiple times already with the global food explorer, where I would love to put a quick prototype of it up on a staging server just to show hannah and lucas what the current etl PR would change.
However, I cannot do that since the only public URL for etl data is the owid-catalog DO bucket - there is no staging bucket, and I cannot just simply point to a different branch which I could if it was on GH.

Let's create proper `staging` environment with staging bucket. There's always the risk that somebody else will checkout a different branch and ruin your data, but if you only want to show off your data for a day or so that risk should be low enough.

Scope:
* [x] create `owid-catalog-staging` bucket in S3
* [x] set up `etl-staging` on analytics server
* [x] set up webhook listening to pushes to `staging` branch in `etl`

Out of scope:
* [ ] publish to staging grapher
* [ ] load staging data from owid-catalog-py

**Comment by marcelgerber** [comment]
Hi @Marigold, what's the current state for this? Would be helpful for reviewing #138 (but I can do without too!)

**Comment by Marigold** [comment]
@marcelgerber I think it's good to go, but Lars can't finish his review. Could you take a look and finish his review so that I can merge it, please? (it's a low risk, so don't overthink it)

**Comment by marcelgerber** [comment]
Hm, I'm out of my comfort zone with this large amount of bash scripts. Maybe @danyx23 can do the final review of owid/analytics#38 instead?
Otherwise, it can also wait until Lars is back, no problem.

**Comment by danyx23** [comment]
I'll have a look!

**Comment by Marigold** [comment]
Pushing to `staging` branch now triggers `etl` which publishes `garden` channel to [S3](https://cloud.digitalocean.com/spaces/owid-catalog-staging?i=8b5115)
