### ISSUE TITLE
Tasks: Data pages ETL workflow

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1364]
Tracking ETL work for Data Pages

### Must have
* [x] Propagate `Origins` when working with `Table` class
* [x] `Origins` support in walkthrough
* [x] `Origins` support in fast-track
* [x] #1370

### Nice to have
* [x] Dummy dataset with all available fields
* [x] Data pages support in fast-track

**Comment by danyx23** [comment]
@Marigold Walkthrough is mostly implemented, right? How long do you think fast-track will take?
