### ISSUE TITLE
Write guidelines on how the new metadata should be used

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#1474]
- Work on centralising the documentation in one place: https://docs.owid.io/projects/etl/en/latest/architecture/metadata/
- Work on official docs: https://github.com/owid/etl/pull/1531
- Work on new tool wizard (contains guidelines)
  - https://github.com/owid/etl/pull/1539
  - https://github.com/owid/etl/issues/1563
- Final changes:
  - metadata field renamings:
    - https://github.com/owid/etl/pull/1599
    - https://github.com/owid/etl/issues/1584
  - wizard and docs:
    - https://github.com/owid/etl/pull/1601
    - https://github.com/owid/etl/issues/1566
  - improve description of metadata fields
    - https://github.com/owid/etl/pull/1602#pullrequestreview-1625485783

**Comment by lucasrodes** [comment]
- Work on centralising the documentation in one place: https://docs.owid.io/projects/etl/en/latest/architecture/metadata/
- Work on official docs: https://github.com/owid/etl/pull/1531
- Work on new tool wizard (contains guidelines)
  - https://github.com/owid/etl/pull/1539
  - https://github.com/owid/etl/issues/1563

**Comment by lucasrodes** [comment]
Finished centralising the documentation (see details: https://github.com/owid/etl/issues/1566)

- Docs updated: https://docs.owid.io/projects/etl.
- New tool with guidelines: `etl-wizard`.
