### ISSUE TITLE
Create a user-friendly way how to set metadata

### ISSUE THREAD

**Issue by Marigold** [owid/etl#148]
Setting dataset/table/variable metadata directly in the python module can be painful. Multi-line descriptions, boilerplate code, etc... Using YAML files for metadata nicely separates code from metadata. There [were attempts](https://github.com/owid/etl/blob/master/etl/grapher_helpers.py#L76) to make this as user-friendly, but I don't think it's there yet. Now that we have enough examples, we should think about the best way and consolidate all those functions.

Add `update` method to replace `setattr` lines https://github.com/owid/owid-catalog-py/blob/master/owid/catalog/meta.py#L156

**Comment by larsyencken** [comment]
Is this still something that you're thinking about, Mojmir?

**Comment by Marigold** [comment]
Closing, this is just nice to have and can be done later.
