### ISSUE TITLE
Large datasets block up the jobs queue and timeout after 4hrs

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#1483]
There are now some very big datasets in the etl, specifically, in this case, the IHME Global Burden of Disease (`ihme_gbd/2019`). A recent update of these steps has caused BuildKite to time out at 4hrs, meaning the job restarts, holding up other datasets that are waiting. 

Perhaps a solution would be to prioritize datasets in the queue that have a smaller number of variables so they aren't held up. 

Relevant [Slack discussion](https://owid.slack.com/archives/C0193RW5E2J/p1692101469051639)

**Comment by Marigold** [comment]
I increased the timeout from 4 hours to 10 hours and optimised upserts to grapher a bit. Prioritising would be hard as we don't know runtime in advance, but running [steps in parallel](https://github.com/owid/etl/pull/1331) could be helpful in unblocking the queue.

Ideally we merge updates to large datasets later in the afternoon, but I know it's not always possible (and I do it from time to time too...).

**Comment by Marigold** [comment]
We pulled timings from Buildkite [to a spreadsheet](https://docs.google.com/spreadsheets/d/1JvT2wpHs1VTAaA20o8Ro7Ui2ZUUYbKiyaftSKebSQh4/edit?usp=sharing). It's not updated regularly, but could be useful
