### ISSUE TITLE
Add descriptions to JSON schemas to display help in VSCode

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1499]
Add fields `description` to [JSON schema files](https://github.com/owid/etl/blob/master/schemas/snapshot-schema.json) to display help in VSCode (assuming one has installed [YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)). 

We could reuse these descriptions in walkthrough by dynamically loading them from the JSON file.

**Comment by lucasrodes** [comment]
With the new helpers from https://github.com/owid/etl/pull/1533, this will be simpler.

I'll work on improving the experience with `walkthrough snapshot`.

**Comment by lucasrodes** [comment]
I am working on centralising the metadata description (examples and other specs) in the [schemas](https://github.com/owid/etl/tree/master/schemas) in #1539

**Comment by lucasrodes** [comment]
This is now available
