### ISSUE TITLE
Backporting is prone to circular dependencies

### ISSUE THREAD

**Issue by Marigold** [owid/etl#153]
## Problem

If we `backport` a dataset and then use it in grapher step in ETL which updates the dataset itself, then we end up with circular dependency. This should be rare, nevertheless we should make sure that doesn't happen as it would ruin the dataset.

## Solution

Either find those circular dependencies from `dag.yml` file or propagate dependencies to grapher so that we know it was built from a backported dataset.

**Comment by larsyencken** [comment]
As a concrete proposal here, I would suggest we update the `dataset` table to add fields that specify exactly where a certain table came from, at very least `etl_path` and `input_checksum`.

When exporting to grapher, throw an error and fail if an existing dataset is there but does not come from the ETL.

When backporting, throw an error and refuse if the dataset comes from the ETL.

**Comment by larsyencken** [comment]
#94 is the proposed solution to this already I think
