### ISSUE TITLE
Allow grapher datasets with the same title, but different namespace/version

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1544]
It should be possible to have datasets in grapher database `datasets` table with the same title, but different `namespace` and/or `version`.

**Comment by Marigold** [comment]
I was just about to take a look at this. Since we now same names for different versions, should we display its path somewhere in admin dataset page? Something like this

<img width="500" alt="image" src="https://github.com/owid/etl/assets/1550888/c8a5d4b5-4df5-464e-91f8-a2f27e64ce68">

**Comment by pabloarosado** [comment]
Thanks @Marigold yes, that would be useful.

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/owid-grapher/pull/2581
