### ISSUE TITLE
Change default format of dataset titles.

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1545]
To be done after https://github.com/owid/etl/issues/1544

With the new metadata, we have the following options for dataset titles:
1. `Title (producer, year)`. This is our current default format, but it involves additional manual work (e.g. changing 2023 -> 2023a -> 2023b), and it's redundant (since we already have `version` in the `datasets` table.
2. `Title`. This is the cleanest option in terms of metadata handling, although currently this would not let us search for a dataset by the producer's name (since `producers` is not in the `datasets` table) in the admin, which may be inconvenient in some cases.
3. `Title (producer)`. Therefore, this seems to be a good tradeoff.

Do we all agree?
* [ ] @lucasrodes 
* [ ] @danyx23 
* [x] @Marigold 

Once decided, I'll change the metadata guidelines.

**Comment by lucasrodes** [comment]
An alternative would be go with option 2 in _ETL_, but then in the Grapher step, under the hood, combine `title` with `producer` to generate option 3 in _Grapher database_.

**Comment by pabloarosado** [comment]
After several discussions, I think we all agree that the best option is to use a dataset title that does not include a reference to any other metadata field (like producer or year). We'll need to improve our admin, search engines (and other tools, like the etl-wizard charts) to make it easy to search by title and other metadata fields.
