### ISSUE TITLE
Per capita variables use display name `population`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1569]
I've noticed that some variables like [Per capita CO2 consumption](http://staging-site-mojmir/admin/variables/738081) use `Population` as a display name.

This happens because dividing by population combines metadata of both variables and if the numerator doesn't have `display` metadata set, it'll inherit it from `Population`.

Maybe we could stop (mis?)using `display.name` and focus on setting the proper `title` instead. @pabloarosado what do you think?

```
v1 = Variable([1,2,3], name='co2')
v1.metadata.title = 'co2'
v2 = Variable([1,2,3], name='population')
v2.metadata.display = {
    'name': 'Population',
    'numDecimalPlaces': 0
}
per_capita = v1 / v2
per_capita.metadata
```
<img width="276" alt="image" src="https://github.com/owid/etl/assets/1550888/28c22efd-9a54-4426-8bdd-68e4db758dce">

**Comment by pabloarosado** [comment]
Hi @Marigold thanks for finding this, I had not thought about this possibility. But in the example you give I don't see `Population` showing anywhere. Can you screenshot or pinpoint an example where this happened?

We could implement some logic on the function that combines metadata (for `title`, `display.name`, `presentation.title_public`, and maybe others). If the operation is `/`, then ignore the title of the second parent. But this might be annoying when doing temporary operations between variables, I'd need to think about it.

**Comment by Marigold** [comment]
Here's an [example](https://owid.cloud/admin/variables/738081) that shows "Population" in the Preview chart. This is not a big problem now, but it becomes more annoying for our indicator-centered future with data pages.

**Comment by pabloarosado** [comment]
After merging https://github.com/owid/etl/pull/1676 now divisions where the numerator has no display and the denominator has display, should yield no display. This should fix the issue.
