### ISSUE TITLE
Final metadata changes

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1584]
Final changes to metadata fields **(to be confirmed during the data call on Monday 11th of September)**:

## Changes in origin metadata fields
* [x] Rename `dataset_url_main` -> `url_main`. For simplicity, and to avoid the confusing word "dataset".
* [x] Rename `dataset_url_download`-> `url_download`. Idem.
* [ ] Rename `dataset_title_producer`-> `title`. This will be the title of the data product.
* [ ] Rename `dataset_description_producer`-> `description`. This will be the description of the data product.
* [ ] Rename `dataset_title_owid` -> `title_snapshot`. This will be the title of the snapshot, that **may often contain** the title of the data product. Mostly for internal or super users.
* [ ] Rename `dataset_description_owid`-> `description_snapshot`. This will be the description of the snapshot, which **should not contain** the description of the data product, and should therefore be additional to `description`. Mostly for internal or super users.
* [ ] Rename `citation_producer`-> `citation_full`. This field is not necessarily written by the producer, and is the only place where we can host a full citation).

## Changes in indicator's presentation metadata fields
* [ ] Rename `producer_short` -> `attribution_short`. Given that it could also be a dataset name, in the same way that we have `attribution_short` at the origin level.
* [x] Rename `topic_tags_links` -> `topic_tags`. For simplicity, and because they are not links.

## Changes to transfer to grapher
* [ ] When creating new charts and data pages, we could construct the subtitle as '{description_short} Measured in {unit}'. **Unclear, to be discussed.**

**Comment by lucasrodes** [comment]
Thanks for putting thought into this and for the summary, Pablo! Overall, I agree with all the modifications.

Minor comment:

From your definitions, it seems like `title` and `description` would be required and `data_product_title` and `data_product_description` would not and fall back to the formers when not specified. Do you prefer this over the opposite? E.g. encouraging users always to set `data_product_title` and `data_product_description`; and if the snapshot != data product, they need to specify `title` and `description`. I don't feel strongly about any of these, but maybe you have thought about this?

**Comment by Marigold** [comment]
@pabloarosado I'm starting work on renaming and will take care of all three lines - ETL, MySQL and Data Page. Let me know if you have any other additions.

**Comment by pabloarosado** [comment]
Hi @Marigold I'm going to update now the description above to include the changes we discussed yesterday at the data call.
