### ISSUE TITLE
⚠️ explorers: markdown → html

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1643]
In #1422, we only looked at descriptions using HTML in ETL. However, there are still some charts and explorers using HTML: Those from manual configs in explorers, datasets that were manually imported in the past, and datasets imported via [`importers`](https://github.com/owid/importers).

This issue tries to address this for Explorers. I've included the list of explorers below; could you check these as those are fixed? 

### Guidelines
There are different types of explorers, and reviewing these might be different.

- **Indicator-based**: We should go back to the snapshot in ETL, which is the source for the indicator. Example: [animal-welfare](https://ourworldindata.org/explorers/animal-welfare)
- **Chart-based**: We should investigate where the dataset powering the used charts comes from. If from ETL, check ETL. Other sources could be `importers` or manual imports. Example: [democracy](https://ourworldindata.org/explorers/democracy)
- **Manual config**: The explorer configuration is written in the admin explorer configm. We need to edit this. Example: [coronavirus-data-explorer](https://ourworldindata.org/explorers/coronavirus-data-explorer)
- **Templating**: The explorer configuration was generated automatically using [owid-content](https://github.com/owid/owid-content/). Example: [population-and-demography](https://ourworldindata.org/explorers/population-and-demography)

### List of explorers to review
(only public ones)

- [x] [coronavirus-data-explorer](https://owid.cloud/admin/explorers/coronavirus-data-explorer)
- [x] [animal-welfare](https://owid.cloud/admin/explorers/animal-welfare)
- [x] [democracy](https://owid.cloud/admin/explorers/democracy)
- [x] [incomes-across-distribution-comparison](https://owid.cloud/admin/explorers/incomes-across-distribution-comparison): https://github.com/owid/owid-content/pull/31
- [x] [inequality-comparison](https://owid.cloud/admin/explorers/inequality-comparison): https://github.com/owid/owid-content/pull/31
- [x] [inequality](https://owid.cloud/admin/explorers/inequality): https://github.com/owid/owid-content/pull/31
- [x] [lis-expanded-poverty](https://owid.cloud/admin/explorers/lis-expanded-poverty): https://github.com/owid/owid-content/pull/31: https://github.com/owid/owid-content/pull/31
- [x] [lis-incomes-across-distribution](https://owid.cloud/admin/explorers/lis-incomes-across-distribution): https://github.com/owid/owid-content/pull/31
- [x] [lis-inequality](https://owid.cloud/admin/explorers/lis-inequality): https://github.com/owid/owid-content/pull/31
- [x] [poverty-comparison](https://owid.cloud/admin/explorers/poverty-comparison): https://github.com/owid/owid-content/pull/31
- [x] [wid-incomes-across-distribution](https://owid.cloud/admin/explorers/wid-incomes-across-distribution)
- [x] [wid-inequality](https://owid.cloud/admin/explorers/wid-inequality)
- [x] [food-footprints](https://owid.cloud/admin/explorers/food-footprints)
- [x] [climate-change](https://owid.cloud/admin/explorers/climate-change)
- [x] [incomes-across-distribution-ppp2017](https://owid.cloud/admin/explorers/incomes-across-distribution-ppp2017): https://github.com/owid/owid-content/pull/31
- [x] [pip-inequality-explorer](https://owid.cloud/admin/explorers/pip-inequality-explorer): https://github.com/owid/owid-content/pull/31
- [x] [poverty-explorer-2011-vs-2017-ppp](https://owid.cloud/admin/explorers/poverty-explorer-2011-vs-2017-ppp): https://github.com/owid/owid-content/pull/31
- [x] [poverty-explorer-expanded](https://owid.cloud/admin/explorers/poverty-explorer-expanded): https://github.com/owid/owid-content/pull/31
- [x] [poverty-explorer](https://owid.cloud/admin/explorers/poverty-explorer): https://github.com/owid/owid-content/pull/31
- [x] [migration](https://owid.cloud/admin/explorers/migration)
- [x] [population-and-demography](https://owid.cloud/admin/explorers/population-and-demography): https://github.com/owid/owid-content/pull/31
- [x] [water-and-sanitation](https://owid.cloud/admin/explorers/water-and-sanitation)
- [x] [global-food](https://owid.cloud/admin/explorers/global-food)
- [x] [crop-yields](https://owid.cloud/admin/explorers/crop-yields)
- [x] [co2](https://owid.cloud/admin/explorers/co2)
- [x] [ipcc-scenarios](https://owid.cloud/admin/explorers/ipcc-scenarios)
- [x] [influenza](https://owid.cloud/admin/explorers/influenza)
- [x] [global-health](https://owid.cloud/admin/explorers/global-health)
- [x] [fertilizers](https://owid.cloud/admin/explorers/fertilizers)
- [x] [air-pollution](https://owid.cloud/admin/explorers/air-pollution)
- [x] [fish-stocks](https://owid.cloud/admin/explorers/fish-stocks)
- [x] [habitat-loss](https://owid.cloud/admin/explorers/habitat-loss)
- [x] [impacts-of-energy-sources](https://owid.cloud/admin/explorers/impacts-of-energy-sources)
- [x] [migration-flows](https://owid.cloud/admin/explorers/migration-flows)
- [x] [monkeypox](https://owid.cloud/admin/explorers/monkeypox)
- [x] [natural-disasters](https://owid.cloud/admin/explorers/natural-disasters)
- [x] [natural-resources](https://owid.cloud/admin/explorers/natural-resources)
- [x] [plastic-pollution](https://owid.cloud/admin/explorers/plastic-pollution)
- [x] [ukraine-russia-food](https://owid.cloud/admin/explorers/ukraine-russia-food)
- [x] [us-covid-data-explorer](https://owid.cloud/admin/explorers/us-covid-data-explorer)
- [x] [energy](https://owid.cloud/admin/explorers/energy)
- [x] [food-prices](https://owid.cloud/admin/explorers/food-prices)

**Comment by lucasrodes** [comment]
some work for explorers based on templating done here: : https://github.com/owid/owid-content/pull/31

**Comment by pabloarosado** [comment]
@lucasrodes, after merging https://github.com/owid/owid-content/pull/33 all explorers in the list should be cleared of HTML tags. Shall we close the issue?

**Comment by lucasrodes** [comment]
Thanks for your work, @pabloarosado @paarriagadap 

Closing this!
