### ISSUE TITLE
metadata: Table <T>, column <C> has no origins.

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1668]
### One-liner
Metadata on `origins` is missing for indicators.

### Context & details

In branch `data/peace-diehl`, when running `etl peace-diehl` I get the following warning:

```
2023-09-26 13:19:00 [warning  ] Table peace_diehl, column peace_scale_level has no origins.
```

I think this comes from the meadow step, where I use a custom way of reading the Snapshot (instead of the library defaults `snap.read*` methods). This is because of the odd format of the data provider. In particular, I use:

```python
df = pd.read_fwf(snap.path, header=None)
df = df[0].str.split(",", expand=True)
```

I then convert this into a Table:

```python
tb = Table(df, metadata=snap.to_table_metadata(), short_name=paths.short_name)
```

This preserves metadata at table level, but does not propagate the metadata at indicator level (hence the "column <C> has no origins" warning later in Garden).

How should we go about this?

**Comment by lucasrodes** [comment]
I've created a new function in `owid.catalog.processing`: `read_fwf`, which should add the metadata to the indicators.

However, I am still getting the same warning.

**Comment by lucasrodes** [comment]
I've now tried using

```python
from etl.snapshot import Snapshot
import owid.catalog.processing as pr

snap = Snapshot("war/2023-09-25/peace_diehl.csv")
tb = pr.read_fwf(snap.path, header=None, metadata=snap.to_table_metadata())
```

But `tb[0].metadata` is not showing any metadata.

**Comment by lucasrodes** [comment]
The metadata cannot be stored for indicators with numerical names. That is, when calling `read_fwf`, the returned table has a single column with name `0` (number zero). Instead, if we use a custom string name, metadata is preserved:

```
tb = snap.read_fwf(header=None, names=["data"])
```


Complete solution to my use case is:

```python
# Load data from snapshot.
tb = snap.read_fwf(header=None, names=["data"])
meta_origins = tb["data"].metadata.origins

tb = tb["data"].str.split(",", expand=True)

# Rename columns
tb = tb.rename(columns={col: str(col) for col in tb.columns})

# Ensure metadata in indicators is preserved
for column in tb.all_columns:
    tb[column].metadata.origins = meta_origins
```

**Comment by larsyencken** [comment]
Seems like we need to decide how we want to pass origins to `Table()` during construction.

For snapshots, there's only ever one origin. So `snap.read_xyz()` should pick up the origin. But for a general case, `Table()` should be able to receive a different origin per column.

Marking as "nice to have" for now, we can improve it when we have time or it becomes more painful.
