### ISSUE TITLE
Prettify backported dataset names

### ISSUE THREAD

**Issue by Marigold** [owid/etl#167]
Backported dataset names are naively transformed using [underscore](https://github.com/owid/owid-catalog-py/blob/master/owid/catalog/utils.py#L8) method. This can result in very long and unreadable names. For instance

* `Long-term wheat yields - FAO (2017) & Bayliss-Smith (1984)` -> `long_term_wheat_yields__fao__2017__and__bayliss_smith__1984`
* `Life satisfaction – Eurobarometer (2017)` -> `life_satisfaction__eurobarometer__2017`
* `Age-adjusted female suicide rates, 1950-2005 - WHO (2005)` -> `age_adjusted_female_suicide_rates__1950_2005__who__2005`

Such names can hinder their discoverability in the catalog (and addressing in general). Dataset names are not standardized in grapher schema (e.g. source is appended to dataset name, but not always) which makes automatic transformation nearly impossible. Any transformation would therefore have to be manual. We have only about 800 backported datasets (those used in at least one chart) which is not _that_ much, but new datasets could be problematic.

Possible solutions:
1. Don't bother with nice underscored names and instead make them discoverable by their original name from the catalog
2. Create manual mapping to dataset & table while trying to keep the name as short as possible (we might also group different datasets into a single one with multiple tables)
3. Create manual mapping, but only strip source name
4. Change grapher `dataset` model and split `name` into `dataset_name` and `source_name`

Solution 2 example:
* `Long-term wheat yields - FAO (2017) & Bayliss-Smith (1984)` -> `long_term_wheat_yields`
* `Life satisfaction – Eurobarometer (2017)` -> `life_satisfaction`
* `Age-adjusted female suicide rates, 1950-2005 - WHO (2005)` -> `age_adjusted_suicide_rates` / table `age_adjusted_female_suicide_rates`

Solution 3 example:
* ...
* `Age-adjusted female suicide rates, 1950-2005 - WHO (2005)` -> `age_adjusted_female_suicide_rates_1950_2005`

Who would benefit from nice names though? We don't show them anywhere besides catalog. Perhaps it makes sense to wait until we start using backported datasets and then decide.

(I've started renaming datasets to get a feel for it [here](https://docs.google.com/spreadsheets/d/1VUAbjBBzATt0n_4Vd3bV8MBqfox2EAATcmkwB9wKGWU/edit?usp=sharing))

**Comment by larsyencken** [comment]
This is probably worth its own whole discussion, maybe with a spreadsheet of examples and some popcorn 🍿 

At the dataset level we could probably sort out `short_names` that work for 90% of the cases pretty well. At the variable level, it becomes a whole different ball game. We should discuss a different strategy than just mangling the name there.

This type of addressing should also be part of API discussions.

**Comment by danyx23** [comment]
To discuss with @Marigold: 
* relevant for the API and addressing scheme
* table per variable vs table per dataset

**Comment by larsyencken** [comment]
From short discussion with @danyx23:

> The naming of historical backported data is less important than the naming of *new* data that goes through the grapher fast-track (uploaded via admin). Perhaps instead we should prioritise adding `short_name` and `version` fields to the MySQL model and the admin.

**Comment by larsyencken** [comment]
From chatting with @danyx23:

- Backports could be left with "bad" names, as long as there aren't non-OWID consumers
- Non-OWID consumers should get things via the browsable data catalog, when it's ready
    - For backports, we should probably not use short names for this data
- We should still add `short_name` and `version` to the grapher MySQL model for `datasets` and `variables`, and set them at data upload time (and on ETL-to-grapher step)

**Comment by larsyencken** [comment]
Closing this issue, replacing with:

- #314
