### ISSUE TITLE
metadata: Find a way to identify where metadata was not propagated

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1679]
### One-liner
We need a way to identify where metadata was lost within an ETL step.

### Context & details
While working on an ETL step, sometimes you do an operation that did not respect propagation of metadata. And if you don't notice it, you may reach the end of the step and then need to go back and figure out where metadata was lost.

We need to avoid that situation. I can think of a few options:
* The easiest is to move the function `owid.catalog.tables.check_all_variables_have_metadata` to `etl.helpers` (and possibly rename it to something shorter). This function checks if all columns have at least one origin. This function can be used (manually) every now and then while debugging.
* Add a method to `Table` that checks the same thing. It could be something like `tb.check_metadata()`.
* Create a new tool that executes an etl step and goes line by line, checking if at any point an indicator loses its origins. Not sure how this would look like.

**Comment by Marigold** [comment]
Ideas 1. and 2. sound good (2. is more slick in my opinion). I do this quite often, too, and I tend to add breakpoints `__import__('ipdb').set_trace()` and print metadata. Having such a method would save me some time.

@pabloarosado there are too many assignees :), pick one and let him do this.

**Comment by Marigold** [comment]
Just added `tb.check_metadata()` (feel free to modify it as you want @pabloarosado, I didn't notice you assigned yourself)

**Comment by pabloarosado** [comment]
Hey @Marigold thanks for the heads-up. I'm trying something here, if it works out, I'll do a PR soon.

**Comment by Marigold** [comment]
Thanks to @pabloarosado, we can now set `Table.DEBUG = True` and see where it fails. See https://github.com/owid/etl/pull/1697
