### ISSUE TITLE
Adding country alias to `regions.yml` triggers all steps that depend on population

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1708]
Country aliases are stored in [regions.yml](https://github.com/owid/etl/blob/master/etl/steps/data/garden/regions/2023-01-01/regions.yml) file. Adding an aliases triggers rebuild of step `data://garden/demography/2023-03-31/population` plus all 200+ steps that depend on it. Aliases are used in interactive harmonisation, but don't affect the population dataset.

Potential solutions:

1. Move aliases to a different file that ETL'd ignore
2. Special checksum calculation for `regions.yml` that would exclude aliases
3. Exclude `regions.yml` from checksum calculation and increment `__etl_epoch__` whenever we make an important change to regions
4. Version (special) individual files by adding `# version: 123` syntax to the top of the file and use it instead of checksum (we'd have to remember to change it when renaming countries)

@pabloarosado what do you think? Have any better ideas? My favourite is 3., even though it'd mean rebuilding the entire ETL (not just those with population as dependencies)

**Comment by Marigold** [comment]
Fixed by adding a special if branch for `regions.yml`. It's not the prettiest solution but is simple and does the job.

**Comment by pabloarosado** [comment]
Thanks for fixing this @Marigold! I would have thought that separating the aliases into its own yaml file, ignored by ETL, would be a good solution. But if this hack works, that's good.

**Comment by Marigold** [comment]
> I would have thought that separating the aliases into its own yaml file, ignored by ETL, would be a good solution.

I thought that too, but that would need tons of changes. Let's just keep kicking the can down the road...
