### ISSUE TITLE
Improve CI performance & PR experience in general

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1710]
Since we create tons of PRs, improving the workflow even by a bit could make the dev experience much nicer. Let's collect what bothers us and how we could improve it in this issue.

### Ultra slow CI

Sometimes building ETL of your branch can take several hours. This is a [real issue](https://github.com/owid/etl/issues/1709) and is being fixed right now.

### Reducing CI overhead

Running `buildkite/etl-unit-tests` takes more than 3 minutes, `buildkite/etl-build-public-datasets-branch` takes 6 minutes minimum. What's the bottleneck? Can we reduce the overhead?

We could [switch to ruff](https://github.com/owid/etl/pull/1017) for linting. Setting `DEBUG=1` could speed up things as well.

### Running ETL without an internet connection

Apparently, `make format` doesn't work without an internet connection. Why exactly? (one reason could be checking `etags` from github)

### Automatic formatting

Sometimes, my PR has just a few lines, and I don't bother running `make format`. Then I go back to my PR only to see that it failed formatting. I don't get to see the results of unit tests and it doesn't start ETL build. There are a few things we could do

1. Automatic formatting (we do it for [owid-grapher](https://github.com/owid/owid-grapher))
2. Run unit tests even if formatting check fails

### Notifications

Would it help to receive notifications about successful/failed builds? It could be private message to Slack or shared channel. It tends to spam a lot and might break your focus.

### Failing ETL deploy after indicator renames

If you change `short_name` of indicators that are used in charts, ETL deploy will fail with an error like this
```
ValueError: Variables used in charts will not be deleted automatically:
--
  | chartId  variableId
  | 0     2895      814467
  | 1     2895      814468
  | 2     2895      814469
  | 3     2895      814470
  | 4     2895      814471
```
Then you have to find the right person, ask them to remap those variables manually and retry ETL deploy. It would be nice if we could get this error at CI time and not at deploy time.

**Comment by pabloarosado** [comment]
I'm not sure if `make format` requires internet, but `make test` does. One clear example is when there has been some poetry changes, and now `make test` will run `poetry install` under the hood. Maybe it would be good to have an `--offline` option. In a similar fashion, it would be good to have an `etl --offline` option (nice to have).
