### ISSUE TITLE
workflow: drafting charts

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#1749]
## One-liner
In order to create a new chart, a researcher might have to draft it multiple times (once on staging, another one on live).

## Summary
It is often the case that researchers want to create a new chart that relies on data that does not exist in our database / ETL.

The workflow for that is usually something like:

1. `Researcher` identifies which new indicators/datasets are needed.
2. `Data manager` ingests the required dataset to ETL, and pushes to their staging server.
3. `Researcher` starts drafting a chart on the staging server.
4. `Researcher` and `Data manager` improve the indicator's metadata (as many iterations as needed)
    - `Researcher` provides feedback to the _Data manager_ so that they can improve the presentation of the indicator (changes to its metadata).
    - `Data manager` improves the metadata and updates the dataset on staging.
5. `Data manager` drafts a Pull Request on this repository with the ETL recipe so the dataset can be ingested to live.
6. Once the PR is reviewed, approved and merged, the `Researcher` needs to create the chart again.

**Why is this helpful workflow?**
- Because the data manager can be agile in modifying the presentation of the dataset or the indicator and share these changes with the researcher (step 4).
- Because a peer still reviews the final code to ensure best practices, learn from each other and all the advantages from Perr Reviewing (Step 5).

**Where is the problem?**
The problem is that the researcher needs to draft the same chart twice (steps 3 and 6).

## Solution
There are different ways we could go from here:

1. A possible solution could be to do step 4 after 5. So that the chart is always drafted in the same place, in live. In step 4, however, we need to be fast, and agile since that's when the researcher and the data manager have several discussions, decide on things, even remove indicators, etc. And I don't think this is something that should be done on live. Plus waiting for PR approval will make this process very slow.
2. Another solution, would be to have an easy way to migrate a draft chart on a staging server to live. Unsure how the alignment between variable/dataset IDs would work between live and staging here.

or others (up for discussion)

**Comment by Marigold** [comment]
@lucasrodes would it be possible to leverage `etl-wizard charts` for this? If the "Old dataset" is from the staging server and the "New dataset" is from live, we might be able to add suggested chart revisions in a very similar way to how we do it within one server. We'd have to modify the code to work with "source" and "target" environment explicitly, but perhaps that wouldn't be as hard. If this is doable then in my mind it'd make sense to prioritise it (being low effort & high value).

**Comment by lucasrodes** [comment]
@Marigold thanks for the suggestion!

Were you thinking about the charts section?

I agree we could have something in there, but I am not sure it would be straightforward:

1. **dataset mapping**: first, the user chooses live and staging dataset names
2. **indicator mapping**: live <-> staging variable IDs mapping is done (either automatically or manually)
3. **get all affected charts**: we get all charts in staging using an indicator from the dataset.
4. **update the charts**: we update the charts, say, with the live variable IDs?
5. **push these charts to live**: I am wondering how these should be pushed, as this is no longer a suggestion. I wouldn’t insert it directly in the charts table
6. 

All steps are doable, but step 4 is tricky. We could literally copy the chart config and just change the ID of the variable(s). Still, I fear that, in some instances, that would be hardcoding some fields (opposite of sourcing some fields from indicator metadata)?

**Comment by Marigold** [comment]
5. Why can't it be a suggestion? Is it for technical reasons?
4. If we solved this with chart suggestions, wouldn't the current logic do it for us?

**Comment by lucasrodes** [comment]
> Why can't it be a suggestion? Is it for technical reasons?

What would you show as 'current chart' and 'suggested chart'? 

> If we solved this with chart suggestions, wouldn't the current logic do it for us?

By 'this', are you referring to what I mentioned in my last paragraph? "All steps are doable, but step 4 is tricky. We could literally copy the chart config and just change the ID of the variable(s). Still, I fear that, in some instances, that would be hardcoding some fields (opposite of sourcing some fields from indicator metadata)?"

**Comment by Marigold** [comment]
> What would you show as 'current chart' and 'suggested chart'?

You're right that we'd have to make some changes to chart revisions in owid-grapher to accept null values in `chart_revisions.chartId` and show an empty chart. Having visual tool like chart revision suggester for migrating charts would be nice, in my opinion.

I don't understand your second paragraph. I'm new to chart revisions, so there's likely something I'm missing.

**Comment by Marigold** [comment]
We've recently added a tool for migrating charts from staging. Here are some [diagrams for the new workflow](https://docs.owid.io/projects/etl/architecture/workflow/staging-servers/#data-manager-workflow). @lucasrodes is that enough to close this issue?
