### ISSUE TITLE
wizard: Running a snapshot silently fails

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1753]
### One-liner
Wizard Snapshot fails to execute a snapshot but on the browser it says "Snapshot uploaded!".

### Context & details
Creating the snapshot .py and .dvc files goes well, but when clicking on the button to execute the snapshot, on the browser I see "Snapshot uploaded!", however the snapshot was not properly executed. When I look at the terminal, it shows an error (for an example error, see this other issue: https://github.com/owid/etl/issues/1752).

**Comment by lucasrodes** [comment]
hi @larsyencken,
In https://github.com/owid/etl/pull/1755 I improved the message after running the snapshot step.

However, the error is not caught from the web app at the moment, and the user still needs to check the terminal (that's what the updated message says). 

I can look into improving this.

**Comment by lucasrodes** [comment]
Improvement shipped in

- https://github.com/owid/etl/pull/1809

**Comment by lucasrodes** [comment]
Should be fixed now
