### ISSUE TITLE
BadZipFile during the installation

### ISSUE THREAD

**Issue by lucas-watteuw** [owid/etl#176]
I have a BadZipFileError when I tried to install etl.

In a shell I use the command:
- git clone https://github.com/owid/etl.git
- cd etl
- make test
- make test
(I really do 2 make test)
- make etl

I put 3 screenshot in hope that will help you resolve my problem.

Thank you in advance.

![photo1](https://user-images.githubusercontent.com/81231194/166823498-f1a90491-ec4d-44e9-b8be-9aaea937125a.png)

![photo2](https://user-images.githubusercontent.com/81231194/166823503-42b6df79-ffe8-4e31-9667-816ef663ee8c.png)
![photo3](https://user-images.githubusercontent.com/81231194/166823511-4dc07551-5354-4fe8-8607-bc1dfa056303.png)

**Comment by Marigold** [comment]
The failing step `data://meadow/hyde/2017/baseline` depends on raw data `walden://hyde/2017/baseline` that is [stored here](https://walden.nyc3.digitaloceanspaces.com/hyde/2017/baseline.zip). The file has 5GB so it's possible the downloading has been interrupted and the file cannot be opened (hence `BadZipFile`). The file should have been downloaded to `~/.owid/walden/hyde/2017/baseline.zip`. Could you check whether the file has indeed 5GB?

If yes, can you run `md5sum ~/.owid/walden/hyde/2017/baseline.zip` and check if it equals `acdbbd3908a29fb8ae75f3e081c980ad`?

In case the file isn't complete, you should remove it and run `./venv/bin/etl data://meadow/hyde/2017/baseline` which will run only the step and its dependencies.

**Comment by lucas-watteuw** [comment]
The file baseline.zip had 397.5MB instead of 5GB.
So I delete it and do` .venv/bin/etl data://meadow/hyde/2017/baseline`
But now another error has appeared. I have a CancelledError and a DeadKernelError.

![photo4](https://user-images.githubusercontent.com/81231194/166995396-82deff52-6942-4d15-b741-c35b38d9b0b8.png)
![photo5](https://user-images.githubusercontent.com/81231194/166997831-fc408336-9a77-4b4b-a404-2f4714004c9e.png)

If I do `md5sum ~/.owid/walden/hyde/2017/baseline.zip`, this is what I see.

![photo6](https://user-images.githubusercontent.com/81231194/166998000-64dbe925-5b4d-443c-b335-dd8698f85571.png)

The `make test` continue to have 12 passed and 3 warnings.

Now if I do `make etl`, I have a CancelledError and a DeadKernelError.
![photo7](https://user-images.githubusercontent.com/81231194/167000783-a627cafe-6970-418d-be72-7385586a4a92.png)
![photo8](https://user-images.githubusercontent.com/81231194/167000817-988ff06d-2c67-401a-83ec-71fcd89ad51b.png)

**Comment by lucas-watteuw** [comment]
My machine is a 4gb memory machine. So I change the dag.yml file.
In this file, it rest:

```
steps:
  

  # Examples
  data://examples/script/script_example:
    - walden://wb/2021-07-01/wb_income
    - data://garden/owid/latest/key_indicators
    - data://garden/reference
  data://examples/jupytext/jupytext_example:
  data://examples/vs_code_cells/vs_code_cells_example:
  # private steps that require S3 access keys for private walden
  data-private://examples/private/2022-03-08/private_example:
    # NOTE: this dataset is public as we don't have any private data yet
    - walden-private://faostat/2022-02-10/faostat_metadata
    - data://garden/reference
```

So now I have no problem with make etl. I'm just processing less data.

**Comment by Marigold** [comment]
> So now I have no problem with make etl. I'm just processing less data.

Great, I'm glad you were able to figure it out! We plan to create exactly what you did - smaller DAG file that could be run without needing excessive memory or cpu.

**Comment by lucas-watteuw** [comment]
If you do not want to modify the DAG file, this is what you coud do:

```
    - git clone https://github.com/owid/etl.git
    - cd etl
    - make test
    - make test
    - poetry run etl examples
```
Because this issue was to resolve BadZipFileError and there is no more BadZipFileError, I will close this issue.
