### ISSUE TITLE
docs: Can the table of contents be made wider?

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#1762]
### One-liner
Just a small quality of life improvement suggestion - would it be possible to make the ToC wider, particularly on [this page](https://docs.owid.io/projects/etl/architecture/metadata/reference/tables/).

### Context & details
I currently find it quite tricky to see what all the excellent new metadata components are called and this would be super helpful for me. Hopefully it is something that can be changed easily, if it's difficult don't worry!

**Comment by lucasrodes** [comment]
Good point, @spoonerf! I thought of this the other day. There should be an easy fix.

Thanks for reporting!
