### ISSUE TITLE
Variable's short_name cannot repeat across tables in a single dataset

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1764]
## Problem

MySQL doesn't know about tables, so every variable must be uniquely named in the whole dataset. If you use the same variable name in multiple tables it silently overwrites one of the variables.

## Background

If you currently use multiple tables with the same variable name
```
tables:
  table_a:
    variables:
      var1: ...

  table_b
    variables:
      var1: ...
```
you'll only end up with one of them in MySQL. The reason is that in `variables` table we only have `datasetId` and `shortName` columns and a unique index on them, but no `tableName`.

## Technical notes

- Even though we don't have a notion of `Table` in MySQL, it would be useful to have `tableName` there to have parity with ETL. We could also potentially use `catalogPath` which already contains the table name.
- An alternative would be to forbid reuse of short_name across tables and raise an error, but I'm not fan of such solution.

## Workaround

In the short term, we can work around this by changing short names.

**Comment by larsyencken** [comment]
The extra background is that we'd love a better map of the ETL in MySQL.

The best fix would seem to be to add `tableName` as you suggest Mojmir, pull it from the `catalogPath`, and then change the uniqueness constraint and upsert query to be on that instead.
