### ISSUE TITLE
Create app etl-archive-steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1820]
## Motivation

We are accumulating new versions of datasets, and may want to make it easy to archive old ones to keep the DAG clean.

## Proposal

Create a script/web UI that makes it easy to archive a series of steps, and double-checks that they're not used.

UPDATE: either it should be part of the step updater automatically, or it should be a one-click option from that UI

## Technical notes

- This would be similar to the current `scripts/move_steps_to_archive.py`, but it would also attempt to move steps from the active to the archive dag (and fail if `version_tracker` complains).
- This could be implemented as part of `StepUpdater`

**Comment by pabloarosado** [comment]
Also, I've noticed that the current `scripts/move_steps_to_archive.py` doesn't move all files to the archive. For example, I see that any `shared.py` files are left behind. I suppose this make sense for safety, in case there were other steps in the same folder that shouldn't be archived.
But we could check if there are other steps in the same folder (which is in most cases not the case), and if not, archive everything.

**Comment by larsyencken** [comment]
We note that we will want to make it easy to archive things, but we don't necessarily want to archive every step immediately after update; keeping old versions around in the active DAG is helpful for QA. We may still want helpers for archiving steps that aren't working any more.

**Comment by larsyencken** [comment]
Based on this, suggesting we wait until archiving is more painful to automate it more.

**Comment by Marigold** [comment]
I'd have found this really useful when migrating to pandas 2. There are like three faostat versions we keep in DAG, which means three times more refactoring. Archiving old versions would also make the ETL faster (especially for faostat steps). Ideally, we'd have "Archive" button in the dashboard that would move the steps automatically and warn about any leftover dependencies. (We could also have "Unarchive" just in case, but that might not be as useful in the end)
