### ISSUE TITLE
Make it possible to add external DAG files `dag.yml`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#186]
Our `dag.yml` currently looks something like this

```
steps:
  data://garden/owid/latest/covid:
    - etag://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
  ...
  data://open_numbers/open_numbers/latest/bp__energy:
    - github://open-numbers/ddf--bp--energy
  ... way too many open_numbers steps that make this hard to read...
```
an idea is to move all `open_numbers` steps into their own `dag_open_numbers.yml` and reference them from the main `dag.yml` file using `include:` stanza, i.e.

```
steps:
  data://garden/owid/latest/covid:
    - etag://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
  ...

include:
  - dag_open_numbers.yml
```

with `dag_open_numbers.yml` looking like this

```
steps:
  data://open_numbers/open_numbers/latest/bp__energy:
    - github://open-numbers/ddf--bp--energy
  ...
```

**Comment by wcox13** [comment]
Thanks @Marigold - just to make sure I'm understanding, the idea here is to modify the `load_dag` function of `etl/steps/__init__.py`, so that we also load into the dag/dict any sub-files listed with the `include` header?

**Comment by wcox13** [comment]
Also is it fine to support one level of `include` for now or should it be like a BFS (support `include` within the included files as well)?

**Comment by wcox13** [comment]
Opened https://github.com/owid/etl/pull/190 @Marigold

**Comment by Marigold** [comment]
Sorry for late reply, but you got it right.

> Also is it fine to support one level of include for now or should it be like a BFS (support include within the included files as well)?

I don't think we'd use it, but supporting it should be easy (more in your PR).

**Comment by pabloarosado** [comment]
Thanks @Marigold I like it very much! I see that dependences work well even if they are defined inside a sub-dag, so that's perfect.
Just one suggestion: Wouldn't it be better to keep sub-dags inside a folder? Otherwise, the root of the etl will become crowded with dag_*.yml files.

**Comment by pabloarosado** [comment]
Hey @Marigold, I just tested that having a 'dag_files' folder with the sub-dags, and then in the include section cite 'dag_files/dag_faostat.yml' works well. At least I did a `etl --dry-run faostat` and it found all the steps well.

**Comment by Marigold** [comment]
Good idea, `dag_files` folder is definitely better. Please move open numbers there too.

**Comment by pabloarosado** [comment]
OK, I'll make another PR for this.
