### ISSUE TITLE
Add at least one dataset level tag to all datasets that have new metadata

### ISSUE THREAD

**Issue by danyx23** [owid/etl#1868]
For the new datapages it would be extremely useful if we could guarantee that every indicator has at least one `topic_tag` assigned. This will ensure that we can link our topic pages with our data pages and help in showing the most relevant content in various places.

The easiest way to ensure this is to set one (or more) tag at the dataset level. This is not always appropriate but works in many cases. Tags have to match a [topic tag in the database](http://datasette-private/owid?sql=select+name%2C+isTopic+from+tags+where+%22isTopic%22+%3D+%3Ap0+order+by+id+desc+limit+101&p0=1) (case sensitive). The schema has been updated to include the current topic tags so you should get autocomplete in the yaml file for this field. The only non-topic that that can be used in "Uncategorized" which can be used for cases where you explicitly don't want to assign a topic (e.g. useful in cases like the WDI where every indicator needs a human or AI assigned tag and you don't have the time to do it yet).

The easiest way to assign a tag to all indicators in a dataset is to set it via the common section in the yaml file:
```yaml
definitions:
  common:
    presentation:
      topic_tags:
      - Poverty
```

As of today we have about 100 datasets that have at least one indicator with new metadata. The list below has a checkmark to indicate if a tag has been added. Then it states the number of indicator the dataset has, the dataset name and the name is linked to the probable location of the metadata yaml file that you need to edit with the above snippet.

### From Lucas
(working on #1869)
- [x] [2 - Population density (various sources, 2023.2)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-06-12/population_density.meta.yml)
- [x] [7 - Population (various sources, 2023.1)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-03-31/population.meta.yml)
- [x] [682 - Human Mortality Database](https://github.com/owid/etl/tree/master/etl/steps/data/garden/hmd/2023-09-19/hmd.meta.yml)
- [x] [168 - Life tables](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-10-04/life_tables.meta.yml)
- [x] [54 - Life Expectancy (period)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-10-10/life_expectancy.meta.yml)
- [x] [3 - Life expectancy at birth](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-10-11/life_expectancy_birth.meta.yml)
- [x] [6 - Life Expectancy: Broken limits](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-10-20/broken_limits_le.meta.yml)
- [x] [33 - Survivorship percentiles (HMD, Alvarez and Vaupel; 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-09-27/survivor_percentiles.meta.yml)
- [x] [1 - Outsurvival statistic](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-10-03/phi_gender_le.meta.yml)
- [x] [2 - Gini coefficient of lifespan inequality (HMD, UN WPP, Aburto et al.; 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-10-04/gini_le.meta.yml)
- [x] [37 - History of war (UCDP, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-06-26/ucdp.meta.yml)
- [x] [21 - History of war (COW, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-07-26/cow.meta.yml)
- [x] [26 - History of war (COW MID, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-08-08/cow_mid.meta.yml)
- [x] [12 - History of war (Gibler and Miller, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-08-15/mie.meta.yml)
- [x] [12 - History of war (Project Mars, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-07-14/mars.meta.yml)
- [x] [30 - History of war (PRIO v3.1, 2017)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-07-21/prio_v31.meta.yml)
- [x] [9 - History of war (Brecke, 1999)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-07-20/brecke.meta.yml)
- [x] [102 - History of war (UCDP, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/ucdp.meta.yml)
- [x] [27 - History of war (UCDP/PRIO, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-10-24/ucdp_prio.meta.yml)
- [x] [56 - History of war (COW, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/cow.meta.yml)
- [x] [78 - History of war (COW MID, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/cow_mid.meta.yml)
- [x] [34 - History of war (Gibler and Miller, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/mie.meta.yml)
- [x] [30 - History of war (Project Mars, 2020)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/mars.meta.yml)
- [x] [72 - History of war (PRIO v3.1, 2017)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/prio_v31.meta.yml)
- [x] [24 - History of war (Brecke, 1999)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-21/brecke.meta.yml)
- [x] [6 - Peace data (Diehl et al., 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/war/2023-09-27/peace_diehl.meta.yml)
- [x] [2 - States in regions (Gleditsch)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/countries/2023-10-01/gleditsch.meta.yml)
- [x] [2 - States in regions (COW)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/countries/2023-09-29/cow_ssm.meta.yml)
- [x] [2 - States in regions (ISD)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/countries/2023-10-01/isd.meta.yml)
- [x] [7 - Global AIDS Update (UNAIDS, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/health/2023-08-09/unaids.meta.yml)
- [x] [4 - International Completeness of Death Registration 2015-2019 (Karlinsky, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/health/2023-08-16/deaths_karlinsky.meta.yml)
- [x] [34 - Comtrade Database](https://github.com/owid/etl/tree/master/etl/steps/data/garden/un/2023-10-09/plastic_waste.meta.yml)
- [x] [1 - Population doubling times (various sources, 2023.1)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/demography/2023-07-03/population_doubling_times.meta.yml)

### From Veronika
(https://github.com/owid/etl/pull/1872)
 - [x] [1 - Global Plastics Outlook - Plastics use by region - projections](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_use_projections.meta.yml)
 - [x] [13 - Global Plastics Outlook - Plastics waste by region and end-of-life fate - projections](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_fate_regions_projections.meta.yml)
 - [x] [15 - Global Plastics Outlook - Plastics use by polymer](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_use_polymer.meta.yml)
 - [x] [16 - Global Plastics Outlook - Plastics use by application](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_use_application.meta.yml)
- [x] [20 - Global Plastics Outlook - Plastics waste in 2019 by region and application](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_waste_2019.meta.yml)
- [x] [20 - Global Plastics Outlook - Plastics waste in 2019 by region and polymer](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_waste_2019_by_polymer.meta.yml)
 - [x] [4 - Global Plastics Outlook - Greenhouse gas emissions from primary plastics](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_emissions.meta.yml)
 - [x] [4 - Global Plastics Outlook - Plastic leakage to aquatic environments - projections](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_aquatic_leakage_projections.meta.yml)
 - [x] [18 - Global Plastics Outlook - Plastics waste by region and end-of-life fate](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_fate_regions.meta.yml)
 - [x] [8 - Global Plastics Outlook - Plastic leakage to aquatic environments](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_aquatic_leakage.meta.yml)
 - [x] [3 - Global Plastics Outlook - Plastic leakage to the environment - projections](https://github.com/owid/etl/tree/master/etl/steps/data/garden/oecd/2023-09-21/plastic_environment_leakage_projections.meta.yml)
- [x] [2 - Production, use, and fate of all plastics ever made (Geyer et al.)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/plastic_waste/2023-09-26/geyer_2017.meta.yml)
 - [x] [2 - Global Corporate Investment in AI by Investment Activity, 2013ΓÇô22 (AI Index, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/artificial_intelligence/2023-06-14/ai_corporate_investment.meta.yml)
 - [x] [2 - Use of statins for the prevention of cardiovascular disease in 41 low-income and middle-income countries.](https://github.com/owid/etl/tree/master/etl/steps/data/garden/statins/2023-10-05/lancet_2022.meta.yml)
 - [x] [120 - Human Capital in the Long Run (Lee and Lee, 2016)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/education/2023-07-17/education_lee_lee.meta.yml)
 - [x] [2 - Global, regional and national trends in statin utilisation in high-income and low/middle-income countries, 2015-2020.](https://github.com/owid/etl/tree/master/etl/steps/data/garden/statins/2023-10-05/bmj_2022.meta.yml)
- [x] [4 - Private Investment in AI by Focus Area (AI Index, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/artificial_intelligence/2023-06-14/ai_private_investment.meta.yml)
- [x] [330 - Average hours of work, by education level and economic activity (ILOSTAT)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ilostat/2023-09-19/average_work_hours.meta.yml)
- [x] [96 - Employment rates, by age and education level (ILOSTAT)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ilostat/2023-09-19/employment.meta.yml)
- [x] [96 - Unemployment rates, by age and education level (ILOSTAT)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ilostat/2023-09-19/unemployment.meta.yml)
 - [x] [68 - ESC Cardiovascular Statistics](https://github.com/owid/etl/tree/master/etl/steps/data/garden/cardiovascular_diseases/2023-10-10/esc.meta.yml)
 - [x] [4 - Global atlas of medical devices](https://github.com/owid/etl/tree/master/etl/steps/data/garden/who/2023-10-13/medical_devices_atlas.meta.yml)

### From Fiona
(https://github.com/owid/etl/pull/1872)
 - [x] [2 - Historical Series of Phenological data for Cherry Tree Flowering at Kyoto City (and March Mean Temperature Reconstructions)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/biodiversity/2023-01-11/cherry_blossom.meta.yml)
- [x] [3 - Babies per woman (total fertility rate)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/gapminder/2023-09-22/total_fertility_rate.meta.yml)
- [x] [4 - Long-run child mortality (Gapminder; UN IGME)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/un/2023-09-19/long_run_child_mortality.meta.yml)
- [x] [10 - Leading causes of death in all ages and under-fives (IHME - GBD, 2019)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ihme_gbd/2023-10-04/leading_causes_child_deaths.meta.yml)

### From Pablo R
- [x] [429 - Natural disasters](https://github.com/owid/etl/tree/master/etl/steps/data/garden/emdat/2023-09-20/natural_disasters.meta.yml)
- [x] [90 - Global Carbon Budget (Global Carbon Project, 2023b)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/gcp/2023-07-10/global_carbon_budget.meta.yml)
- [x] [87 - Global Carbon Budget](https://github.com/owid/etl/tree/master/etl/steps/data/garden/gcp/2023-09-28/global_carbon_budget.meta.yml)
- [x] [21 - Energy mix (Energy Institute, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/energy/2023-07-10/energy_mix.meta.yml)
- [x] [18 - Emissions-weighted Carbon Price](https://github.com/owid/etl/tree/master/etl/steps/data/garden/rff/2023-10-19/emissions_weighted_carbon_price.meta.yml)
- [x] [18 - Global natural disasters by type](https://github.com/owid/etl/tree/master/etl/steps/data/garden/emdat/2023-09-20/natural_disasters_global_by_type.meta.yml)
- [x] [15 - Electricity mix (EI & Ember, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/energy/2023-07-10/electricity_mix.meta.yml)
- [x] [10 - Global hen inventory (Welfare Footprint Project, 2022)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-01/global_hen_inventory.meta.yml)
- [x] [9 - Number of farmed fish killed for food worldwide](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-08/farmed_finfishes_used_for_food.meta.yml)
- [x] [7 - Dummy monster](https://github.com/owid/etl/tree/master/etl/steps/data/garden/dummy/2023-10-12/dummy_monster.meta.yml)
- [x] [6 - Number of individual wild fish killed for food](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-16/number_of_wild_fish_killed_for_food.meta.yml)
- [x] [6 - Number of farmed decapod crustaceans killed for food (Fishcount, 2018)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-15/number_of_farmed_decapod_crustaceans.meta.yml)
- [x] [6 - Number of farmed fish killed for food (Fishcount, 2018)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-14/number_of_farmed_fish.meta.yml)
- [x] [5 - UK egg statistics (Defra, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-01/uk_egg_statistics.meta.yml)
- [x] [4 - Fur banning](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-10-24/fur_laws.meta.yml)
- [x] [4 - Fur banning](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-09-08/fur_laws.meta.yml)
- [x] [3 - Near-surface temperature anomaly](https://github.com/owid/etl/tree/master/etl/steps/data/garden/met_office_hadley_centre/2023-10-18/near_surface_temperature.meta.yml)
- [x] [3 - Fossil fuel production (EI & Shift, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/energy/2023-07-10/fossil_fuel_production.meta.yml)
- [x] [2 - World Carbon Pricing Database](https://github.com/owid/etl/tree/master/etl/steps/data/garden/rff/2023-10-19/world_carbon_pricing.meta.yml)
- [x] [2 - Net Zero Tracker](https://github.com/owid/etl/tree/master/etl/steps/data/garden/emissions/2023-10-10/net_zero_tracker.meta.yml)
- [x] [2 - Share of cage-free eggs (Various sources, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-08-03/share_of_cage_free_eggs.meta.yml)
- [x] [2 - Primary energy consumption (EI & EIA, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/energy/2023-07-10/primary_energy_consumption.meta.yml)
- [x] [1 - Emission Factor Database](https://github.com/owid/etl/tree/master/etl/steps/data/garden/emissions/2023-10-24/emission_factors.meta.yml)
- [x] [1 - Bullfighting laws](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-09-05/bullfighting_laws.meta.yml)
- [x] [1 - Chick culling laws](https://github.com/owid/etl/tree/master/etl/steps/data/garden/animal_welfare/2023-09-01/chick_culling_laws.meta.yml)
- [x] [1 - Dummy OWID dataset title](https://github.com/owid/etl/tree/master/etl/steps/data/garden/dummy/2020-01-01/dummy.meta.yml)

### From Mojmir
- [x] [3 - Living Planet Index ΓÇô WWF (2022)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/biodiversity/2022/living_planet_index.meta.yml)
- [x] [448 - World Inequality Database (WID, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/wid/2023-08-24/world_inequality_database.meta.yml)
- [x] [89 - World Bank Poverty and Inequality Platform (PIP)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/wb/2022-10-03/world_bank_pip.meta.yml)

### From Pablo A
- [x] [21 - State Capacity Dataset](https://github.com/owid/etl/tree/master/etl/steps/data/garden/state_capacity/2023-10-19/state_capacity_dataset.meta.yml)
- [x] [3 - Maddison Project Database](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ggdc/2020-10-01/ggdc_maddison.meta.yml)
- [x] [355 - Democracy and Human rights - OWID based on Varieties of Democracy (v13) and Regimes of the World](https://github.com/owid/etl/tree/master/etl/steps/data/garden/democracy/2023-03-02/vdem.meta.yml)
- [x] [7 - Colonial Dates Dataset (COLDAT)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.meta.yml)
- [x] [9 - Augmented Human Development Index (AHDI)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/ahdi/2023-09-08/augmented_hdi.meta.yml)

### Others
- [x] [1 - [origin.title]](https://github.com/owid/etl/tree/master/etl/steps/data/garden/dummy/2020-01-01/dummy_full.meta.yml)
- [x] [1 - Reported Smallpox Cases (WHO, 2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/fasttrack/latest/smallpox_cases.meta.yml)
- [x] [1 - World Development Indicators - World Bank (2023.05.11)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/worldbank_wdi/2023-05-29/wdi.meta.yml)
- [x] [1 - United Nations Inter-agency Group for Child Mortality Estimation (2023)](https://github.com/owid/etl/tree/master/etl/steps/data/garden/un/2023-08-16/igme.meta.yml)

<details>
<summary>Datasette query for the above list</summary>
The following datasette query was used to arrive at the above list:

```sql
with datasets_with_counts as (
  select
    d.name as name,
    count(*) as variableCount,
    json_group_array(distinct v.catalogPath) as paths
  from
    datasets d
    join variables v on v.datasetId = d.id
  where
    v.schemaVersion = 2
  group by
    d.id
  order by
    count(*) desc
)
SELECT
  name,
  variableCount,
  json_each.value AS path
FROM
  datasets_with_counts t,
  json_each(t.paths)
```
</details>

**Comment by lucasrodes** [comment]
I've restructured the list, making it easier to work on my datasets. I'd suggest you do the same, @pabloarosado. With the ones remaining, we can either distribute them among us both or let others know. Can decide once we're finished with ours.

**Comment by pabloarosado** [comment]
I've added tags to all datasets I've worked on: https://github.com/owid/etl/pull/1870
I've realised some of the datasets listed above are still using old metadata (e.g. [Energy mix](https://github.com/owid/etl/blob/master/etl/steps/data/garden/energy/2023-07-10/energy_mix.meta.yml)). I haven't added topic tags to those.

We can just distribute of the list half and half among us, and then add the others as reviewers.

**Comment by pabloarosado** [comment]
I see that [grapher steps are failing](https://buildkite.com/our-world-in-data/etl-automated-staging-environment/builds/248#018b707b-a959-4b5d-b553-e6404ef4bafb) (also in my local grapher). It's related to `grapher_model`, something connected to the `displayOrder` of the topic tags. Maybe some migration needs to be done in the database. @danyx23 were you expecting this or is it a bug?

**Comment by lucasrodes** [comment]
@pabloarosado when are you getting this error?

I was getting this error when using Jinja on `topic_tags` ([see my comment](https://owid.slack.com/archives/C0193RW5E2J/p1698401091226079)).

Could be related to this update https://github.com/owid/etl/pull/1863? @Marigold

**Comment by Marigold** [comment]
@pabloarosado sorry, my bad! Could you please rebase on top of the master?

**Comment by lucasrodes** [comment]
@pabloarosado I've re-structured the list again to clarify which datasets each of us is tackling.

I've finished my part, you can review my changes here:
- https://github.com/owid/etl/pull/1869

I've created an additional PR with the changes affecting datasets from others (no need to review this):
- https://github.com/owid/etl/pull/1872

**Comment by pabloarosado** [comment]
It's not clear to me what to do with auxiliary indicators, like population or GDP, that we have sometimes within a dataset. For example, natural disasters has those indicators. These indicators only exist because it's convenient (for us and for superuser downloading the dataset) to have population and GDP next to the per capita and per gdp variables. They're useful to do sanity checks.
* We don't want to tag them as `Population` or `Economic Growth`, because they shouldn't appear anywhere on those topics.
* We don't want to tag them as `Natural Disasters`, since we don't want them to appear on those searches.

So, I'll tag them as "Uncategorized". Do you agree @lucasrodes ?

**Comment by lucasrodes** [comment]
Yeah, that sounds reasonable, @pabloarosado!

**Comment by pabloarosado** [comment]
I've checked most of the datasets in the list, since they were using the old metadata (including WDI). I understand that they don't need to be tagged.

@pabloarosado among the tags in [this list](http://datasette-private/owid?sql=select+name%2C+isTopic+from+tags+where+%22isTopic%22+%3D+%3Ap0+order+by+id+desc+limit+101&p0=1), which ones would you assign (being the first tag the most important one) to the indicators of:
* [State Capacity Dataset](https://github.com/owid/etl/blob/master/etl/steps/data/garden/state_capacity/2023-10-19/state_capacity_dataset.meta.yml).
* [Colonial Dates Dataset](https://github.com/owid/etl/blob/master/etl/steps/data/garden/harvard/2023-09-18/colonial_dates_dataset.meta.yml).
* [Augmented Human Development Index](https://github.com/owid/etl/blob/master/etl/steps/data/garden/ahdi/2023-09-08/augmented_hdi.meta.yml).

@spoonerf among the tags in [this list](http://datasette-private/owid?sql=select+name%2C+isTopic+from+tags+where+%22isTopic%22+%3D+%3Ap0+order+by+id+desc+limit+101&p0=1), which ones would you assign (being the first tag the most important one) to the indicators of:
* [United Nations Inter-agency Group for Child Mortality Estimation](https://github.com/owid/etl/blob/master/etl/steps/data/garden/un/2023-08-16/igme.meta.yml).

Thanks both!

**Comment by spoonerf** [comment]
Hey @pabloarosado!

I would go with `Child & Infant Mortality` for the [United Nations Inter-agency Group for Child Mortality Estimation](https://github.com/owid/etl/blob/master/etl/steps/data/garden/un/2023-08-16/igme.meta.yml) dataset. 

Just be aware that the Datasette link you shared is showing only the first 101 topic tags ordered by id, but there are 128. Maybe [this link](http://datasette-private/owid?sql=select+name%2C+isTopic+from+tags+where+%22isTopic%22+%3D+%3Ap0+order+by+name&p0=1) is better.

**Comment by lucasrodes** [comment]
@pabloarosado I'd use 'State Capacity' for 'State Capacity Dataset' and 'Colonial Dates Dataset'. And possible 'Human Development Index (AHDI)' for the 'Augmented Human Development Index'

**Comment by paarriagadap** [comment]
Hi! I was away last Friday. Yes, the ones described by @lucasrodes are the ones to use. It's `Human Development Index (HDI)`, by the way.

**Comment by pabloarosado** [comment]
Hey @lucasrodes I think the two PRs are ready to be merged (assuming that there are no other new CI surprises with random steps). If everything goes well, shall we merge by the end of the day?

**Comment by pabloarosado** [comment]
This issue was completed late October, but I suppose we forgot to close it.
