### ISSUE TITLE
Concept: uniquely address a catalog table and subcontents

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#187]
## Problem

We want to create an API. The API won't use integer primary keys to fetch variable data, instead it will need a different addressing scheme that lets us identify which catalog table the data is in.

We want the API to be able to fetch just part of the data in a data frame in our catalog. This means it also needs a syntax to address only some columns or index ranges of the data.

## Possible ideas

Needs discussion.

### ETL paths

Use ETL paths based on `short_names` with some kind of suffix. But the paths will be really long.

### UUIDs

Use UUIDs that represent a table or a column. But the ETL regenerates data on every run, we would need a "deterministic UUID" scheme so that two people on different computers generate the same UUID for the same data 😱 

### ETL index hashes

Use ETL paths, but (automatically or on disk) keep a list of hashes to those paths. The hashes can be used instead of the path itself.

**Comment by larsyencken** [comment]
Just as a note, "Concept" cards are not meant to be fleshed out solutions. We should try to turn them into proposals which we can then agree on or discuss more.

**Comment by Marigold** [comment]
This is still a thing as far as I know.

**Comment by larsyencken** [comment]
This got solved and shipped, e.g. `grapher/bp/2022-07-14/statistical_review/statistical_review#oil__proved_reserves`
