### ISSUE TITLE
metadata: display and presentation fields need to be automatically propagated on operations

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#1876]
## Context

- We currently propagate and merge some/many metadata fields when you do common operations between `Table` columns
- Since then, we have added more fields, and these do not get automatically propagated yet

## One-liner

Fields like `title_public`, or `topic_tags` should be automatically propagated on operations, with some reasonable logic.

## Motivation

- Wherever possible, we want to save work and make maintaining all this metadata easier
- We should try to propagate what additional fields we can

## Technical notes

- Currently, when doing an operation between two indicators, say `c = a + b`, the `presentation` field in the metadata is propagated to `c` only if `a.metadata.presentation` is identical to `b.metadata.presentation`. 
- This means that many public titles or topic tags will not be automatically propagated (even though topic tags are now mandatory). We would like to improve the logic of this propagation.
- Since `presentation` is a dictionary, it needs a different merge strategy to plain strings

**Comment by larsyencken** [comment]
Note that you need to do a rebuild after doing this, and then check the output of `datadiff`, which will be crazy big and probably not super useful.
