### ISSUE TITLE
Make walden part of ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#193]
Having [walden](https://github.com/owid/walden) as a submodule is a bit inconvenient as one has to create multiple PRs when adding datasets and it's also a bit unclear for a newcomer why we need extra repository for data processing. Both approaches have their pros and cons that need to be weighted responsibly, I'm not saying that having it in a single repository is better (nor that it will add much value). Here are some ideas we had:

1. `walden://` name is a bit confusing, `snapshot://` is more intuitive
2. both Walden and ETL have `Catalog` class is causing some confusion, renaming it or even unifying both would be cool
3. Walden data is stored in `~/.owid/walden`, but `etl` stores it in `etl/data` folder

This is not a priority by any means, dropping it here for posterity.

**Comment by danyx23** [comment]
Discussed with @larsyencken - our preference now is to:
* Generally in favour of a monorepo, i.e. moving the python codebase for walden and the index into ETL (needs a short proposal)
* `snapshot://` or `upstream://` would both be better than walden (feel free to make this change ahead of everything else)
* The data folder could just be folded into the etl folder structure

**Comment by danyx23** [comment]
This issue is now for creating the short proposal, the actual work would be a new followup issue that get's estimated separately

**Comment by Marigold** [comment]
I wrote a short [proposal in Notion](https://www.notion.so/owid-v2/2022-05-30-Proposal-make-Walden-part-of-ETL-f069961b29194efa9bc0b998694fdf4e). Even thought this is just "nice to have", the effort is probably not gonna be high and the sooner we do this the better?

**Comment by Marigold** [comment]
No stale bot, don't do it! We have a [new proposal](https://www.notion.so/owid/2022-07-13-Restructure-ETL-Walden-800793e13d314570a476cde32e7780f3) and we can't wait to have walden part of ETL! (cc @larsyencken )

**Comment by larsyencken** [comment]
> We're still using walden in ETL (I've started walden -> snapshot migration, but then started questioning myself), so we'd also have to move `walden/index` there. Do you think it's worth moving Walden to ETL now that we're trying to get rid of it? An alternative how to get rid of it as a dependency would be migrating to snapshots (which is totally doable) and only referencing walden repo from ETL.

The walden index is actually in `owid/walden/index` in `vendor/walden`, so if we did the move I suggested above it would come.

The best outcome of all would be to migrate everything to snapshots, but I think even that would be easier to do incrementally within the same repo. Then we can delete the walden code from ETL once everything is migrated.

**Comment by Marigold** [comment]
You're right it might be easier, I'll give it a try when I get a chance!

**Comment by larsyencken** [comment]
Looks like we didn't move `vendor/walden/owid/` to `owid/` and commit it to the repo. Is this actually closed?

**Comment by Marigold** [comment]
We didn't. Walden is slowly being replaced by snapshots. I tried to migrate everything from walden to snapshots at one point, but it was too much work just for the sake of having clean repository. The last walden commit is 4 months old and no one has complained about submodules since then, so I thought we don't have keep this issue around. (Feel free to reopen)

**Comment by larsyencken** [comment]
That's cool. When you close something that way, can you leave a note and tag as "wontfix", to make it clearer how we resolved it?

**Comment by larsyencken** [comment]
This was implemented here: https://github.com/owid/etl/pull/1218
