### ISSUE TITLE
Proposal: uniquely address a catalog table and subcontents

### ISSUE THREAD

**Issue by Marigold** [owid/etl#194]
## Backlinks
* https://github.com/owid/etl/issues/187
* [Data addressing scheme](https://www.notion.so/owid/Data-addressing-scheme-a64f3e5db8e34597979a3eedac0c5cba) in Notion (recommended, a lot of good stuff there!)

## Goals

Ideally the addressing scheme would be short, human and machine readable, universal, ... however, we might have to do compromises, so it's better to state what is our primary goal beforehand. Since we plan to make it work with grapher first, I think we don't have to focus on human readability or nice slugs as much as having it fit nicely into our current system. Short and readable slugs are nice to have, but if we have a browsable catalog then users are gonna just copy&paste the URL from search results anyway.

## Paradigms

We can either go the mainstream way and have a standard API or we can open our database to the world through the API and let anyone write queries against it. The second option is risky, but opens up some interesting possibilities

- SQL interface everyone is familiar with
- client-side processing with DuckDB-wasm
- other layers on top of this API

We could do both and build helper endpoints on top of the main SQL endpoint.

### ETL paths

Use paths from ETL catalog, i.e. `channel/institution/version/dataset/table`. These can get long especially with backported datasets (they are automatically underscored), the main advantages are consistency with catalog and readability. The main problem is length - [practical limit is 2048 characters](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string) (newer browsers have higher limit) which is ok for a dataset, but if we add columns selection to URL then it might become unfeasible (although we are selecting at most a few columns in practice).

Even though there are limitations, I think this is the most straightforward solution. If we hit URL length limits we can always send it as POST request with additional info in columns.

_Note: backported datasets are currently prefixed with `dataset_[dataset.id]` and the table uses the same name as the dataset most of the time, this is not great and could be definitely improved, ideas welcomed_

#### [People living in democracies](https://ourworldindata.org/grapher/people-living-in-democracies-lied?country=~OWID_WRL)
- `backport/owid/latest/dataset_5546_political_regimes__skaaning_et_al__2015/dataset_5546_political_regimes__skaaning_et_al__2015.feather`

#### [Maddison GDP dataset](https://ourworldindata.org/grapher/maddison-data-gdp-per-capita-in-2011us-single-benchmark)
- `backport/owid/latest/dataset_1924_maddison_project_database_2018__bolt_et_al__2018/dataset_1924_maddison_project_database_2018__bolt_et_al__2018.feather`

#### [Population density](https://ourworldindata.org/grapher/population-density)
- `garden/owid/latest/population_density/population_density.feather`

#### Faostat
- `garden/faostat/2022-04-26/faostat_rl/faostat_rl.feather`

### SQL

We could also expose our database directly and let users use arbitrary SQL queries (DuckDB is read-only so this should be pretty safe). The problem here becomes metadata (it would have to be queried separately).

```
SELECT country, year, population_density
FROM garden__owid__latest__population_density__population_density
```

### UUIDs

> Use UUIDs that represent a table or a column. But the ETL regenerates data on every run, we would need a "deterministic UUID" scheme so that two people on different computers generate the same UUID for the same data 😱

Ideas?

### ETL index hashes

> Use ETL paths, but (automatically or on disk) keep a list of hashes to those paths. The hashes can be used instead of the path itself.

Ideas? (This somehow touches the paragraph below)

### Variable and dataset IDs

To ease the [transition from grapher DB to API](https://www.notion.so/owid/API-for-Data-Metadata-for-Grapher-78045acf2f9c4bc9bdfc7edb8bf7911f), we should also support addressing via variable ids (or dataset ids) with special endpoint. All backported datasets hold info about their original variable ids, so constructing map table `variable id -> ETL path` in API shouldn't be a problem.

## Subcontent addressing

Some good propositions were made in the [Notion document](https://www.notion.so/owid/Data-addressing-scheme-a64f3e5db8e34597979a3eedac0c5cba). Sample query would look like

```
data://dataset/release/variable?dim1=value1&dim2=value2&dim3=value3
```

Similarly, we could also use query parameters like `columns=A,B,C&years=1950-2020&sex=female` or raw SQL.

```
garden/owid/latest/population_density/population_density.feather?columns=country,year,population_density
```

**Comment by larsyencken** [comment]
Early thought:

- We were worried about using the path to identify the variable, since we could exceed GET parameter space when fetching multiple variables
    - But, this won't be a problem for dimensional tables like in health, since all the data's on the same path

**Comment by Marigold** [comment]
Moved to [Notion](https://www.notion.so/owid-v2/2022-05-24-Proposal-uniquely-address-a-catalog-table-and-subcontents-c50ac9783e744a71b7d6888c5f8c5768)
