### ISSUE TITLE
Ask for informations about the steps and the architecture

### ISSUE THREAD

**Issue by lucas-watteuw** [owid/etl#199]
I want more informations about the steps and the architecture of the project.

I will begin with the steps.
In the dag.yml file we see:

```
data://open_numbers/open_numbers/latest/undp__hdi:
  - github://open-numbers/ddf--undp--hdi

data://meadow/gapminder/2019-12-10/population:
  - walden://gapminder/2019-12-10/population

data://garden/owid/latest/covid:
  - etag://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
```

Even if you don't put the github, etag or walden step, the file are generated so why put it?
```

grapher://ggdc/2020-10-01/ggdc_maddison:
  - data://garden/ggdc/2020-10-01/ggdc_maddison
```

The commande to generate file is .venv/bin/etl grapher://ggdc/2020-10-01/ggdc_maddison
I see the file for the data steps being generated in the data folder but I don't see the file generate by the grapher step, where is it generated?

I will continue with the architecture.

There is 2 parts in the future-architecture.png.
The first part is clean, harmonize and remix.
The second part is publish.

If I understand, the first part is the grapher step or the data step that I put in the yml file.
THe second part is the one that I don't understand.

```
poetry run etl --private
poetry run reindex
poetry run publish --private
```

This one end with botocore.exceptions.NoCredentialsError: Unable to locate credentials
`
poetry run publish`

This one end with Exception: You cannot publish public catalog yet, only private catalogs with flag --private are supported

Do I need to put my data on walden before being able to publish?

**Comment by Marigold** [comment]
Hey Lucas! Yeah, this can be confusing, let me clarify it. We have an internal private database powering charts in ourworldindata.org and it is called "grapher" or "grapher DB". Those steps prefixed with `grapher://` are only meant to export data into grapher DB, so it's not very useful for contributors like you (it's run with `--grapher` flag and you'd need credentials to our database).

`publish` command is used to publish data into our open data catalog on S3 (= DigitalOcean spaces) which has [Pythonic API](https://github.com/owid/owid-catalog-py). `publish` command is again not meant to be used by public, but if we get a public contribution and merge it, our server will run the `publish` for you automatically.

> Do I need to put my data on walden before being able to publish?

Can I ask if you intend to use it to host your own data catalog or do you want to contribute with a dataset? (Short answer is yes, you'd have to put data to walden first, then process them with ETL and then publish)

**Comment by lucas-watteuw** [comment]
I want to host my own catalog.

**Comment by Marigold** [comment]
Oh cool! We can probably write a short guide how to host your own catalog. If your data isn't too large I'd recommend to first start without walden and instead committing the data files to git (we plan to merge walden with etl anyway, so doing this later rather than sooner might be a good idea).

You'll first need to create a bucket in S3 (we use DigitalOcean Spaces) and then save credentials in .env file to make publish work (you can even publish current OWID catalog to your bucket for a start)
