### ISSUE TITLE
Improvements of `etl-staging-sync`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2017]
## Suggested improvements

* [x] Switch server destruction from 1 day to 3 days
* [x] Improve WARNING if chart has been updated on live
  - We could at least show diff of chart configs
* [x] #2412
* [x] We could check if variables from live chart are newer than from staging
* [ ] How about redirects created on staging?
* [ ] Call it `etl-publish-charts`

## UI

One issue is that users need write access to live DB to use the CLI. The other is CLI ergonomics, it'd be much more friendly to have an UI in Admin. We could have a simple UI similar to Fast-track in Admin, which would be just an interface to the CLI.

It could be run either from the staging server if we decide to destroy them with delay or it could be run on live if we somehow snapshot the staging server.

Web app could be written in pywebio, https://github.com/Textualize/textual-web or streamlit.

## Server destruction

Right now we keep staging server around for 24 hours to give us time to sync charts from there. We could go a different route and instead **snapshot** changed from the staging server before destruction and then use the snapshot for syncing charts.

Ideally, we'd dump the whole MySQL database (or at least necessary tables like `variables`, `charts`, etc.), save it to R2 and fetch it when running CLI. It'd be nice if we could dump it as SQLite and then query the file directly.

**Comment by Marigold** [comment]
Let's keep this open a bit longer. We've done the UI and several of above mentioned improvements.

**Comment by Marigold** [comment]
More ideas by @danyx23 with quick replies

> I think when you do a dry run it would be great if you could click the chart ids and it would open in a new window on that staging servers (our urls are predictable, so I think this should work) and/or maybe even try to add an image tag that points to the thumbnail of that chart. The reason for this is that chart ids are a bit tough on their own to sanity check (did I publish/edit this one by mistake?).

The reason it shows "terminal"-like output without rich format is that it calls CLI `etl-staging-sync` and redirects its output to the app. The advantage is that we don't need duplicate CLI features in the streamlit app.

That said, perhaps even hyperlinks from that output could be clickable? (Haven't tried it)

> Could we add a buildkite step after a PR merge in ETL that just dumps the new and updated chart rows in some format (json? sql statements?) to a storage bucket? Or, if that is easier, do a mysql dump, zip it and store it in S3? If we want to make this our preferred way of working, having a 3 day gun pointed to your chart work doesn't sound very nice (e.g. you click merge on the Thursday evening before easter, forget about this rule, come back on Tuesday and all the chart work that the data manager and author did is gone). It's totally ok if restoring the work in these cases is a bit of work but we should have some way of salvaging it.

The initial plan was to take a dump of the entire MySQL, store it in R2 and then use it in staging sync instead of connecting to staging server MySQL. Such solution would let us kill staging server right after merging it. I started doing this, but then I realized it's real "work". Your idea of keeping staging alive and dumping MySQL just in case should be simpler.

I'd be curious of what others say when they start using it. I don't see it very likely (although the effort of backing up work is not as high).

**Comment by larsyencken** [comment]
@Marigold Can you please update this card with the most recent picture of where we are?

**Comment by Marigold** [comment]
Closing this, it'll be replaced by the new version of `chart-sync` with better `chart-diff` interaction.
