### ISSUE TITLE
enhance: deprecate `etl.data_helpers.population`

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2025]
This module only has one method: `add_population`, which should no longer be used because it does not have some latest features and has the population dataset URI hardcoded.

Instead, we should be using `etl.data_helpers.geo.add_population_to_table`.

There are couple of features that we should probably integrate from it into `etl.data_helpers.geo.add_population_to_table`; for instance the fact that it can add population values by country-year _and_ year age groups.

**Deadline**
- Probably nice to do it during 2024 Q1

**Comment by larsyencken** [comment]
@Marigold All uses of this are in the health space, perhaps something to check out when you're back if you have space?
