### ISSUE TITLE
Issue with Tag table in grapher step

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2037]
I'm running into this issue when running grapher steps: 

> [SQL: SELECT tags.id, tags.name, tags.slug, tags.`createdAt`, tags.`updatedAt`, tags.`isBulkImport`, tags.`parentId`, tags.`specialType` 
FROM tags 
WHERE tags.name IN (%s) AND tags.slug IS NOT NULL]
[parameters: ('Tuberculosis',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Tuberculosis is an existing tag and I am pretty sure I have pulled the latest masters on owid-grapher, etl and ops. 

An example would be: 

`poetry run etl grapher/tuberculosis/2023-11-27/expenditure --grapher` on `tb-expenditure` branch.

**Comment by Marigold** [comment]
@spoonerf could you try running `make refresh` from `etl` directory? There were some changes to MySQL structure yesterday.

**Comment by spoonerf** [comment]
Ah okay, I tried that and it's taking a while (not sure if that is unexpected or not), it's been stuck on this for the last few mins:


![Screenshot 2023-12-05 at 14 13 27](https://github.com/owid/etl/assets/10774728/7c085380-faf2-40fe-a5b5-60fbb82d4f15)

**Comment by spoonerf** [comment]
haha, I should ask Santa for more patience, that refreshed and the issue is solved. Thanks @Marigold!
