### ISSUE TITLE
metadata: ETL lets you define a string `description_key`, but then grapher creates a list of bullet points with just one letter

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2064]
ETL lets you define a string `description_key`, but then grapher creates a list of bullet points with just one letter.

Instead, ETL should raise a warning or an error when `description_key` is not an array.

**Comment by larsyencken** [comment]
This seems like a smaller point of a broader issue: shouldn't we be be applying a JSONschema to the metadata? That would solve this and also a range of other issues.

For YAML files, it could be done in CI. Perhaps in places where it's dynamic, at write time?

**Comment by Marigold** [comment]
There's a problem with legacy YAML files, as we don't have schema versioning. We have a linter for YAML files, though, so if it is manually created, you should see an error.

**Comment by larsyencken** [comment]
That's a fine reason for historical data, but it doesn't seem to be a good reason to skip using a schema on new data.

I'll make a new issue for it.

**Comment by Marigold** [comment]
Thanks, Pablo; I'll add an assert explicitly for this and then work on the strict schema validation that Lars suggested.

**Comment by lucasrodes** [comment]
Issue raised by pablo might be related to this one: https://github.com/owid/etl/issues/867

cc. @Marigold

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/pull/2454. I'll trigger nightly build to find if we still have steps like that.
