### ISSUE TITLE
Should the upstream source for the World Development Indicators be Open Numbers or the World Bank?

### ISSUE THREAD

**Issue by bnjmacdonald** [owid/etl#210]
## Context

PR #206 adds `walden->meadow->garden->grapher` steps for the World Development Indicators, using the [World Bank as the upstream source](https://datacatalog.worldbank.org/search/dataset/0037712).

But we actually already have an `open_numbers` step for the World Development Indicators, which uses [Open Numbers as the upstream source](https://github.com/open-numbers/ddf--open_numbers--world_development_indicators). There is currently no `grapher` step for this data.

## Question
**Do we want to use Open Numbers as the upstream source OR the World Bank as the upstream source?**

- A downside to using Open Numbers is that there is currently no `grapher` step, so the existing World Bank `grapher` step would need to be revised. This would probably require a few days of work to make sure that the variable/source metadata is assigned appropriately (which is rendered in a chart's Source tab). The existing `open_numbers` step would also need to be revised to include some of the logic that exists in the World Bank `garden` step (specifically country/region harmonization, which involves excluding a subset of regions).
- But if, generally speaking, we want to move towards using Open Numbers when possible, then I can see how it might be worth the time to revise these `garden`+`grapher` steps to use Open Numbers instead of the World Bank.

I generally don't know what our intentions are with Open Numbers, so I'm ill-equipped to answer this question. @Marigold perhaps?

## Related
- The `land_area` key_indicator ([garden step](https://github.com/owid/etl/blob/master/etl/steps/data/garden/owid/latest/key_indicators/table_land_area.py)) uses World Development Indicator data, currently using data from the `open_numbers` step. If we decide to use World Bank as the upstream source, this script should be revised.

**Comment by Marigold** [comment]
> But if, generally speaking, we want to move towards using Open Numbers when possible

I didn't want to give an impression we are moving towards Open Numbers! I think it's better to have things under our control. Another advantage of replacing ON with our version would be shorter time to build ETL (building open numbers is the bottleneck right now).
