### ISSUE TITLE
UN SDG metadata links stopped working

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2154]
We run into the following error with step `grapher/un/2023-08-16/un_sdg`
```
File "/var/lib/buildkite-agent/builds/etl-build-2-20/our-world-in-data/etl-full-private-rebuild-every-2nd-night/etl/steps/data/grapher/un/2023-08-16/un_sdg.py", line 53, in run
--
  | df_tab = add_metadata_and_prepare_for_grapher(df_var, ds_garden, source_desc)
  | File "/var/lib/buildkite-agent/builds/etl-build-2-20/our-world-in-data/etl-full-private-rebuild-every-2nd-night/etl/steps/data/grapher/un/2023-08-16/un_sdg.py", line 122, in add_metadata_and_prepare_for_grapher
  | source_desc_out = create_metadata_desc(
  | File "/var/lib/buildkite-agent/builds/etl-build-2-20/our-world-in-data/etl-full-private-rebuild-every-2nd-night/etl/steps/data/grapher/un/2023-08-16/un_sdg.py", line 105, in create_metadata_desc
  | source_url = get_metadata_link(indicator)
  | File "/var/lib/buildkite-agent/builds/etl-build-2-20/our-world-in-data/etl-full-private-rebuild-every-2nd-night/etl/steps/data/grapher/un/2023-08-16/un_sdg.py", line 251, in get_metadata_link
  | assert ctype_a == "application/pdf", url_a + "does not link to a pdf"
  | AssertionError: https://unstats.un.org/sdgs/metadata/files/Metadata-01-0a-02a.pdfdoes not link to a pdf
  |  
  | COMMAND: prlimit --as=34359738368 poetry run run_python_step data://grapher/un/2023-08-16/un_sdg /var/lib/buildkite-agent/builds/etl-build-2-20/our-world-in-data/etl-full-private-rebuild-every-2nd-night/data/grapher/un/2023-08-16/un_sdg
```

It looks like some (or maybe all?) links like https://unstats.un.org/sdgs/metadata/files/Metadata-10-01-01b.pdf have stopped working.

As a hotfix, we should consider disabling that URL until we find a workaround and build SDG without it.

Ideally, we shouldn't be making external HTTP requests in the grapher step, as we should be able to rebuild everything from snapshots (this might have been overkill for this case?). We could also fix this by getting those URLs from an old dataset and **adding them as a snapshot**. @spoonerf I'm happy to do that if you think that's the way to go.

**Comment by Marigold** [comment]
@spoonerf the newest version got fixed, but it [still happens](https://buildkite.com/our-world-in-data/etl-full-private-rebuild-every-2nd-night/builds/401#018ce138-9737-48e9-8f7a-4dd51d60342c) for `un/2023-01-24/un_sdg`. It's labelled as `UN SDG - archive` in `dag/main.yml`, but the dataset itself is not archived. It's still used by [4 charts](https://owid.cloud/admin/datasets/5895). Is there a reason for that or would it be possible to migrate them and archive it? If it's too much hassle, then we can just hotfix the old version.

**Comment by spoonerf** [comment]
Hey @Marigold! 

I've migrated three of the charts over to the latest dataset, but the variable for the last one isn't available in the latest dataset; this seems to happen occasionally with the UN SDG. Typically the variable reappears in a later version, so I will move that last chart over then. 

However, if it's annoying to have this huge dataset kicking around the etl for just one chart let me know, it's not really an important chart and we can totally replace it with a different one from the SDG dataset. 

I do the hotfix to the older dataset now.
