### ISSUE TITLE
Apply a strict schema to YAML metadata files

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2238]
## Problem

We would like to ensure that our YAML and `.meta.json` files have the metadata fields that we expect, and we would like to guard against accidental errors like [using the wrong type](https://github.com/owid/etl/issues/2064) for a field or having a typo in a field name.

## Proposed solution

Something along these lines would lock down our YAML in a helpful way:

1. Set up a schema for our current metadata standards
2. Allow YAML files to opt-in to that schema with a `$schema` parameter
3. Validate YAML files in CI against any schema they opt-in to
4. Add the `$schema` parameter and opt-in historical YAML files that are already compliant
5. Have CI check for compliance for datasets created after a certain date (i.e. force them to opt in)

**Comment by alhridoy** [comment]
Hi @larsyencken could you advise which files you think would be good starting points to focus on for adding YAML schema validation?

Some areas I was considering are:

schemas/: To add the new JSON validation schema. I can start with the existing metadata standard.
etl/: Where we could integrate the validation during metadata parsing.
tests/: To add new test cases.

Thanks

**Comment by larsyencken** [comment]
Mildly inclined to call it important to lock down our metadata like this, to prevent edge case errors.

**Comment by lucasrodes** [comment]
Just as an FYI, and in case it affects other parts of the project: We currently have schemas in [`schemas/`](https://github.com/owid/etl/tree/master/schemas), which power:

- [Our documentation on Metadata](https://docs.owid.io/projects/etl/architecture/metadata/reference/). 
  - The documentation is rendered using [this script](https://github.com/owid/etl/blob/master/docs/ignore/generate_dynamic_docs.py).
- Our [Meta Expert](http://etl.owid.io/wizard/Meta%20Expert) tool to answer any questions on metadata.
  - It relies on the same functions as our documentation generation above. See [`apps/wizard/pages/meta_expert/prompts.py`](https://github.com/owid/etl/blob/master/apps/wizard/pages/meta_expert/prompts.py), which uses functions from [`etl.docs`](etl/docs.py).
- The hints and helper texts on Wizard when creating new steps (see screenshot below). These are rendered in the individual python scripts (e.g. [`apps/wizard/etl_steps/snapshot.py`](apps/wizard/etl_steps/snapshot.py) for snapshot). These also use functions from [`etl.docs`](etl/docs.py).
  ![image](https://github.com/owid/etl/assets/18101289/d03a947e-6b99-40b4-bd2e-998783e80120)

**Comment by Marigold** [comment]
This would also solve https://github.com/owid/etl/issues/2064
