### ISSUE TITLE
About 15% of indicators give 404s in the data API

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2240]
## Problem

We created the data API to move data and metadata out of MySQL. It should have 100% coverage over data that's in our database, including data that's not used in any chart.

However, when we exhaustively scan the API for variables listed in MySQL, we find that ~15% of them give 404s in the API. Upon inspection, their files are missing from R2.

## Impact

UPDATE: we have been able to fully back up the data API and there are overall no missing indicators -- the missing data is for old unused indicators

## Examples

|   id   |                           metadata_url                            |
|--------|-------------------------------------------------------------------|
| 479956 | https://api.ourworldindata.org/v1/indicators/479956.metadata.json |
| 597298 | https://api.ourworldindata.org/v1/indicators/597298.metadata.json |
| 595022 | https://api.ourworldindata.org/v1/indicators/595022.metadata.json |
| 486058 | https://api.ourworldindata.org/v1/indicators/486058.metadata.json |
| 487050 | https://api.ourworldindata.org/v1/indicators/487050.metadata.json |
| 452268 | https://api.ourworldindata.org/v1/indicators/452268.metadata.json |
| 588058 | https://api.ourworldindata.org/v1/indicators/588058.metadata.json |
| 490332 | https://api.ourworldindata.org/v1/indicators/490332.metadata.json |
| 479372 | https://api.ourworldindata.org/v1/indicators/479372.metadata.json |
| 483199 | https://api.ourworldindata.org/v1/indicators/483199.metadata.json |

## Technical notes

- API requests are served from a CloudFlare worker that fetches the data from R2
- The data does not appear to be in R2 for these cases
- These failing requests all appear to redirect to a legacy catalog URL, perhaps as a fallback (e.g. https://catalog.ourworldindata.org/baked-variables/live_grapher/metadata/479956.json)

**Comment by larsyencken** [comment]
It appears that 479956 exists in the old baked variables, perhaps the fallback URL in the worker is bad?

The failing fallback URL: https://catalog.ourworldindata.org/baked-variables/live_grapher/metadata/479956.json

A working URL: https://owid-catalog.nyc3.digitaloceanspaces.com/baked-variables/live_grapher/metadata/479956.json

**Comment by larsyencken** [comment]
Using the working URL above as a fallback, I was able to access JSON metadata and data for every single indicator.

**Comment by Marigold** [comment]
I looked at those examples, and all come from **old archived ETL datasets**. It's possible that I forgot to create JSON records for these. The easiest "solution" would be to wait for the next dataset cleanup and remove them.

If we really needed them, we'd have to unarchive and rerun them or move data files from the old catalog. (Or we could park this and wait if anyone complains in the next few months)

```
select
    d.*
from datasets as d
join variables as v on d.id = v.datasetId
where v.id in (479956, 597298, 595022, 486058, 487050, 452268, 588058, 490332, 479372, 483199);
```

**Comment by larsyencken** [comment]
I'm satisfied that there's nothing that needs doing here.
