### ISSUE TITLE
Project: Wizard to update steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2249]
# Update wizard
We currently have tools to walk us through the **creation** of snapshots and data steps (namely the etl-wizard snapshots, etl-wizard meadow, etc.). But we don't have a similar tool for the **update** of existing snapshots and data steps.

Here I'll describe a possible approach that could be achieved in one cycle, and then some possible additional features (nice to have, or for the future):

## Minimum requirements
We could have an `etl-step-update` cli/UI tool very similar to `etl-wizard` that works as follows:
* To update a specific snapshot (e.g. `etl-step-update snapshot://met_office_hadley_centre/2023-10-18/near_surface_temperature_southern_hemisphere.csv` which is the latest snapshot that we want to update): 
  * We have a very similar UI (or even the same?) to what we currently use for `etl-wizard snapshot`, but already filled out with the content of the latest metadata dvc file. All fields can be edited (which is especially important if, e.g. download link or publication date have changed).
  * Optionally, the UI may warn of particularly dangerous fields (e.g. there is an old year hardcoded).
  * When clicking on submit, it creates the new metadata dvc file (with the changes edited in the UI) and duplicates the latest snapshot script (keep in mind that it may be different to the raw script that `etl-wizard snapshot` would create).
  * You have the option to click on run (in the same way that `etl-wizard snapshot` does).
* To update a specific data step:
  * Duplicate a specific data step with the new version.
    * NOTE: To begin with, `shared.py` and similar files will be ignored.
  * Add the new step to the corresponding dag file. All dependencies will be in their latest active version.

## Full requirements
Since we would almost always want to update multiple data steps in one go (e.g. meadow, garden, grapher) we have a UI where:
* You choose a specific snapshot or grapher data step, and select whether you want to see either backward, or forward, or all dependencies of that step.
* Then you see all those steps with a checkbox.
  * NOTE: Maybe here you would not only see steps, but actual files, which would let you choose `shared.py` and other files to copy across.
* You select which of those steps you need to update, and they will be duplicated and added to the corresponding dag file.
* When steps are added to the dag, they have a nice header.
* All the dependencies of all new steps are the latest versions.

## Nice to have
* We could have a UI to edit metadata of the garden steps before the files are duplicated (since you may want to change a few things in the new version).

* We could decide which dependency versions to use: Sometimes, for datasets with many dependencies, we may want to update only certain dependencies and not others (because they may involve much additional work).
  * For every step you update, we could have a UI that shows the dependencies with a dropdown of active versions availble. By default, all latest versions are selected.
  * When you click run, a temp dag is created with that choice of versions. The temp dag is added to the main dag. The main step will be ETL run.
    * If it works without warnings or errors, it asks if transferring to main dag.
      * If so, append new lines to the corresponding dag file.
    * If fails, go back to UI with dropdowns of versions. Choose another combination and retry.

* We could have the option to revert changes (which you could do with git, but it would be nice if the tool already knows what lines from the dag and what files and folders exactly need to be deleted).

### Week 1
* Fix and improve VersionTracker (https://github.com/owid/etl/issues/1821) which may be a crucial tool to keep track of versions to update.
* [Interruption] May need to update the electricity dataset, given that there has been a release of new data.
### Week 2
* Create a minimum requirements CLI to update steps.
* Adapt existing UI to be used for updates.
### Week 3
* Add full requirements.
* Add documentation.
### Cooldown
* Consider the nice to have features.
* Consider adding grapher info to VersionTracker.

**Comment by lucasrodes** [comment]
Thanks for drafting this, @pabloarosado!

Some very initial thoughts:

- I think that the UI should _be part_ of wizard. This way, we are aligned with our goals here: https://github.com/owid/owid-issues/issues/1365, which are to have a single space for all our ETL tooling apps.
- As per the command client, the specific naming of it is not really important now. But the way I envision our command tools, is that all of them are under the umbrella of a single command client. E.g. `etls run [step]`, `etls harmonizer`.

At the end of the day, it'd be nice to have a single UI space (i.e. `Wizard`) and a single command client (I just thought of `etls` for now, which stands for "etl services").

**Comment by pabloarosado** [comment]
The ETL dashboard (and the CLI for StepUpdater) are now [in production](http://etl.owid.io/wizard/ETL%20Dashboard). We also have [this tracking issue](https://github.com/owid/etl/issues/2365), where we can add any bugs or possible improvements.
