### ISSUE TITLE
CI builds sometimes fail with ChecksumMismatch error

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2352]
Builds are sometimes failing due to checksum errors in snapshots.

### Nightly build

```
ValueError: Checksum mismatch for /var/lib/buildkite-agent/builds/etl-build-2-13/our-world-in-data/etl-full-private-rebuild-every-2nd-night/data/snapshots/un/2023-01-24/un_sdg.feather: expected 4eec76d904280209ba5a635b21e28b54, got 16f1859d406e476d5600ad4e0cc9af5e
```
https://buildkite.com/our-world-in-data/etl-full-private-rebuild-every-2nd-night/builds/436#018df003-c571-4351-8811-04d6a372081f

**Comment by Marigold** [comment]
Ugh, I have no idea how that could happen. It's almost as if it was an incomplete download with messed-up checksum. I can replicate it neither locally nor in buildkite environment. I restarted the job. If this starts occurring more frequently, we could compare its filesize and retry if necessary.

**Comment by larsyencken** [comment]
That kind of explanation could make sense, since the previous `ChecksumMismatch` was for a different snapshot.

**Comment by larsyencken** [comment]
I'm going to run a loop of downloading snapshots (bandwidth is free on Hetzner) and see if I can get a failure in an isolated place.

**Comment by larsyencken** [comment]
Nightly builds are green, closing this until it comes up again
