### ISSUE TITLE
chart-sync: use more informative user name in approval tool

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2377]
## Problem

Currently, when a user uses the chart-sync, all charts modified in the source server are put in the queue of the chart approval tool under the user name "ETL":

![image](https://github.com/owid/etl/assets/18101289/9f58819c-b629-482e-8c89-ae9b73fe62d7)

This could be more informative. Instead, we could label it according to the branch that created the staging server, e.g. "fix/population".

## Technical notes

This is a bit tricky, as the `SuggestedChartRevisions` object is created with the user ID (and not user name). Key code to change:

- In [etl](https://github.com/owid/etl/blob/master/apps/staging_sync/cli.py#L217-L225)
- In [owid-grapher](https://github.com/owid/owid-grapher/blob/master/adminSiteClient/SuggestedChartRevisionApproverPage.tsx#L594-L618)

**Comment by Marigold** [comment]
Good idea, though might not be trivial if we don't know how to effectively do development chart revision tool. (Could be also parked until we decide to refactor it in streamlit)

**Comment by larsyencken** [comment]
Related to #2465

**Comment by lucasrodes** [comment]
(quick follow-up on this issue)

Recently I thought of a quick win in this domain, and it occurred to me that we could add some note in the "Reason for suggested revision" field, which is shown at the bottom of the suggestion (see screenshot) and comes from the field `suggestedReason` in table `suggested_chart_revisions`.

![image](https://github.com/owid/etl/assets/18101289/68516791-cf73-46e2-a0af-4c9a449133a3)

We might move the chart approval tool to Streamlit at some point, so this solution doesn't take much time.

This quick solution wouldn’t provide filtering, but it could be a hacky way to see where that revision comes from without touching any typescript.

**Comment by lucasrodes** [comment]
This is no longer on the roadmap, given that we will be switching to a new workflow: https://github.com/owid/etl/issues/2580
