### ISSUE TITLE
Batch cycle: ETL and ops improvements for cycle 2024.2

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2390]
_Last update Wed 10th Apr._

**Must do**

- [x] https://github.com/owid/owid-grapher/pull/3128
- [x] https://github.com/owid/etl/issues/2238
- [x] Propagate data types to MySQL from ETL for Sophia https://github.com/owid/owid-grapher/pull/2039
- [x] https://github.com/owid/ops/issues/10
- [x] #1094 

**Could do**

- [x] https://github.com/owid/owid-grapher/issues/3303
- [x] owid/etl#2393
- [x] https://github.com/owid/ops/issues/97

**Not this cycle**

- [ ] owid/etl#2394
- [ ] https://github.com/owid/ops/issues/155
- [ ] #2411
- [x] owid/ops#153
- [ ] owid/etl#2392
- [ ] owid/etl#2391
- [ ] #2495

**Comment by Marigold** [comment]
More candidates:
- Propagate data types to MySQL from ETL for Sophia https://github.com/owid/owid-grapher/pull/2039
- Migrate GDrive images to R2 https://github.com/owid/owid-grapher/pull/3128
- https://github.com/owid/owid-grapher/issues/3303
- https://github.com/owid/ops/issues/97
