### ISSUE TITLE
Data diff: single line diff against previous dataset version

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2393]
## What

`etl diff path/to/dataset` automatically detects the previous version of the dataset and diffs against that.

## Why? Why now?

One of the most common things we do is to update a dataset. We want to catch differences early, rather than late at chart revision.

**Comment by Marigold** [comment]
That already exists but is implicit only. If the dataset doesn't exist in target, it'll try to find the previous version and compare it against it. I've created artificial `grapher/who/2024-04-03/gho_suicides` and running
```
etl diff REMOTE data/ --include grapher/who/2024-04-03/gho_suicides --verbose
```
gives the following output
```
~ Dataset grapher/who/2024-04-03/gho_suicides (new version)
    - version: '2024-02-14'
    ?                 ^ ^^
    + version: '2024-04-03'
    ?                 ^ ^^
  = Table gho_suicides
    ~ Column suicide_rate (changed data)
        - Changed values: 11400 / 11400 (100.00%)
        - year: 20 affected
        - country: 190 affected
        - sex: both sexes, female, male
        - Avg. change: 1.00 (8%)
```

This is useful in PR when creating a new version. It doesn't let you compare against a previous version in the same data folder though. Would that be useful? I guess we could make it possible to run `etl diff` on two datasets, e.g.
```
etl diff grapher/who/2024-04-03/gho_suicides grapher/who/2024-02-01/gho_suicides
```
cc @pabloarosado

**Comment by pabloarosado** [comment]
Hi @Marigold yes, that would be useful. I just tried `etl diff data/ data/ garden/climate/2024-01-31/sea_ice_index garden/climate/2024-03-11/sea_ice_index` but as you said, it failed (`Got unexpected extra arguments (garden/climate/2024-01-31/sea_ice_index garden/climate/2024-03-11/sea_ice_index)`).

**Comment by Marigold** [comment]
This PR https://github.com/owid/etl/pull/2494 should let you run datadiff with two versions of a dataset, e.g.
```
etl diff data/garden/climate/2024-01-31/sea_ice_index data/garden/climate/2024-03-11/sea_ice_index --verbose
```
