### ISSUE TITLE
Skip chart revision for charts with identical data

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2394]
## What

Improve the chart revision flow by skipping charts that have no differences.

## Why? Why now?

Currently, charts are queued up for manual review even when there are no changes, e.g. because other variables in a dataset changed.

We should make this flow more efficient by only requiring QA when there is something to QA.

## Technical notes

- Aren't there already options for auto-applying some chart revisions in staging sync?
  - Yes, in staging sync this is to avoid a double approval workflow
- The chart revision code is the last piece for Daniel to migrate TypeORM-to-Knex database code; should he do it, or should we migrate it to Streamlit? Unclear
- **Decision:** we should do this not in the chart approval code but in the code that decides whether to queue a chart for approval

**Comment by danyx23** [comment]
This is simple to do and still useful

**Comment by danyx23** [comment]
But maybe we should move it over to the grapher repo as this is where this logic lies?

**Comment by Marigold** [comment]
We plan to deprecate chart revisions in favour of chart-diff (which already has this feature). What is "worth QA-ing" in general is a bigger question we shall open soon after.
