### ISSUE TITLE
Project: backport variables from MySQL to the ETL

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#24]
## Problem

We want our data catalog to be an authentic catalog of all the data we use at OWID, to in fact be the same data we present to people on the site. But we have a lot of old data that we will never recover or write a recipe for. To get this into our data catalog we will need to backport it somehow.

Our admin interface is also used daily as a way of getting new data in, skipping both importers and the ETL. It would be excellent to have a way to get this data into the ETL as well.

## Scope

- [x] Come up with a design proposal
- [x] #132
    - [ ] align metadata from MySQL schema into ETL schema to make it lossless
    - [ ] script for getting data from grapher into walden
    - [ ] ETL step to get data from walden into our catalog
- [ ] Script to audit MySQL to know if a backport is out of date (content hash of variables)
- [ ] #152
- [x] #151

## Success means

- [ ] We can backport a variable with a single command
- [ ] Backported variables are available via published API
- [ ] We can tell if MySQL has newer data than our backport
- [ ] The backport is lossless

## Architectural approach

https://www.notion.so/owid/Proposal-for-backporting-MySQL-variables-to-the-ETL-0a33cbb0fca94f72b6542875e6003eb4

## Loose ideas

Create a new `backport` namespace and, using a MySQL connection to Grapher's database, export all public datasets to our new catalog format.

This is most sensible to do once `importers` is no longer used, and once the `etl` is capturing all or nearly all the new additions to the grapher db. Then it can be done once, rather than over and over.

**Comment by larsyencken** [comment]
After thinking about this more, I think we should have a dynamic backport system that can do just one variable at a time.

**Comment by Marigold** [comment]
## Scope

New scope based on the [latest proposal](https://www.notion.so/owid/Proposal-for-backporting-MySQL-variables-to-the-ETL-0a33cbb0fca94f72b6542875e6003eb4)

- [ ] script for getting data from grapher into walden (with lossless metadata)
- [ ] ETL step to get data from walden into our catalog
- [ ] align metadata from MySQL schema into ETL schema
- [ ] content hash of variables and its data in MySQL

**Comment by larsyencken** [comment]
@Marigold Just merged the scopes with your changes and adjusted the project description, does it look ok?

**Comment by larsyencken** [comment]
Superseded now by https://github.com/owid/etl/issues/195, closing this one
