### ISSUE TITLE
Improve performance of SDG tracker

### ISSUE THREAD

**Issue by Marigold** [owid/etl#241]
Step `data://garden/sdg/latest/sdg` takes a long time to build and it is rebuilt quite often as its backported dependencies change. We should optimise it or at least parallelise it, but it is very likely there's some trivial performance bottleneck that could be solved by caching or preloading.

**Comment by wcox13** [comment]
sounds good! assigned myself

**Comment by wcox13** [comment]
Alright, was new to Python profiling so it took me a sec, but here it is! https://github.com/owid/owid-catalog-py/pull/49

**Comment by Marigold** [comment]
> Alright, was new to Python profiling so it took me a sec

Just out of curiosity - what tools did you use? I'm used to `%lprun` and `%cprun` from jupyter notebook, but I guess there must be better tools now.

**Comment by wcox13** [comment]
I used `cProfile` then chipped away at the output with `pstats` (e.g. sorting by cumulative time). Just what was recommended in pydocs. I haven't done it in Jupyter and I don't know if this is actually better!
