### ISSUE TITLE
docs: Old link to pythonic api on OWID home page

### ISSUE THREAD

**Issue by joelostblom** [owid/etl#2432]
### One-liner
Old link to pythonic api on OWID home page https://ourworldindata.org/teaching#how-can-i-use-our-world-in-data-to-teach

### Context & details
The website still links the old repo where it says "Pythonic API" instead of this new repo.

(This should be filed against the website, but I can't find a repo for that.)

**Comment by lucasrodes** [comment]
hi @joelostblom ! thanks for reporting. We have updated the link. It is now using: https://docs.owid.io/projects/etl/api/
