### ISSUE TITLE
Remove backported steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2477]
Can we get rid of backported steps?

Only 5 backported datasets are used in ETL. Of those, only 1 is used in charts, namely `backport://backport/owid/latest/dataset_5676_global_health_observatory__world_health_organization__2022_08`, which is used in 5 charts.

Eventually, it would be good to get rid of all the code related to backports, but, for now, I was wondering if we could simply remove the steps (i.e. the many `dataset_...` files) that are not used, and keep only the 5 that are used.

Having these files becomes quite inconvenient, for example, when searching for files in VSCode. They often appear in file or code search results:
https://github.com/owid/etl/assets/12246978/676634eb-8619-4a86-85f3-7ee72b247bf8

**Comment by Marigold** [comment]
This would take a couple of days possibly, backporting has many tentacles.

**Comment by Marigold** [comment]
Don't close it! Backports have no place in our codebase.

**Comment by Marigold** [comment]
All backport:// steps are [gone](https://github.com/owid/etl/pull/3172)!
