### ISSUE TITLE
Admin metadata editing of types

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2495]
## Context & motivation

On the Grapher side, we would like to make use of ordinal type information, especially in a few places such as scatterplot legend labels. (e.g. income groups)

But we have a chicken and egg problem; we don't have this data to use yet, so it's not helpful to support using it in Grapher.

## Proposal

Enable setting ordinal type information on an indicator in the admin, so that someone doing a chart can go and fix the ordering of an indicator legend this way.

## Mojmir notes

I'm sceptical of the value of editing types in admin. This only makes sense for **ordinal type** now. I don't think this should be important because:

1. No one has edited any metadata yet
2. Ordinal type is only relevant to a couple of indicators (two as of now - income and age groups)
3. Implementing this in admin could be non-trivial (fetching all values from JSON file and displaying them as sortable component)

**Comment by larsyencken** [comment]
Thanks for your thoughts @Marigold! 

I totally understand that it can feel not valuable to invest in something people aren't using. The motivation for this was not about where we are not, but we're we're trying to take Grapher's type model. Based on your feedback though, I agree we can take it off the table for this cycle and discuss it with Sophia at the offsite instead.

Separately, on admin editing, I bet that the complexity of the mapping between indicator + chart to data page is a big barrier to people editing in the admin. It could be cool to do an experiment where we help an author upgrade an chart/indicator into a data page, purely using the admin, then we see if there are a few simple links we could add that make that easier.

**Comment by larsyencken** [comment]
We can park this one for now, the type system is not the main focus in Grapher-land in the near future.
