### ISSUE TITLE
StepUpdater doesn't work well after recent changes (possibly pandas update?)

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2517]
StepUpdater silently does the wrong thing after recent changes (possibly pandas update?).

To replicate, run `etl update data://meadow/emdat/2023-09-20/natural_disasters snapshot://emdat/2023-09-20/natural_disasters.xlsx`

When running that command on an old ETL state (e.g. `git checkout 074c9e6bdbf12eebc6de465df7ceb381ae0b3ab0`, and then `poetry install`), the resulting `main.yml` file has the content:

```
  #
  # EM-DAT Natural disasters (2023).
  #
  data://meadow/emdat/2024-04-11/natural_disasters:
    - snapshot://emdat/2024-04-11/natural_disasters.xlsx

```

which is correct.

However, when running it on ETL master, the resulting `main.yml` file has the content:

```

  #
  # EM-DAT Natural disasters (2023).
  #
  data://meadow/emdat/2024-04-11/natural_disasters:
    - snapshot://emdat/2023-09-20/natural_disasters.xlsx
```
which is wrong because the new meadow uses the old snapshot.

The issue must be something in [this file](https://github.com/owid/etl/blob/master/apps/step_update/cli.py), possibly related to how VersionTracker is reloaded after creating the snapshot step (`_load_version_tracker()`).

**Comment by Marigold** [comment]
@pabloarosado, that might be my fault. I started caching `load_dag` which is used by StepUpdater through VersionTracker. I've [created a PR](https://github.com/owid/etl/pull/2518/files) that reverts the global caching and only caches it in PathFinder. Could it be the cause?

**Comment by pabloarosado** [comment]
> @pabloarosado, that might be my fault. I started caching `load_dag` which is used by StepUpdater through VersionTracker. I've [created a PR](https://github.com/owid/etl/pull/2518/files) that reverts the global caching and only caches it in PathFinder. Could it be the cause?

Thanks a lot, this was driving me crazy. Yes, your PR fixes the issue.
