### ISSUE TITLE
Problems with long URLs in staging servers

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2532]
When creating a branch with a long name, the staging server is created with a trimmed version of that name.

For example, I created a branch called `update-climate-data-and-fix-co2-concentration-issue`, and the staging server is `http://staging-site-update-climate-data-and-fix-co2-concentration-issu/`.

Maybe it's good (or necessary) to avoid very long URLs. If that's the case, at least, the owidbot should account for this issue when displaying the URL of the server. In the case of the example, owidbot said:
```
Staging server:
Admin: http://staging-site-update-climate-data-and-fix-co2-concentration-issue/admin/login
Site: http://staging-site-update-climate-data-and-fix-co2-concentration-issue/
Login: ssh owid@staging-site-update-climate-data-and-fix-co2-concentration-issue
```
But those URLs do not exist.

**Comment by Marigold** [comment]
LXC containers have a hard limit on names to something like 63 characters, which is why we trim it. I'll fix the owidbot.

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/pull/2530
