### ISSUE TITLE
wizard: snapshot local file import restarts if you click away from screen

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2549]
### One-liner
When running Snapshot and importing a local file, you can add the file path to Wizard. If you do this in more than one click or aren't quite quick, it restarts the page, and you need to enter the snapshot metadata again. 

Hard to explain so I've included a screengrab!

### Environment

- Python: 3.11
- Operating system: Mac OS 14.2.1 (23C71)
- Working with local, staging or live: local

### Context & details

https://github.com/owid/etl/assets/10774728/5367a104-a7c0-47ee-bac5-7704e90277b9

**Comment by lucasrodes** [comment]
@spoonerf I'll take a look into this! 

Note that the snapshot files should have been created already, so no need to fill in the metadata again. You can instead use the terminal command:

```shell
python snapshots/path/to/script.py --path-to-file path/to/file.csv
```

**Comment by spoonerf** [comment]
Ah thanks @lucasrodes - that is good to know!
