### ISSUE TITLE
Move explorers into their own channel

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#255]
## Problem

The `garden` channel is polluted with tiny tables from the food explorer.

## Suggested solution

Move the food explorer from `garden/explorers/2021/food_explorer` to `explorers/owid/2021/food_explorer`.

It would need to be done in three steps:

1. Wait for new food explorer data to be published by @pabloarosado 
2. Migrate the production config to point to the new location
3. Delete the old location

**Comment by larsyencken** [comment]
@pabloarosado Perhaps you're already doing something like this in your FAO work?

**Comment by pabloarosado** [comment]
Hi @larsyencken. I added the new explorer to the new channel outside `garden`, but have not moved the old explorer yet. That could be a different PR. Do you want me to do it?
By the way, I called the new channel `explorer`. Should I rename it to `explorers`? I don't mind either name.

**Comment by larsyencken** [comment]
Ah, good stuff! Then we can pick up this issue after the `add-new-faostat-steps` branch gets merged.

I have a soft preference for `explorers` over `explorer`, but I'm easy.

**Comment by pabloarosado** [comment]
I have changed `explorer` to `explorers` on [this branch](https://github.com/owid/etl/tree/add-new-faostat-steps).

**Comment by pabloarosado** [comment]
Hi @larsyencken. The new food explorer is now in master, and I have moved the old food explorer to the new explorers channel. So in principle I think this issue can be closed, but I'm not sure if there is anything else to be changed.

**Comment by larsyencken** [comment]
I'm a little confused as to the current status. Is your new data that's been merged in actually being used in the current global food explorer, or is prod still using the old data?

**Comment by pabloarosado** [comment]
Hi @larsyencken the global food explorer in production is using the new data.

**Comment by larsyencken** [comment]
Ah, cheers, I see it. Closing now.
