### ISSUE TITLE
Staging servers with real users instead of Admin

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2578]
All our staging servers use `admin` as a user, which means that all charts would have "Created by Admin" on them. This would happen even after syncing charts to production.

I'm not sure if this would be technically feasible, but it'd involve:

- Get logged user in Wizard (can we get it from cookies or from `sessions` table in MySQL?)
- `AdminAPI` object artificially creates sessions to call API for creating charts, this would have change too to use real user
- Getting production users to staging servers (by calling `make refresh` there)

## Alternatives

After merging PR, `chart-sync` could get author name from the git branch, map it to user in production and use it for creating charts.

**Comment by lucasrodes** [comment]
Maybe useful for Wizard running on staging / production environments: https://arc.net/l/quote/vuafspjx

**Comment by Marigold** [comment]
This would be still useful, though it's not clear how important it is (with respect to technical feasibility).

**Comment by Marigold** [comment]
There's a new [st.context](https://docs.streamlit.io/develop/api-reference/utilities/st.context) in streamlit that can access cookies to detect user id.

**Comment by Marigold** [comment]
Tailscale provides info about logged-in users in requests. Check out the [discussion](https://owid.slack.com/archives/C03JTHBPCN5/p1723046984709909?thread_ts=1723043795.407959&cid=C03JTHBPCN5).

![image](https://github.com/user-attachments/assets/8e159d70-f510-49ea-8bfe-be72bd0be4df)

**Comment by Marigold** [comment]
@lucasrodes this is among "nice to haves" which makes me reluctant to start it. Do you think it could be important enough to start working on it?

**Comment by Marigold** [comment]
This is something we definitely want to have if possible.
