### ISSUE TITLE
Snapshot typo not updating

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2584]
I might totally be missing something here, but I _think_ this is a bug. 

I made a typo in the citation and producer of [this variable](https://ourworldindata.org/grapher/polio-vaccine-schedule#sources-and-processing) (_Oragnization_). I fixed it in [GitHub last week](https://github.com/owid/etl/commit/c46dbc05db7e1f6e612c632440018102f7837256), and that commit seemed to run as expected, but the typo is still on the data page. I can’t see any other point in the etl where that typo might be coming in, other than the snapshot. 

@Marigold any idea what is going on or what I'm missing?

**Comment by lucasrodes** [comment]
might be related to https://github.com/owid/etl/issues/2596?
