### ISSUE TITLE
Wizard restarts on every commit on a staging server

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2637]
Streamlit currently restarts every time something is committed to a staging server. But, if you are working on the Wizard (e.g. upgrading indicators or reviewing charts), you may lose work. Would it be possible to avoid the restart?

**Comment by Marigold** [comment]
We can enable live reload on staging servers and do hard restart on master (where there's a likely code change).

**Comment by Marigold** [comment]
> I am not sure I follow on this one. What's the difference between 'live reload' and 'hard restart'?

As far as I know, streamlit uses "live reload" by default (if you make any code change, it'll reload the app). By "hard restart" I mean restarting the app (which is done via pm2 process manager).
