### ISSUE TITLE
wizard: link to wizard pages doesn't work when opened for the first time

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2662]
Owidbot posts a link to chart-diff page to every PR such as http://staging-site-ntd-funding/etl/wizard/Chart%20Diff. However, when I click on it, I see an error
```
Page not found
You have requested page /Chart Diff, but no corresponding file was found in the app's pages/ directory. Running the app's main page.
```
Then I have to manually click on it in wizard. Interesting, after opening the page from Wizard, the link then works (I guess streamlit saves some info about the page internally?).

It's not a big deal, but I wonder if there's an easy solution and whether it bothers someone else too.

**Comment by lucasrodes** [comment]
this has been occurring for some time and, while not urgent, it is a bit annoying.

we currently use a third party library to manage a multi-page app (i.e wizard): https://github.com/blackary/st_pages. So one option would be to explore a bit more how we use this library and try to see if we can fix this. 

On the other hand, streamlit has some capabilities for multi-page apps, but I remember these being quite limited. See [docs](https://docs.streamlit.io/get-started/tutorials/create-a-multipage-app).

In [streamlit's roadmap](https://roadmap.streamlit.app), they mention that they are working on improving (actually testing) their native support (see section 'Multipage apps v2 - Public Preview'). So another option would be to see if we are better of using native support once their v2 is out.

**Comment by Marigold** [comment]
If it's on their roadmap, then I wouldn't worry about this. It's just one extra click.

**Comment by pabloarosado** [comment]
For now, I think a simple solution would be that the link points to the wizard, not to chart diff. The user would need to do an extra click anyway, but at least they would not see the error and get confused.

**Comment by lucasrodes** [comment]
The situation might improve with the new release of MPA v2, but I think there are couple of issues there still.

For the time being, a solution is to use query-based link with the alias of the page (see [config.yml](https://github.com/owid/etl/blob/master/apps/wizard/config/config.yml) for aliases). For chart diff, that'd be: http://staging-site-master/etl/wizard?page=chart-diff

**Comment by lucasrodes** [comment]
This issue still happening in MPAv2. Raised an issue here: https://github.com/streamlit/streamlit/issues/8860
