### ISSUE TITLE
metadata: allow non-integer values in display.numDecimalPlaces

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2673]
### One-liner
I would like to use a Jinja template to fill in the `display.numDecimalPlaces` field, but currently this is causing the [CI etl-unit-tests](https://buildkite.com/our-world-in-data/etl-unit-tests/builds/14886#018f9a9a-2583-4a2d-9a9b-0ab53eab7c75) to fail, as the schema only allows integers in this field. 

### Context & details
Would it be possible to relax this constraint?
![Screenshot 2024-05-21 at 11 06 47](https://github.com/owid/etl/assets/10774728/1a25e784-8a65-46a3-8392-7f85563a51af)

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/commit/b4ad0d656bbed3494894296435a180709feb2aa4. Feel free to add it to more fields if you need to use templates.
