### ISSUE TITLE
Create a streamlit tool to define map brackets in explorers

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#2683]
Choosing map brackets is painful. At an individual chart level, at least we have a visual tool to achieve this (however, it can be improved, there is [an issue](https://github.com/owid/owid-grapher/issues/3641) on how to achieve this, and [another issue](https://github.com/owid/owid-grapher/issues/3640) on what should be the default strategy).

But for explorers we don't have any tool in the grapher admin. So, creating file-based or indicator-based explorers means manually going view after view and manually setting each of the numeric bins.

To begin with, we could have a tool in streamlit that:
* ingests a variable id,
* fetches the data from `https://api.ourworldindata.org/v1/indicators/{variable_id}.data.json`,
* shows a grapher map chart,
* lets the user pick the map brackets,
* returns the bracket values.

Then, instead of ingesting one variable, it could get a list of variables, and the tool would let the user tweak the brackets one by one (with a similar layout to chart-diff).

So, the user would go to an explorer admin, select the variable ids from a column, copy them to the clipboard, paste them in the streamlit input, tweak all brackets, copy the resulting list of brackets to the clipboard, and then paste them back in the explorer.

**Comment by larsyencken** [comment]
Is this done for now, from your perspective @pabloarosado ?

**Comment by pabloarosado** [comment]
Yes, @larsyencken I think we can close this for now. We can improve it little by little as we use it.
