### ISSUE TITLE
Compute checksums for indicators

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2726]
## Motivation

Chart-diff can detect if chart config has changed, but it cannot detect if the underlying data changed (we only have indicator ID in chart config). If we had the indicator's checksum saved in MySQL, we'd be able to do those kinds of checks.

This could also be useful for automatically approving charts in chart-diff that are identical. We could replace indicator IDs with their checksums in chart config and compare them.

## Implementation

The most intuitive approach seems to be calculating checksums from data & metadata JSON files that we save to R2.

### [data.json](https://api.ourworldindata.org/v1/indicators/553199.metadata.json)

We should sort the data first before calculating the checksum. Then the checksum could even be `etag` (we could calculate it ourselves or get it from R2).

### [metadata.json](https://api.ourworldindata.org/v1/indicators/553199.metadata.json)

Metadata contains fields that shouldn't be part of the checksum, like `createdAt` or `updatedAt`. 

This could correspond to the etag of the file, but the problem is that metadata contains fields that shouldn't be part of the checksum like `updatedAt`, etc. So it would likely differ from the etag.

## Risks

Computing checksums could be CPU-intensive and might hurt the performance of large datasets.

**Comment by lucasrodes** [comment]
implementing this in https://github.com/owid/etl/pull/2743

**Comment by lucasrodes** [comment]
@Marigold can this be closed?

**Comment by Marigold** [comment]
Done.
