### ISSUE TITLE
🐛 indicator upgrader: correctly detect new datasets

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2733]
### One-liner
Detection is not working as expected. It sometimes detects more datasets than actually needed.

Working on an example here: https://github.com/owid/etl/pull/2731

### Context & details

When going to indicator upgrader, one should expect to have the dropdown for the new dataset automatically set to the new dataset. Or with the subset of datasets that are new to the branch.

However, this is not happening in most of the cases. For context, find below the relevant parts in the codebase. Note that some commentary and love is very much needed to these parts.

1. In indicator upgrader, the list with the new datasets is obtained:
https://github.com/owid/etl/blob/78652349742e413787861fcb337e1e964d39ca23/apps/wizard/app_pages/indicator_upgrade/app.py#L60
2. This goes into:
https://github.com/owid/etl/blob/78652349742e413787861fcb337e1e964d39ca23/apps/wizard/app_pages/indicator_upgrade/utils.py#L32-L61
3. Which relies on `VersionTracker` and others
https://github.com/owid/etl/blob/78652349742e413787861fcb337e1e964d39ca23/apps/wizard/app_pages/indicator_upgrade/utils.py#L32-L61

### PR
https://github.com/owid/etl/pull/2731

**Comment by pabloarosado** [comment]
Thanks for creating this issue, @lucasrodes. For me, the detection of modified datasets works well when working with local wizard on local files (which is what we should do with the new workflow). But on staging wizard something odd happens (I think staging servers are doing some git operations that affect the logic of the function). Or does the dataset detection fail also in your local wizard?
