### ISSUE TITLE
Problem with computation of government expenditure as a share of national income

### ISSUE THREAD

**Issue by pedro-s-amaral** [owid/etl#2755]
There is an error in the computation of government expenditure as a share of national income using the IMF data from Mauro (2015). The original data reports primary government expenditure, interest payment expenditure, and total government expenditure. The latter being the sum of the first two. 

In compiling the data, OWID mistakingly reports government expenditure as the sum of total government expenditure and interest payment expenditure. This effectively inflates the reported government expenditure since interest payments are added twice.

As an example,  take Denmark in 1993. The original IMF data, reports 53.55 primary expenditure, 6.66 interest expenditure, and 60.21 total expenditure (the sum of the first two). In contrast, OWID reports total expenditure at 66.88=60.21+6.66 (rounded).

**Comment by edomt** [comment]
Thank you for reporting, @pedro-s-amaral — we'll look into this (and https://github.com/owid/etl/issues/2756) and report back.

**Comment by paarriagadap** [comment]
Thanks for this message, @pedro-s-amaral. This was indeed an error in our calculation, so we decided to update to the [latest IMF data](https://www.imf.org/external/datamapper/datasets/FPP) (up to 2022). You can see the new data in this chart:
https://ourworldindata.org/grapher/historical-gov-spending-gdp
