### ISSUE TITLE
Source of data for government expenditure as a share of national income missing 

### ISSUE THREAD

**Issue by pedro-s-amaral** [owid/etl#2756]
The reported source for the OWID's government expenditure as a share of national income missing is the IMF Fiscal Affairs Departmental, based on Mauro et al. (2015). This is so for most of the data, but some countries, like Botswana or Egypt, are not present in the original reported source. Need to report the source used for such countries.

**Comment by paarriagadap** [comment]
Thanks for noticing, @pedro-s-amaral. With the updated described in https://github.com/owid/etl/issues/2755#issuecomment-2178726968 we decided to use data from one source, the [IMF's Public Finances in Modern History dataset](https://www.imf.org/external/datamapper/datasets/FPP). The source is now correctly displayed in the [Sources and processing section](https://ourworldindata.org/grapher/historical-gov-spending-gdp#sources-and-processing) of [our chart](https://ourworldindata.org/grapher/historical-gov-spending-gdp).
