### ISSUE TITLE
Indicator Upgrader Database Error

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#2824]
I've been having some issues with Indicator Upgrader running into DatabaseErrors in [this staging server](http://staging-site-gbd-risk/etl/wizard/indicator-upgrade). Refreshing doesn't seem to help.

**Comment by pabloarosado** [comment]
I just pushed a fix to the branch `gbd-risk` (it was just a query that was not properly working when only one dataset was passed). It should work now.

**Comment by lucasrodes** [comment]
@pabloarosado is this solved?
