### ISSUE TITLE
Raise a warning when `etl my_dataset` does not find any datasets

### ISSUE THREAD

**Issue by Marigold** [owid/etl#288]
A minor issue I have noticed a few times with etlis that, when it does not find any steps to be executed, it tells you "All datasets up to date!". But the same happens when the step you wrote does not exist at all. This can be problematic if you misspell a dataset (e.g. etl food-explorer instead of etl food_explorer) or a version (e.g. etl 2022-05-18/faostat_food_explorer instead of etl 2022-05-17/faostat_food_explorer) or something like that. It can also happen when you are working on a step that you have not yet included in the dag. Instead of doing this, the etl should say "Dataset not found".

**Comment by wcox13** [comment]
https://github.com/owid/etl/pull/291
