### ISSUE TITLE
chart-diff: there is some chart-leakage

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2880]
## One-liner
After working on your PR for some time, if you check the chart-diffs, there might be some charts that are unknown to you. These seem to come from some inaccurate comparison between server database tables.

## Things that lead to different charts

- **Different config**. This works all the time
- **Different data**. Mostly working
- **Different metadata**. ⚠️ Has spurious differences

## Context & details

After some days of working on your PR, some chart-diffs appear hidden in chart-diff app. These are ignored by @owidbot, and are not shown by default, so not critical. Most of the charts appear to be tagged with labels `metadata change` or `data change`.

Examples
- PR https://github.com/owid/etl/pull/2861, with chart-diff available [here](http://staging-site-refactor-chartsync/etl/wizard/?page=chart-diff&show_all=).
- PR https://github.com/owid/etl/pull/2867, chart-diff available [here](http://staging-site-happiness-ages/etl/wizard/chart-diff)
- PR https://github.com/owid/etl/pull/2872, chart-diff available [here](http://staging-site-ghe-performance/etl/wizard/chart-diff?show_all=)

## Problems

- Some datasets are different every time you build them (i.e. they are daily)
  - This means they will always appear in the difference

**Comment by Marigold** [comment]
@lucasrodes I'm on it. I know where is this coming from. I'll rethink how `modified_charts_by_admin` works and split it into two parts - chart config updates and data/metadata updates.

**Comment by larsyencken** [comment]
## From discussion

- We should fix cases where the date in the metadata is dynamic, and take it from the snapshot instead
- If that solves the problem, we stop there

**Comment by larsyencken** [comment]
@Marigold to check it out and see if we can just blacklist non-deterministic datasets from the diff

**Comment by larsyencken** [comment]
From discussion, we understand this to be less of a problem now, but we're a bit unclear on the current situation.

@Marigold Can you double-check if we still need this issue?

**Comment by Marigold** [comment]
We're seeing way less spurious differences for data & metadata changes after blacklisting some datasets. We'd still see differences if PR is out of date with master, but that's expected and merging should always fix that.

(We used to merge with master automatically on staging server, but it was problematic for other reasons, like automatically updating after regions change, etc. It could be worth revisiting in the future, though.)
