### ISSUE TITLE
Add `--verbose` mode to `etl` command

### ISSUE THREAD

**Issue by Marigold** [owid/etl#292]
We're making spelling mistakes quite often when calling the DAG using `etl mystep` and what we often get back is just `All datasets are up to date` without knowing what's going on under the hood. This is hard to debug. This got recently improved with [raising error when no steps are found](https://github.com/owid/etl/pull/291), but I was thinking that maybe having `--verbose/-v` flag logging what steps are already completed (and perhaps other info) could be useful.

**Comment by Marigold** [comment]
@wcox13 do you think this would be useful or would it be just adding useless code to our codebase?

**Comment by wcox13** [comment]
what exactly would be the new info/format here? i thought we already had some output describing which steps are run

maybe which steps are up to date / not run?

**Comment by wcox13** [comment]
oh sry, just reread— i just suggested what you wrote already

i think no harm in adding useful logging. does it need to be under a verbose flag? could just have it on by default, i don’t think one line per step would be too noisy. but either way works

**Comment by Marigold** [comment]
Thanks, you're right in that there's no harm, but also probably not much to gain... So low priority, anyway, leaving this open if we come up with something more interesting to log.
