### ISSUE TITLE
Walkthrough - improvements

### ISSUE THREAD

**Issue by Marigold** [owid/etl#294]
Suggested improvements of walkthrough from this [Slack thread](https://owid.slack.com/archives/C0193RW5E2J/p1658143999235099):

**Initial list of issues:**
* [ ] And I'd say that, before creating those files (especially the *.py), it should check if a file already exists. Otherwise it's currently overwriting it.
* [x] Why having a validate script? I think it would be better if those validations were already at the end of the meadow step. Additionally, if you think a separate validate script is better, I’d suggest to use .py instead of .ipynb.
* [ ] add buttons for a few of the functions to execute stuff - this way you could stay a bit more in the tool itself and only switch over to the terminal or VS code (which might also be opened with a button?
* [ ] I think ingest script should be expected to work not just once, but also for future releases of the data. So I think that it would be better to not hardcode dates in the metadata file. We could have some kind of tags for years and dates?
* [x] I get a `Dataset not found in Walden, did you upload it?` However the walden index file already exists in the submodule and the file is already in s3, so does it need to be merged to master?
  * could not reproduce
* [x] And a final note: there are many ways to misspell "walkthrough". Maybe calling it "guide" will be appreciated by our future selves?

@pabloarosado:
* [x] "Afghanistan" should not be by default in the mapping, because a dataset may not include it (I just found one example). Maybe it should be just empty.
* [x] Although I like the name "Excludistan", I guess it should not be there, and the list of excluded countries should also be empty (otherwise after a while the etl may end up having many instances of "Excludistan").
* [x] We already have a `geo.harmonize_countries` function in datautils. Maybe that should be used by default (we know that we have to improve it, but it is still better than the default code you have added to the garden steps).

@Marigold:
* [x] I've noticed that the walkthrough script creates a countries file named institution.country_mapping.json, but shouldn't it be institution.countries.json? I guess it doesn't really matter, but I though the latter was sort of accepted
* [x] I'd suggest to remove all instances of ggdc names and URLs. Using "dummy" is probably a better idea.
* [x] question about the .meta.yml file generated in the garden step. I see that the template contains some fields which I believe to be used in grapher only. Shouldn’t this be in the grapher step instead? Field `entityAnnotationsMap` for instance
* [x] add variable matching to grapher walkthrough, see [this file for an inspiration](https://github.com/owid/etl/pull/324/files#diff-cbf288226b30062782ecd9b21a622abf2e040d70235d158ea8dbba685a5ea542)
  * #690
  * #706
* [x] rename "walkthrough" to "wizard" because it's cool
* [x] My only suggestion would be to avoid real information in dummy: For example, instead of citing "Maddison ..." it could just be "Template dataset..." or something like that. Otherwise we may, by mistake, have a reference to the GGDC in a dataset that has nothing to do with it. Also, having such a complete country mapping could lead to confusion, and a data manager could believe that they already have harmonized countries.

@pabloarosado 
* [x] Improve format of code. In particular, add more well-written comments. My proposed standard would be: "A visitor who doesn't know Python wants to roughly understand what's done to the data".
* [x] Add version as another field (which by default would be the current date).
* [x] Remove examples from GGDC. I think it would help to have all metadata fields included, with a brief explanation and a fake example.
* [x] Change order of fields in web form (e.g. namespace should always appear first).
* [x] Auto-generated ingest scripts should be created inside institution/version folders.
* [x] Auto-generate metadata template with all variables' metadata (or this may be a separate tool to walkthrough).

@pabloarosado 2023-08-17
* [x] Dropdown of yaml files, to be able to choose the one to write to (instead of the default walkthrough.yml, which no one should use).
* [x] Remove the “Generate playground” (does anybody use it?).
* [x] Minor rewording (and possibly coloring?) of the description of fields in snapshot. For example the “Version” field could be confusing.
* [x] Use owid.catalog.processing functions and assume metadata propagation.
* [x] Use `create_dataset` without `default_metadata`, and use check_... = True, to ensure all variables have metadata.
* [ ] Add checkboxes to optionally include countries and excluded countries files.

_Note: items to the list have been added based on discussion in this thread_

**Comment by pabloarosado** [comment]
A few more things I'd add (if you agree):
[ ] "Afghanistan" should not be by default in the mapping, because a dataset may not include it (I just found one example). Maybe it should be just empty.
[ ] Although I like the name "Excludistan", I guess it should not be there, and the list of excluded countries should also be empty (otherwise after a while the etl may end up having many instances of "Excludistan").
[ ] We already have a `geo.harmonize_countries` function in datautils. Maybe that should be used by default (we know that we have to improve it, but it is still better than the default code you have added to the garden steps).

**Comment by Marigold** [comment]
* [ ] I'd suggest to remove all instances of ggdc names and URLs. Using "dummy" is probably a better idea.

**Comment by Marigold** [comment]
* [ ] add variable matching to grapher walkthrough, see [this file for an inspiration](https://github.com/owid/etl/pull/324/files#diff-cbf288226b30062782ecd9b21a622abf2e040d70235d158ea8dbba685a5ea542)

**Comment by Marigold** [comment]
* [ ] rename "walkthrough" to "wizard" because it's cool

**Comment by Marigold** [comment]
* [ ] My only suggestion would be to avoid real information in dummy: For example, instead of citing "Maddison ..." it could just be "Template dataset..." or something like that. Otherwise we may, by mistake, have a reference to the GGDC in a dataset that has nothing to do with it. Also, having such a complete country mapping could lead to confusion, and a data manager could believe that they already have harmonized countries.

**Comment by pabloarosado** [comment]
I would really appreciate these improvements. In fact I'm happy to implement some of them, whenever I have some time. Here are some more:
* [ ] Improve format of code. In particular, add more well-written comments. My proposed standard would be: "A visitor who doesn't know Python wants to roughly understand what's done to the data".
* [ ] Add version as another field (which by default would be the current date).
* [ ] Remove examples from GGDC. I think it would help to have all .
* [ ] Change order of fields in web form (e.g. namespace should always appear first).
* [ ] Auto-generated ingest scripts should be created inside institution/version folders.
* [ ] Web form could include what dag file to use (or create a new one). This may be more complicated.
* [ ] Auto-generate metadata template with all variables' metadata (or this may be a separate tool to walkthrough).

**Comment by Marigold** [comment]
@pabloarosado great suggestions, thanks! This is a good time for me to do these improvements as I'm starting work on "Fasttrack ETL" which should be a replacement for admin dataset uploader similar to walkthrough.

I'll do the easy ones asap and leave comments for the rest.

>  Remove examples from GGDC. I think it would help to have all

Not sure I follow

>  Web form could include what dag file to use (or create a new one). This may be more complicated.

Users are supposed to move dag lines from `dag_walkthrough.yml` to either `dag.yml` or somewhere else. Editing YAML files programatically (that have been previously edited manually) is a pain. I don't think this is worth it.

> Improve format of code. In particular, add more well-written comments. My proposed standard would be: "A visitor who doesn't know Python wants to roughly understand what's done to the data".

Please contribute if you already have some ideas! Ironically you're using walkthrough much more than I do, so if anyone knows what's missing, it's you.

Others are WIP.

**Comment by pabloarosado** [comment]
Hey @Marigold sorry I left one of the points unfinished! The one about "Remove examples from GGDC". I have updated it now.
If you think some of my suggestions are not doable, that's fine.
And yes, I want to work on that at some point, as soon as I find some time. In the meantime, whatever other improvements you make would be appreciated!

**Comment by lucasrodes** [comment]
> add variable matching to grapher walkthrough, see [this file for an inspiration](https://github.com/owid/etl/pull/324/files#diff-cbf288226b30062782ecd9b21a622abf2e040d70235d158ea8dbba685a5ea542)

I have added this in https://github.com/owid/etl/pull/690 and https://github.com/owid/etl/pull/706

**Comment by paarriagadap** [comment]
Hi! Maybe a small improvement can be

- [ ]  When **Import dataset from local file** is selected in `walkthrough snapshots` the instructions after submitting should include how to upload the local dataset.

I mean, something like:
```
Upload the local dataset by using
python snapshots/lis/2023-01-18/luxembourg_income_study_keyvars.py --skip-upload --path-to-file **relative path of file**
```

Right now the steps are shown considering the regular case.

**Comment by lucasrodes** [comment]
Closing this in favour of  https://github.com/owid/etl/issues/new?assignees=marigold%2Clucasrodes&labels=wizard%2Cwalkthrough&projects=&template=4-walkthrough-issue---.md&title=%5Bwizard+or+walkthrough%5D%3A+meaningful+title+for+the+issue
