### ISSUE TITLE
Automate PR creation when updating steps

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2999]
Our [guide](https://docs.owid.io/projects/etl/guides/data-work/update-data/) for updating data suggests creating _reference_ and _review_ branches as best practice. We already use `etl d draft-pr` command which has proven to be handy for automatic PR creation. We could do similar automation for updating data:

1. Create reference branch
2. Update steps (by using functions from ETL dashboard)
3. Commit new steps and push reference branch to Github
4. Create a review branch with PR

@lucasrodes suggested
> Maybe, we want to add that when updating the steps in ETL Dashboard? E.g a checkbox or something ‘create reference and review branches’. Title and name of the branch could be dynamically generated based on the datasets selected for update (edited) 

@pabloarosado suggested
> I don't think all that can easily be done automatically (because step 2. can get a bit tricky). But maybe there's a better way around it.

It'd make sense to at least create reference & review branches automatically, and then see whether it's worth automating the rest. Leveraging `etl d draft-pr` could make it relatively easy.

**Comment by lucasrodes** [comment]
One minor thing: I'd rename the command to something shorter, so it is easier to adopt for the team.

From the top of my head, I'm thinking `etl pr`, but I'm open to suggestions.

**Comment by larsyencken** [comment]
We discussed that you can suggest to review a subset of commits, to make the review more relevant.

**Comment by pabloarosado** [comment]
> We discussed that you can suggest to review a subset of commits, to make the review more relevant.

Yes, Lars suggested an alternative to creating a reference branch and a subbranch. You can simply create a PR that attempts to merge a branch to master. Then, on the upper left corner, you can choose which commits to consider when reviewing. You can skip the commit(s) that duplicated old code. Once you select the ones you want to consider, we can copy that URL and add it to the description of the PR, to point the reviewer to a more convenient view of the changes.

![Screenshot 2024-07-25 at 12 06 08](https://github.com/user-attachments/assets/3ca7407a-edf7-4b93-8452-97aa158bdb73)

I haven't tried this workflow yet, but it looks promising. If it works well, we can avoid creating a reference branch (and of course it's corresponding staging server). I'll try it out and update the docs accordingly.

**Comment by Marigold** [comment]
Closing. We tried to automate it, but the process is often too complex and automation hurts rather than helps.
