### ISSUE TITLE
catalog: support more methods

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#3009]
Some methods are currently not supported for Table, Variable, etc. For such cases, we need to convert Tables to DataFrames, and then come back to the 'Table' world and ensure no metadata is lost.

### List of methods (wip)

- [x] `VariableGroupBy.rolling`
- [x] `TableGroupBy.rolling`

#### VariableGroupBy.rolling

```py
tb = Table(pd.DataFrame({
    "country": [1, 1, 2, 2, 3, 3],
    "value": [4,5,6,7,8,9]
}))

tb.groupby("country")['value'].rolling(7)
```
Error: `NotImplementedError: `

#### TableGroupBy.rolling

```py
tb = Table(pd.DataFrame({
    "country": [1, 1, 2, 2, 3, 3],
    "value": [4,5,6,7,8,9]
}))

tb.groupby("country")[['value']].rolling(7)
```

Error: `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.`

**Comment by lucasrodes** [comment]
I just thought maybe we want to have a function `dframe` which we could use with context managers:

```python
with dframe(tb) as df:
    df = some_ops(df)
```

something along those lines, that converts `tb` into a `DataFrame` and on exit it should try to (i) convert `df` back to a `Table` and bring the 'lost' metadata back.

**Comment by lucasrodes** [comment]
After talking with Pablo, my understanding is that the current recommended way of doing the 'Table →  DataFrame → Table' hack would be:

```python
df = pd.DataFrame(tb)

df = some_operations(df)

tb = Table(df).copy_metadata(tb)
```

**Comment by pabloarosado** [comment]
Operation `pd.to_numeric` does not propagate metadata, and it's quite useful (see, e.g. [this discussion](https://owid.slack.com/archives/C46U9LXRR/p1721826020112659)).

**Comment by Marigold** [comment]
We could create a decorator for functions working with dataframes & series that would preserve metadata. Something like this
```python
from typing import Callable, Any

def keep_metadata(func: Callable[..., pd.DataFrame | pd.Series]) -> Callable[..., Table | Variable]:
    def wrapper(*args: Any, **kwargs: Any) -> Table | Variable:
        tb = args[0]
        df = func(*args, **kwargs)
        if isinstance(df, pd.Series):
            return Variable(df, name=tb.name, metadata=tb.metadata)
        elif isinstance(df, pd.DataFrame):
            return Table(df).copy_metadata(tb)
        else:
            raise ValueError(f"Unexpected return type: {type(df)}")
    return wrapper


@keep_metadata
def rolling_mean(df: pd.DataFrame) -> pd.DataFrame:
    return df.rolling(window=1).mean()

# create sample table
df = pd.DataFrame({
    "a": ['1','2','3']
})
tb = Table(df)
tb.a.m.title = 'my variable'

# use pd.to_numeric while preserving metadata
tb.a = keep_metadata(pd.to_numeric)(tb.a)
assert tb.a.m.title == 'my variable'

# apply a function that only works on dataframes
tb = rolling_mean(tb)
assert tb.a.m.title == 'my variable'
```

**Comment by Marigold** [comment]
All suggestions from above comments were implemented. Should we keep this as a tracking issue?

**Comment by pabloarosado** [comment]
> All suggestions from above comments were implemented. Should we keep this as a tracking issue or close?

Thanks! The likelihood of having such missing methods is going to be smaller and smaller over time, so maybe it's better to close it and open other issues if needed. But I also don't mind having it as a tracking issue, if you prefer.
