### ISSUE TITLE
Fix `yearIsDay` in backporting

### ISSUE THREAD

**Issue by Marigold** [owid/etl#302]
Since we only have a `year` column in grapher DB, daily data had to be hacked by using special property `display.yearIsDay` which means year is not actually year, but number of days since 2020-01-21 (here's a [sample conversion code](https://github.com/owid/co2-data/blob/master/scripts/utils.py#L73)). Should we fix it when backporting datasets?

**Comment by Marigold** [comment]
Should we do something about `display.conversionFactor` too?

**Comment by larsyencken** [comment]
Yeah, our existing code in `owid-grapher-py` that fetches data from the site does this coversion, I think we should escape year-is-day as fast as possible: https://github.com/owid/owid-grapher-py/blob/master/owid/site/__init__.py#L68

If possible, we could also go with a typed pandas column for it, but really a string is fine too. It would be tempting to rename the column name to `date` in this case.

**Comment by larsyencken** [comment]
I'm unsure about `display.conversionFactor`, we could add it to the column metadata for now.
