### ISSUE TITLE
Broken link and sample YAML code for example DVC file on fur laws data in ETL docs

### ISSUE THREAD

**Issue by spiros** [owid/etl#3096]
### One-liner
Broken link and sample YAML code for example DVC file on fur laws data in ETL docs

### Context & details
The link for the sample DVC file referenced in https://docs.owid.io/projects/etl/architecture/workflow/#snapshot was broken.
This [PR](https://github.com/owid/etl/pull/3095) updates both link and YAML code.

**Comment by lucasrodes** [comment]
Thanks @spiros! Merged, fixed and should be live in short.
