### ISSUE TITLE
Dataset metadata should match its path

### ISSUE THREAD

**Issue by Marigold** [owid/etl#311]
Dataset `garden/bp/2022-07-11/energy_mix/bp_energy_mix__bp_2021` currently has `Dataset.version == 2021`. Having different version in dataset and in path (`2022-07-11`) is confusing. We should probably raise an error if dataset version doesn't match version from path (same for namespace and short_name).

Perhaps we could also assign it implicitly? Or create a helper function `Dataset.create_from_path` (using [paths](https://github.com/owid/etl/blob/9ff5277f8b78d9cb238996d2524db88d51ec4fdf/etl/steps/data/meadow/un_sdg/2022-07-07/un_sdg.py#L17))?

There are also some datasets with missing version (`garden/faostat/2021-04-09/faostat_fbsc/bulk`), namespace, etc. So make sure we fix them before enforcing everything.

**Comment by Marigold** [comment]
Datasets with missing versions:
- [ ] garden/faostat/2021-04-09/faostat_fbsc/bulk
- [ ] garden/faostat/2021-04-09/faostat_fbsc/meta_fbs_element
- [ ] garden/faostat/2021-04-09/faostat_fbsc/meta_item

**Comment by larsyencken** [comment]
Sounds like something like this is going on:

````
ds = Dataset.create_empty(path)    # <-- implicit version in the path
update_metadata_from_walden(ds, walden_ds)   # <-- overwrite the version
ds.add(t)
```

Maybe when you update the metadata, it should fail if the version you set is not in the path?

Probably this logic should live in the ETL, not in `owid-catalog`, so maybe we could extend `Dataset` with a `LocalDataset` class that does this validation.

**Comment by Marigold** [comment]
Reopening, this could result in painful bug. Should be one-liner.

**Comment by larsyencken** [comment]
@Marigold As a reminder, you can label issues as "pinned" and then they won't get garbage collected.

**Comment by Marigold** [comment]
I didn't find any version mismatch and the extra code is not worth it. There are weird edge cases with automatic covid updates, missing versions that are then assigned publication date, etc.

**Comment by larsyencken** [comment]
Cool, retagging as "wontfix"
