### ISSUE TITLE
wizard: zeroDay new behaviour causing unexpected behaviour in Explore Mode

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#3125]
### One-liner

`zeroDay` set automatically is causing unexpected behaviour in _Explore mode_ in **Indicator Upgrader**.

### Context & details
Recently, there were some ergonomic improvements for data pipelines that use `date` instead of year (I think [here](https://github.com/owid/etl/pull/3083), probably?).

I was comparing indicator [grapher/covid/latest/vaccinations/vaccinations#total_vaccinations](http://staging-site-covid-vax/admin/variables/738594) (old) with [grapher/covid/latest/vaccinations_global/vaccinations_global#total_vaccinations](http://staging-site-covid-vax/admin/variables/984968) (new), which should be rather similar. However, I was getting unexpected error values.

<img width="732" alt="image" src="https://github.com/user-attachments/assets/5f9e8014-2551-4164-83c9-bd9beace3ea9">

This is causing the underlying hardcoded 'year' column to miss-match between indicators.

**Explore mode** is very helpful to make sure that the timeseries of two indicators match approximately. We should make sure that it is also reliable when using `date` columns. We probably need to convert '`year`' to an actual date using the `zeroDay` value of both indicator. Only then we can align the time-series.

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/pull/3137. Please reopen if this appears again.
