### ISSUE TITLE
bug: edit links in staging servers link to `staging-site-master`

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#3157]
### One-liner
If I click on the edit button of a chart from the live site on a staging server, I am redirected to the staging-site-master edit pane.

### Context & details

Reproduce:
- Go to http://staging-site-covid-explorer/grapher/daily-covid-vaccination-doses-per-capita
- Click on share → Edit
   ![image](https://github.com/user-attachments/assets/5245e193-df5b-4e6c-8cd3-6feba4fd95fc)
- The edit page is under `staging-site-master`.

This can lead to accidental chart edits on `staging-site-master`, which can then lead to unexpected behaviours in other etl tools.

**Comment by Marigold** [comment]
@lucasrodes I _think_ I fixed it. The thing is that your server was the only one where I could replicate it. Let me know if you see it again, please.
