### ISSUE TITLE
Include version in dataset name when importing to grapher

### ISSUE THREAD

**Issue by Marigold** [owid/etl#316]
## Problem

> I think I've noticed a reason why we should include the year in the short name: when running the grapher step, the name of the new dataset created in the admin is simply `statistical_review`, which, next time we update it, will overwrite the previous. So I suppose we always have to add the version in the short name

## Solution

When importing to grapher, save dataset with name `[dataset.short_name]__[dataset.version]` instead of just `[dataset.short_name]`. We could include namespace too, but perhaps it's too much?

We could also just warn users (or raise an error) when their dataset's name does not contain version.

@larsyencken what do you think? We'd better do it before Fiona and Lucas finish their grapher steps.

**Comment by larsyencken** [comment]
Sure, we can do that. But a dataset `name` is more like what we'd call a
`title` in the ETL metadata. We should still add the `short_name` and
`version` fields to the dataset model itself, and start populating them
when we export from the ETL. Presumably we'll need this information to
query the API later, when we don't have data values in MySQL.

**Comment by Marigold** [comment]
Right, having proper MySQL model nicely mapping to ETL would be better than hacking it like that. Besides, Pablo has [already taken care](https://github.com/owid/etl/pull/320/files#diff-ceffd10beab88807e12da7ce17f2c226aac6a76b6fef602fecc076070f2b42abR363) of good short name.
