### ISSUE TITLE
chart-diff: does not work correctly for draft charts

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3275]
## Problem

The chart diff flow hasn't been designed for draft charts, so lingering draft charts can cause it to crash.

## Expected behaviour

Draft charts should also be queued for approval, like other charts.

## Workaround

We currently ignore draft charts in the chart diff.

**Comment by larsyencken** [comment]
We triaged this as "important" since you might expect that your work as draft charts would be shipped, but instead you could lose that work after merging.

**Comment by Marigold** [comment]
Draft charts now work just like normal charts.
