### ISSUE TITLE
:sparkles: enhance `dataset.read_table(...)` method with type normalisation

### ISSUE THREAD

**Issue by Marigold** [owid/etl#3277]
## Motivation

Historically, we've been using function `dataset["my_table"]` to access table from a dataset. Recently, a new helper method `dataset.read_table(reset_index: bool = False)` has been added that lets us read the table with reset index which is significantly faster for large dimensional datasets.

## Concept

We could add more functionality to `read_table` and make it de facto standard to read tables. These could be:
- Retype all columns to "standard" types (e.g. `uint8 -> int64`, `Float16 -> float64`) and categorical to `string` type
- ~~underscore column names etc. (see `.format` method)~~
  - Should already be in snake case by the time we're talking tables

**Comment by larsyencken** [comment]
We think type standardising would remove some common footguns for data folk:

- `categorical` → `string`
- `Float*` -> `Float64`
- `Int*` -> `Int64`
