### ISSUE TITLE
chart-diff: sort order in chart is not synced to admin

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#3285]
### One-liner
After editing a chart on a PR staging serve and merging the PR, the `Sort Order` property is lost.

![image](https://github.com/user-attachments/assets/d4e281c7-13f5-4ff4-965f-65e64c1f85cf)

### Context & details
I was working on https://github.com/owid/etl/pull/3280, where I migrated four charts. These charts were synced with PROD, but the sorting was lost.

I wonder if this happens during the chart-sync phase?

**Comment by Marigold** [comment]
Should be fixed by https://github.com/owid/etl/pull/3292
