### ISSUE TITLE
Co-publish data in multiple formats (csv, feather, parquet)

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#332]
## Background

We want to make it easy to browse our data and get it in a variety of formats. Today the ETL publishes the dataset it generates through the `publish` command. Each ETL step itself decides on what format to use at the moment the table is added to the dataset: [`Dataset.add(table)`](https://github.com/owid/owid-catalog-py/blob/574dc31457ca0d5c6790446d2ed8e164143e259e/owid/catalog/datasets.py#L65). Current options are `csv` (for explorers) or `feather`.

## Proposal

We should pick a set of formats (csv, feather, parquet) and generate the data in _all those formats_, rather than picking one.

```mermaid
graph LR
etl[ETL step] --> memory[in-memory]
memory --> csv
memory --> feather
memory --> parquet
csv --> s3
feather --> s3
parquet --> s3
```

### Upsides

- Consistency between all our published datasets, no need to remember what format the data was in
- Faster development and prototyping for us, since we can always find a format that a new client can use
  - New API can more easily consume parquet files

### Downsides

- BIG on-disk footprint, especially due to CSV files (~10x? 5G -> 50G?)
- Slower ETL due to extra format generation
- Slower `publish` step due to more files to sync to S3

## Scope

- [x] https://github.com/owid/owid-catalog-py/pull/53
- [ ] https://github.com/owid/etl/pull/344
- [ ] https://github.com/owid/owid-catalog-py/pull/55

**Comment by larsyencken** [comment]
@Marigold @danyx23 Thoughts? 🙂

**Comment by Marigold** [comment]
@danyx23 suggested the same thing yesterday. I wouldn't rush with publishing `.csv` files because of their size (gzipped possibly, but honestly I'm not sure who would be consumer since you can read from URL with `pd.read_feather`).

Related issues / PRs:
* https://github.com/owid/owid-catalog-py/pull/37
* https://github.com/owid/etl/issues/30

**Comment by larsyencken** [comment]
Oh, the consumer for `.csv` would be the browsable data catalog, since there's a lot of folk being very productive in the spreadsheet world. That would be the reason for trying to render to CSV as well.

**Comment by Marigold** [comment]
Oh, obviously, I totally forget about them. Then gzipped csv could be useful (I think that uncompressed csv would be enormously large in some cases and users wouldn't want to download uncompressed content anyway)
