### ISSUE TITLE
Deprecate sources in favour of origins

### ISSUE THREAD

**Issue by Marigold** [owid/etl#3331]
## Problem

Maintaining both sources and origins is cumbersome. Migrating all sources to origins would allow us to deprecate a significant amount of code in both ETL and Grapher, potentially speeding up the process. We've already migrated the most critical datasets to origins and are currently migrating the rest as needed. However, a one-time full migration might be more efficient.

### Full migration to origins in snapshots

This would involve migrating all sources in snapshots to origins. We’d need to devise an automatic source-to-origin transformation and modify all steps to use `Table` instead of `DataFrame` to ensure proper origin propagation.

### Adding origins to YAML files

For all garden and grapher datasets, we could extract sources, automatically migrate them to origins, and add them to the metadata YAML files (potentially as `*.meta.override.yml`).

## TODO
- [x] How many (unarchived) datasets still use sources?

**Comment by larsyencken** [comment]
It would be good to understand the size of the migration needed to work out if it's worthwhile now.

**Comment by Marigold** [comment]
Searching for `sources:` in YAML files returned 193 results in 121 files (for active steps). This would entail rewrite of snapshots, metadata, etc... totally not worth it, given that sources haven't been causing problems recently.
