### ISSUE TITLE
Add an anomaly detection for standalone indicators

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3370]
## Overview

Using ChatGPT or another method, create an online method for detecting notable outliers or potential data errors.

## Prior art

See the "Find interesting views" tab of the [ETL Insighter](https://etl.owid.io/wizard/insighter), which truncates an indicator to the last 20 years and feeds the data plus a prompt to ChatGPT 4o.

## Challenges

- The 128k context window is not enough to put the entire data series in
  - You could pass the data file for use with code interpreter (likely worse results)
  - You could truncate the data (e.g. last 20 years)
  - You could split the data into multiple chunks, and do detection on each chunk
  - You could thumbnail subsets of the data, and do detection based on thumbnails

**Comment by lucasrodes** [comment]
@Marigold, I'd say that this is completed, right?

Feel free to re-open this if you think it should remain open.

Improvements and enhancements can be shared at https://github.com/owid/etl/issues/3436.
