### ISSUE TITLE
Indicator upgrader doesn't work on a particular dataset

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#3384]
I'm trying to use [this dataset](https://admin.owid.io/admin/datasets/6737) in Indicator Upgrader; it only has one draft chart, which is expected. When I run Indicator Upgrader, it says this:

![Image](https://github.com/user-attachments/assets/1bb2b706-bf15-4af0-8905-06120f2fe7f8)

I guess it might be failing as that dataset is from fast track, or because there's only one draft chart?

**Comment by larsyencken** [comment]
Thanks for reporting @spoonerf! We're unclear if this will still be happening after other recent changes, but if it pops up again please let us know and we can get it fixed.
