### ISSUE TITLE
Create script to suggest chart revisions

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#339]
Recently, the scripts to create chart revisions was copied from importers to etl. However, currently, `etl/chart_revision_suggester.py` is not a script. We need to generalise it to simply load a variable mapping and suggest the chart revisions.
For example, the variable mapping json file currently needs to be stored inside the data set, in a `config/variable_replacements.json` file. But we don't need to store this file (especially because the mappings are different in a local grapher, or staging, or live.

Optionally, `match_variables_from_two_versions_of_a_dataset.py` and `chart_revision_suggester.py` could be both executed by the same script.

**Comment by larsyencken** [comment]
Cool! Just wondering where it should live. If it uses some special ETL sauce, then the ETL is the right place. If it's about managing grapher charts and doesn't need the ETL, since it's a publication management tool more than a data management tool.

**Comment by pabloarosado** [comment]
It's very convenient to have it in the etl repos, when working on grapher steps. For example, right now I have to work both with etl and importers to create revisions. This means that I always have to ensure that both repos have the right credentials (of local, staging, or live grapher). Given that we already have some `grapher_*` modules, it could become just another one, e.g. `grapher_suggest_chart_revisions.py`.
In fact they have already been used in [some grapher steps](https://github.com/owid/etl/blob/master/etl/steps/grapher/un_sdg/2022-07-07/match_vars_crs.py).

**Comment by lucasrodes** [comment]
@pabloarosado, the first version is available from https://github.com/owid/etl/pull/494 (command `etl-chart-suggester`).

In its first form, it is a very hacky version. For E.g. some of the input arguments shouldn't be necessary (name of the dataset, version, etc.).
