### ISSUE TITLE
Newly imported dataset is archived

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#340]
I've recently imported the new UN SDG dataset, however immediately after import it appears to be archived. I've had this issue on both staging and on live:
![Screenshot 2022-07-29 at 15 42 28](https://user-images.githubusercontent.com/10774728/181784428-8ac3e872-0c7f-4752-bab2-fb637f4d20e2.png)

Possibly related - I recently archived the un_sdg_2019 namespace with this `mysql` command `update namespaces set isArchived = true where name='un_sdg_2019';`

**Comment by larsyencken** [comment]
My thinking here is that the archiving should probably be happening on the `dataset` level, not the `namespace` level, since in our new data model we reuse the namespace for a long time and have different versions.

**Comment by spoonerf** [comment]
That makes sense - I have manually unarchived the `un_sdg_2019` namespace now with `update namespaces set isArchived = false  where name='un_sdg_2019';`.

I'll archive the relevant datasets instead.
