### ISSUE TITLE
Bug in walkthrough meadow

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#343]
When running `walkthrough meadow` I enter the right namespace, dataset short name and version, and untick the option to create a metadata file. However, when I submit, I get an error saying that the metadata file is not found.
![Screen Shot 2022-08-01 at 10 53 14](https://user-images.githubusercontent.com/12246978/182111533-2b49de6b-2d3f-4751-bfb3-63d422f0e8fc.png)

By the way, I think that the version of the walden dataset and the meadow step should be different things. For example, you may want to create a meadow step for an old walden dataset, and you don't want the version of the meadow step to be as old as the walden dataset version.

**Comment by Marigold** [comment]
> For example, you may want to create a meadow step for an old walden dataset, and you don't want the version of the meadow step to be as old as the walden dataset version.

Thanks Pablo, that makes sense. I'll see how can I relax that requirement.
