### ISSUE TITLE
Reindex after each ETL run or step

### ISSUE THREAD

**Issue by Marigold** [owid/etl#346]
## Problem

Users of ETL are forgetting about calling `reindex` after running `etl` command and are then wondering why doesn't their dataset appear in `LocalCatalog`. It happens to me quite often - debugging something and then realising I forgot to reindex.

## Solution

`reindex` command has `--include` flag that only reindex folders matching the pattern (we're using it in `fasttrack`). We could either bulk reindex at the end of each etl run or reindex every dataset as it's built.

**Comment by larsyencken** [comment]
The alternative to always reindexing is to have `LocalCatalog` just lazily walk the directory tree on demand, that's also a strategy that can never go out of date.

**Comment by Marigold** [comment]
Not sure I get what you mean, could you be more specific? (reindexing everything currently takes ~88s and everything lazy I can imagine would be impractical)
