### ISSUE TITLE
chart-diff: Getting 'UNKNOWN -- REPORT THIS' flag in a chart-diff session

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#3484]
This is the chart-diff session: http://staging-site-unodc-2024/etl/wizard/chart-diff?show_all=

The charts didn't come up unless I selected 'Show all charts', so maybe something weird is going on?
![Image](https://github.com/user-attachments/assets/c2eebc3c-24a1-4744-bdd6-d24e166b1bb0)

**Comment by Marigold** [comment]
Thanks for reporting this @spoonerf, it was indeed an UI bug. Could you please merge with master and try again?

**Comment by spoonerf** [comment]
Thanks @Marigold, that worked! I'll close this now.
