### ISSUE TITLE
Production ETL script does not run to completion

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#350]
## Problem

Server logs show that the production ETL script `prod-etl.sh` commonly does not run to completion.

## Diagnosis

The script runs until it hits a line like `git commit -m 'blah'`, but when there are no changes to commit, git gives a non-zero error code. Since the script is being run with `#!/bin/bash -e`, the script stops there.

## Proposed solution

1. Refactor the script to give clearer output
2. Guard all git commit statements with `my_statement || true` so they do not cause the script to halt

**Comment by Marigold** [comment]
I created a duplicate [issue](https://github.com/owid/analytics/issues/50) before seeing this one (with a dumb [hotfix](https://github.com/owid/analytics/pull/51)).

I see you've assigned yourself, thanks! My bash skills are not superhuman unfortunately, so feel free to close that PR and come up with something nicer.
