### ISSUE TITLE
anomalist: throws and error on UN SDG & is reeeeally slow

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#3506]
### ✅ Loading the SDG dataset fails on anomalist

When using the Anomalist on the latest UN SDG data it fails with the following error. Link [here](http://localhost:8053/anomalist?anomalist_datasets_selected=6761).

![Image](https://github.com/user-attachments/assets/850d9236-6916-459d-8fe8-e378a461f69c)

I suspect the issue might be to do with the very long indicator names we necessarily have in the dataset (there are a wide range of different dimensions which can be quite verbose). 

UPDATE (2024-11-07): @Marigold fixed the long indicator name problem

cc @antea04 as it might be useful to run the Anomalist on this dataset at some point, given the number of data issues you already found. 

### Anomalist is really slow on the UN SDG dataset

Mojmir noted that the SDG dataset is unusual in that it uses many small tables, whereas this would (probably) be faster on a few large tables.

We note that the step itself doesn't take a long time to run, so Anomalist should be able to handle it too.

**Comment by Marigold** [comment]
Thanks for reporting! I fixed the error in master, but another issue is that it takes ages for a dataset like this. I'm keeping this open until I look into its performance.

**Comment by Marigold** [comment]
@spoonerf so I finally fixed it and made it "fast" enough. UN SDG has 10000 variables, which complicates things "a little". The best way to try it out is to create a PR (or use `staging-site-fiona`) and make a change to recipe for UN SDG. Staging server recalculates anomalies for all changed steps, so you should see them after ~10 min in staging wizard.

**Comment by spoonerf** [comment]
Awesome, thanks v much @Marigold!
