### ISSUE TITLE
anomalist: Issue with duplicated index in Global Health Observatory means anomalist fails

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#3509]
Anomalist is throwing an error for [this dataset](http://localhost:8053/anomalist?anomalist_datasets_selected=6403), suggesting there is an indexing error, but the etl steps for this dataset run fine.

![Image](https://github.com/user-attachments/assets/ddb52e4c-7c66-420c-b34c-090ca7fee137)

This is totally not urgent; I'm just keen to try out the Anomalist on datasets I suspect have quite a few anomalies, namely GHO and UN SDG.

**Comment by Marigold** [comment]
I'll look into it asap. You couldn't have chosen smaller datasets, could you? 😅
