### ISSUE TITLE
lib/datautils: `groupby_agg` on string column with missing values introduces 0

### ISSUE THREAD

**Issue by jorisvandenbossche** [owid/etl#3515]
While running the tests with the next version of pandas, I ran into this case:

https://github.com/owid/etl/blob/f9e2f93e70e1ba38210cc51f900d1f92475ca45d/lib/datautils/tests/test_dataframes.py#L309-L329

where the expected result `df_out` column `"value_02"` is a mixed integer/string column, because of a zero being introduced through the groupby's `sum` on a group with only missing values.

While being tested as the expected result, I am wondering if this is the intended or desired behaviour to get a `0` in there (I assume this is not the case). Or whether this is just from using some dummy data in the test, and not something you encounter or want on the actual datasets? (for example, I don't know if you actually ever use the "sum" operation on a string column in practice)

The reason I ran into this case is because this test is failing with pandas' future string dtype enabled. It is failing because the result now no longer has an integer `0` but a string `"0"` (and hence the `assert equals(..)` failed), which I think is even worse (so I opened an upstream issue to fix this in pandas: https://github.com/pandas-dev/pandas/issues/60229, thanks to running your test suite!)

**Comment by larsyencken** [comment]
@pabloarosado will take a quick look, it may not be trivial for us to make a change to behaviour since it affects a bunch of our steps.

**Comment by Marigold** [comment]
It took me a while to understand what’s going on. Fortunately, this is dummy data and isn’t very representative of our typical use case. In fact, I’d say running `sum` on strings would generally be considered bad practice for us.

I’m closing this for now. If it gets fixed upstream, we’ll address it on our side. Thanks, Joris!
