### ISSUE TITLE
Signal users to create a PR in owid-content when creating explorers on staging servers

### ISSUE THREAD

**Issue by Marigold** [owid/etl#3534]
## Context

Until recently, staging servers used the `master` branch of `owid-content`, and this means any explorer work there was done directly on prod.

However, as of yesterday, each staging server uses its own branch of `owid-content`, matched to the ETL branch name. Edits in the admin, or running export steps, will commit to this branch.

## Problem

With the new behaviour, you need to remember to make a PR and merge your `owid-content` changes after you merge your ETL branch. However, you might forget and then your explorer changes will not go live.

Note that these branches are not garbage-collected, so your work will not be accidentally deleted.

## Proposal

Idea by @lucasrodes from https://github.com/owid/etl/pull/3307

> I was wondering if we should signal somewhere more prominently that the user needs to manually create a PR & merge their branch in owid-content. Maybe @owidbot?

> We could also programmatically create the PR in owid-content.

> Could also ping the user in Slack?

See [ETL docs](https://docs.owid.io/projects/etl/architecture/workflow/?h=creating+multi+dimensional+indicators#creating-explorers) how to work with explorers on staging.

**Comment by larsyencken** [comment]
From discussion, we think it would be plenty to add a comment post-merge when there were changes outstanding, with a one-click link to create a PR on `owid-content` against the right targets.
