### ISSUE TITLE
harmonize_ipython doesn't offer to export mapping of countries if no ambiguous countries are found

### ISSUE THREAD

**Issue by antea04** [owid/etl#3559]
#### One-liner:
The etl function harmonize_ipython (`from etl.harmonize import harmonize_ipython`) doesn't prompt the user to export its mapping of countries if no ambiguous countries are found.

#### Context:
While it is not strictly necessary to include countries which are already their "harmonized" version in the mapping, the default behaviour of the other harmonizing endpoints (cli, wizard) is to do it regardless. It avoids ambiguity and the etl warning of "these countries have been skipped in the harmonization mapping".  

I would like the ipython harmonization tool to do it as well and offer me this option, even if all countries can be automatically mapped.

#### Assignee:
I can try to do it in my next cooldown/ downtime, or @lucasrodes whenever he has time. It's in no way urgent.

**Comment by lucasrodes** [comment]
Thanks for proposing this, @antea04! It makes total sense.

If I understood you well, the harmonization process would output different mappings depending on whether you use CLI/Wizard or iPython. For the former methods, already standardized countries appear in the mapping (e.g. `"Latvia": "Latvia"`). But for the latter, this one would be omitted. Is this correct?

If so, I agree that all methods should output the same mappings.

If it helps, I did some quick checks, and some points:

The function `harmonize_ipython` makes calls to [run_automatic](https://github.com/owid/etl/blob/master/etl/harmonize.py#L312) and [run_interactive_ipython](https://github.com/owid/etl/blob/master/etl/harmonize.py#L424).

My intuition tells me that `run_interactive_ipython` is fine, and probably the source of the discrepancy (between ipython and cli/wizard) is the logic in `run_automatic`. All of them call `Harmonizer.run_automatic`, but differently:

---

**iPython**
[harmonizer.run_automatic(logging="ipython")](https://github.com/owid/etl/blob/master/etl/harmonize.py#L121)

**CLI**
[harmonizer.run_automatic(logging="shell")](https://github.com/owid/etl/blob/master/etl/harmonize.py#L92)

**Wizard**
[harmonizer.run_automatic()](https://github.com/owid/etl/blob/master/apps/wizard/app_pages/harmonizer.py#L191)
(this is equivalent to `logging=None`)

---


So, I think there's something with `run_automatic` when `logging="ipython"`. I quickly checked its code, but couldn't find anything obvious there.

I'd suggest adding `print` statements and keeping track of the value of `self.mapping` as you run the different steps.

**Comment by pabloarosado** [comment]
Thanks for reporting this @antea04, I've just encountered the same issue. I created [a quick PR](https://github.com/owid/etl/pull/3577) which solved it at least for my case.

**Comment by lucasrodes** [comment]
After thinking a bit more carefully, my intuition is that this issue _only_ appears if the user does not press any of the buttons "Export mapping". This is because the `export_mapping` call in [run_interactive_ipython](https://github.com/owid/etl/blob/master/etl/harmonize.py#L424) only occurs if the user does so.

So for instance, if _all_ countries are mapped automatically, nothing gets exported.
