### ISSUE TITLE
Add support for upserting different sources with the same `name`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#358]
## Problem

For the `un_sdg` dataset we need sources with different descriptions, but same name. For instance

```
Source(name='World Bank', description='Further information available at: https://unstats.un.org/sdgs/metadata/files/Metadata-17-03-02.pdf', ...)
Source(name='World Bank', description='Further information available at: https://unstats.un.org/sdgs/metadata/files/Metadata-16-01-01.pdf', ...)
```

The problem is that we are upserting sources by their name, so if there are two sources with the same name, they'll be overwritten instead of creating two different sources.

## Solution

* We could have `short_name` for source working as a unique identifier to do upserts with
* They've had the same issue in importers and [fixed it by upserting only if all attributes match](https://github.com/owid/importers/commit/27d793ef2340ab9b856eb8d0edc4dd8d43356c40)
* Hack - move that info to variable description and keep only one source (we're using this right now in `un_sdg`)

The second option looks good enough. Sources are not linked to charts like variables, so creating new ones and deleting old ones (like we already do) is no big deal.

**Comment by Marigold** [comment]
@larsyencken would you mind triaging this? Fiona said it's not a blocker, but she has a PR that depends on this.

**Comment by Marigold** [comment]
@larsyencken so the situation has changed again. Fiona had a great idea to move that info to variable description and use single source, which means this has much lower priority now.

**Comment by larsyencken** [comment]
Proposal from chatting to @danyx23 is that:

- `sources.datasetId` should not be `NULLABLE`, i.e. it should always be required, and each source is "owned" by a dataset
- (`sources.datasetId`, `sources.name`) should be unique together, so a source name is unique per dataset

That means we are actually doubling down on this constraint that Fiona ran into. In her situation, we would want to either pick different names (e.g. `World Bank (XYZ devision)`) or to put the variation per variable into the variable metadata, like she did.

**Comment by larsyencken** [comment]
We'll make a new issue for it.
