### ISSUE TITLE
Export step fails to create new branch

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#3584]
I was trying to execute the `export://github/co2_data/latest/owid_co2` step, by running:
```
CO2_BRANCH=update-gcb-data etlr github/co2_data --export
```
However, I encountered a few issues:
* `OWIDBOT_ACCESS_TOKEN` needed to be defined in `.env`. This was easy to fix, but I'm wondering if this was necessary. I suppose it should rather be using our `GITHUB_TOKEN`.
* I expected it would create a new branch, but instead it failed because the branch was not found. So I manually created the branch, rerun the export step, and then it worked.

Ideally, this step should:
* Not require the `CO2_BRANCH` variable. Instead, it would create a branch with the same name as the current ETL branch (and, if it already exists, it should fail, for safety).
* Create a branch and a PR.

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/etl/pull/3605
