### ISSUE TITLE
ETL can fail with silent out of memory errors

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#360]
The api currently uses 25% of the memory on the `analytics` server, which is enough to cause high-memory steps of the ETL to fail (e.g. `data://open_numbers/open_numbers/latest/ihme__global_burden_disease_death_number`).

The behaviour when they fail is to silently hang. This probably due to the recent process isolation change, or the parallel open numbers change, or both.

**Comment by Marigold** [comment]
Killed data-api until I find the reason it's consuming that much memory ([issue](https://github.com/owid/data-api/issues/12))

**Comment by larsyencken** [comment]
Downgrading to "nice to have" until it becomes more of an issue again.

**Comment by larsyencken** [comment]
Happened again in the last few days, quietly stalled the ETL, which did not die or release locks, meaning no retry was done either.

**Comment by larsyencken** [comment]
This particular step appears to peak around 80% memory usage on a 16G machine (~12.8G memory).
