### ISSUE TITLE
metadata: source -> name and published_by are set to "Google Sheet" when using fasttrack

### ISSUE THREAD

**Issue by edomt** [owid/etl#3616]
### One-liner
Investigate why datasets uploaded through fast-track have some fields set to "Google Sheet".

### Context & details

@pabloarosado recently commented in https://github.com/owid/owid-issues/issues/1630:

> There were also some cases of source "Google Sheet" (as [the example](https://admin.owid.io/admin/charts/7240/edit) Veronika mentioned). We should look into why this is happening. I don't think it's a technical fasttrack problem, but rather that fasttrack is not being properly used. So we should clarify with authors if fasttrack's documentation is unclear, or fasttrack is asking for too many fields, or if the guidelines should be revisited.

One example is [Plastics in Great Pacific Garbage Patch (Lebreton)](https://admin.owid.io/admin/datasets/6259):

![Image](https://github.com/user-attachments/assets/c487e8fd-a48f-45d2-8919-1dc7dbe8ce08)

But looking at the [spreadsheet](https://docs.google.com/spreadsheets/d/1QMw_ZRD3XxCEceBVWwFj3lUKHSOsraf51kuubahBeB8/edit?gid=1898134479#gid=1898134479) used to upload the data, I couldn't find any occurrence of "Google Sheet", so I suspect it might be inserted at another point in the process?

Other examples include:

- https://github.com/owid/etl/blob/master/snapshots/fasttrack/latest/nuclear_warhead_stockpiles.csv.dvc
- https://github.com/owid/etl/blob/master/snapshots/fasttrack/latest/antibiotic_usage_livestock.csv.dvc
- https://github.com/owid/etl/blob/master/snapshots/fasttrack/latest/democracy_freedom_house.csv.dvc

We should investigate why these fast-track datasets have this metadata value, and whether it's an ongoing problem.

**Comment by pabloarosado** [comment]
Fixed by @Marigold on https://github.com/owid/etl/pull/3618
