### ISSUE TITLE
Grapher step fails ("Unknown column 'shortName' in 'field list'")

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#370]
I'm trying to execute [the grapher step of the Electricity Mix dataset](https://github.com/owid/etl/blob/add-electricity-mix/etl/steps/grapher/energy/2022-08-03/electricity_mix.py) in my local grapher, but it fails with the following error:
```
1. grapher://energy/2022-08-03/electricity_mix...
Verifying namespace is present
Upserting dataset
2022-08-04 17:52.58 [error    ] Error encountered during import: (1054, "Unknown column 'shortName' in 'field list'")
2022-08-04 17:52.58 [error    ] Rolling back changes...
```

**Comment by pabloarosado** [comment]
I realised that the new column `shortName` did not exist in my local grapher `datasets` table, even though I have deleted and re-built the local docker volume `owid-grapher_mysql_data_public` twice. Anyway, I run `yarn buildTsc && yarn runDbMigrations` and now the new columns are there.

**Comment by Marigold** [comment]
> even though I have deleted and re-built the local docker volume 

Eh, sorry, I thought that would work. Glad you figured it out!
