### ISSUE TITLE
🐛 etl.grapher_helpers.render_variable_meta not working as expected

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#3750]
I am trying `etl.grapher_helpers.render_variable_meta` to assist me in editing the metadata of step `garden/un/2024-07-12/un_wpp`, but I can't really figure out how it works.

I've been following the guidelines from [the docs](https://docs.owid.io/projects/etl/architecture/metadata/structuring-yaml/#using-jinja-templates-for-advanced-cases) (see end of page), and have created a temporary notebook next to the Garden metadata YAML file (`etl/steps/data/garden/un/2024-07-12/test.ipynb`). In that notebook, I have used the code:

```py
from owid.catalog import Dataset
from etl import grapher_helpers as gh
from etl import paths

# Load dataset
tb = Dataset(paths.DATA_DIR / "garden/un/2024-07-12/un_wpp")['births']
# Define dimensions
sex = "female"
age = "all"
variant = "estimates"
# Render metadata, get `presentation.title_public` field
gh.render_variable_meta(tb["births"].m, dim_dict={"sex": sex, "age": age, "variant": variant}).presentation.title_public
```

I've been changing the `yml` file, but these changes don't seem to reflect in the rendered metadata. I've been re-starting the notebook kernel, but that was not the issue.

My impression is that it is loading the metadata from the JSON files in the `data/` folder instead?

**Comment by Marigold** [comment]
That's right, your approach loads data from the `data/` folder on this line
```
tb = Dataset(paths.DATA_DIR / "garden/un/2024-07-12/un_wpp")['births']
```
To see updates, you'd have to rerun the step. That could be time-consuming though. The first approach mentioned in docs is faster (and preferred in most cases). It loads YAML file and renders it with given `dim_dict` (and you should see updates right away), i.e.

```
from etl.grapher import helpers as gh

# Define dimensions
sex = "female"
age = "all"
variant = "estimates"
dim_dict = {"sex": sex, "age": age, "variant": variant}

# Render metadata, get `presentation.title_public` field
d = gh.render_yaml_file("un_wpp.meta.yml", dim_dict=dim_dict)
d['tables']['births']['variables']['births']['presentation']
```

**Comment by lucasrodes** [comment]
that makes sense, thanks!
