### ISSUE TITLE
Refactor and use ORM for grapher inserts

### ISSUE THREAD

**Issue by Marigold** [owid/etl#415]
## Problem

We're going to change our MySQL schema as part of new data architecture. Current grapher code that interacts with MySQL was copied from [importers repo](https://github.com/owid/importers/blob/master/db_utils.py) and uses raw SQL queries. That is not bad by itself, but given the changes ahead it makes sense to clean it up and try to simplify it and typecheck with ORM.

## Solution

Rewrite `db_utils.py` and `grapher_import.py` with [SQLModel](https://sqlmodel.tiangolo.com/) ORM and see whether it improves code readability and speed.

**Comment by larsyencken** [comment]
Cool! I'm all for the type-checking, and an ORM will probably make for better code, though you might end up just escaping it for the performance critical parts.

**Comment by Marigold** [comment]
> though you might end up just escaping it for the performance critical parts.

That's the plan for `data_values`, luckily other MySQL interactions are not bottlenecks (moreover I've profiled it already and it's only 10% slower).
