### ISSUE TITLE
UN WPP checksum mismatch in Walden

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#418]
```
owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://walden.nyc3.digitaloceanspaces.com/un/2022-07-11/un_wpp.zip:
	walden index checksum = ae621fc20f6eec9d18fe3d78b752d0b7
	downloaded checksum = d27da7eec76bbda7e093fc3d95926d5c
```

**Comment by larsyencken** [comment]
Hmm... just redownloaded the file, the checksum has changed, it might be ok now. Trying again...

**Comment by lucasrodes** [comment]
hi @larsyencken,
how can I recreate this error?

I was just checking, and my bad. I added [this line](https://github.com/owid/walden/commit/5fbd093f0005c17cfea0e822597973f30cab8d5c), which removed some files from the zipped file in Walden and did not update the hash...

On it!

**Comment by lucasrodes** [comment]
Should be fixed in d4417bf87407e2aaa5a1f43c9a739d84ce9754bc

**Comment by larsyencken** [comment]
Works for me

**Comment by larsyencken** [comment]
It also might have been this issue #420
