### ISSUE TITLE
Error: etl-prod.sh freezes and locks subsequent runs

### ISSUE THREAD

**Issue by Marigold** [owid/etl#425]
## Problem

We had a really long queue of [etl-prod.sh](https://github.com/owid/analytics/blob/main/ops/scripts/etl-prod.sh) processes waiting for lock to pull latest changes and execute ETL. For some reason this lock still existed (could have been zombie process). Is there a way to make it more robust? (i.e. release lock after given time) Would monitoring & alerting for ETL runs be helpful (custom metrics for duration, frequency)?

## Possible Solutions

1. Add `--wait` flag to lock which would send the error to #analytics-errors
2. Add timeout to ETL run (a few hours?)
3. ?

**Comment by larsyencken** [comment]
How about:

- `timeout -k 3h ...` at the front of the cron command (even if it doesn't complete after 3h, it will have made a lot of partial progress that will resume next run)
- `flock --wait 3600` inside the command, so that we see errors rather than have a big cascade of things build up
-
