### ISSUE TITLE
Grapher - split datasets into datasets and tables

### ISSUE THREAD

**Issue by Marigold** [owid/etl#450]
Split tables `datasets` into two tables `datasets` and `tables` that link to `variables`.

Using Tables doesn't get us any immediate value, so it's likely a low priority at the moment.

There's a branch with [implementation in grapher](https://github.com/owid/owid-grapher/tree/450-add-tables).

**Comment by danyx23** [comment]
@Marigold same as before, can you spell this out a bit more please? Thank you!

**Comment by danyx23** [comment]
Before this is merged I think we should schedule some work on the admin as well - i.e. where we currently display "Datasets" in the admin UI we should probably show an overview of the tables and then for one table show the individual variables.
