### ISSUE TITLE
Remove `version` and `namespace` from `datasets.shortName`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#456]
Our [current best practice](https://github.com/owid/etl/blob/master/etl/grapher_helpers.py#L403) is to save datasets with short name `[namespace]_[version]_[shortName]` (e.g. `electricity_mix__energy_2022_08_03`). We've recently added `version` to `datasets` table, so it would be cleaner to use only actual short name from now on and update short names of existing datasets.

I'm not aware of any side effects or disadvantages of changing short names, but perhaps I missed something? @pabloarosado 

(After grapher refactoring, function `adapt_dataset_metadata_for_grapher` will be called implicitly for every grapher dataset. So users won't even notice something has changed.)

### Steps
* [ ] Change the code in [adapt_dataset_metadata_for_grapher](https://github.com/owid/etl/blob/master/etl/grapher_helpers.py#L383)
* [ ] Go through all grapher steps and make sure they're consistent with this
* [ ] Fix all datasets from `select * from datasets where shortName is not null`
* [x] Add unique constraint on (namespace, version, shortName)

**Comment by pabloarosado** [comment]
Hi @Marigold. I think you meant that the current best practice is `[short_name]__[namespace]_[version]`, right?
I think that it would indeed be cleaner to just have the short names. However, when searching for a dataset in the cloud admin, you would see the same name for different datasets, and would not be able to know which version each dataset has. So it would be necessary to add a column in the admin to specify namespace and version.
Apart from that, right now I can't think of any other possible issue if we used only short names...

**Comment by Marigold** [comment]
> I think you meant that the current best practice is `[short_name]__[namespace]_[version]`, right?

You're right. It's not consistent though, some datasets are using different structure which is why I want to unify it all and make it implicit.

> So it would be necessary to add a column in the admin to specify namespace and version.

What is shown in admin is dataset's **title**, short name is not shown anywhere. Title could contain version (from what I've checked all faostat datasets do), so that shouldn't be an issue. (Although showing version wouldn't hurt!)
