### ISSUE TITLE
Step checksum does not include `shared.py` module

### ISSUE THREAD

**Issue by Marigold** [owid/etl#466]
When deciding whether DataStep is dirty, we calculate checksum of its [step files](https://github.com/owid/etl/blob/master/etl/steps/__init__.py#L347). There are two situations that can happen:

1. If there's a folder `[short_name]/*` then we calculate checksum of all its files
2. If there's a module `[short_name].py` then we calculate checksum of all files in the same directory with prefix `[short_name].`

This is relatively unknown thing and users assume checksum just magically works for **all files**. We heavily use `shared.py` module that often contains code shared between datasets with different names (like [here](https://github.com/owid/etl/tree/master/etl/steps/data/garden/energy/2022-09-09), but we use it all over the place). Since `shared.py` doesn't make it to step files either way, code changes won't be reflected in the checksum.

What would be the best way to fix this? I can think of:

1. Adding all `shared.*` files to step files (hardcoding)
2. Move everything into `[short_name]/*` directories (but then you cannot share `shared.py` between datasets)
3. Adding **all** files into step files
4. Dynamically get all dependencies of `[short_name].py` and include them as step files (no idea how hard can it be)

@larsyencken any elegant solutions?

**Comment by larsyencken** [comment]
Hmm... my rough preferences in order:

1. (less magic) Symlink `shared.py --> ../shared.py` for these cases, then they'll be picked up in the checksum
2. (more magic) Convention that `../shared*.py` is also included in the checksum, when available

**Comment by Marigold** [comment]
I'm gonna implement 1. as a hotfix and will be closely watching incoming PRs for these types of mistakes. Even though 2. is less magic, using symlinks might look like more magic to users.

**Comment by Marigold** [comment]
As an another heuristic I think it'd be useful to also checksum files matching `short_name*` and not just `short_name.*` as people are using modules like `[short_name]_tools.py`.

**Comment by larsyencken** [comment]
> As an another heuristic I think it'd be useful to also checksum files matching `short_name*` and not just `short_name.*` as people are using modules like `[short_name]_tools.py`.

It's more vulnerable to overlap though, like `population.py` and `population_by_age.py`, or some similar situations. 

It's honestly hard to get implicit detection right. Perhaps we should be encouraging more folders.

**Comment by larsyencken** [comment]
I'd put them in folders and symlink them both in, rather than come up with fancy rules.

**Comment by Marigold** [comment]
I agree they're good, but from my experience few people from data science space are even aware of them. I'd ask others first how they feel about it. I fear it might be easier for them to use `--force --only` (no one has complained about this yet and shared modules are everywhere, which means everyone is using it).

**Comment by larsyencken** [comment]
In my mind, this relates to the bigger issue of reproducible builds that is a little broken by pinning to Github master for all those datasets. I would love us to be able to rewind and reproduce all our historical builds. It's the sort of thing that doesn't seem important at all now, then suddenly 1y later we realise we lost the ability to do something very very helpful in our work.
