### ISSUE TITLE
Meadow UN step fails because of bad zip file

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#481]
The etl step `data://meadow/un/2022-07-11/un_wpp` fails because `zipfile.BadZipFile: File is not a zip file`.

**Comment by larsyencken** [comment]
Looks like a potential case of this one, which we thought we fixed:

- https://github.com/owid/etl/issues/420

**Comment by larsyencken** [comment]
Could not reproduce. The problem disappeared once the walden zip file was deleted, meaning that it was a Walden corruption problem, but it might have happened before the earlier fix was shipped.
