### ISSUE TITLE
Use `_` instead `__` in underscore function?

### ISSUE THREAD

**Issue by Marigold** [owid/etl#496]
We've recently had an [inconsistency](https://github.com/owid/etl/issues/487#issuecomment-1252863212) between ETL and grapher in using underscores. We've decided to keep using `__` for now. 

Mixing `_` and `__` might make some variables more readable, on the other hand using both can be confusing. There [has been a push](https://owid.slack.com/archives/C0193RW5E2J/p1663745593524109) to unify everything to `_`.

Switching to `_` everywhere would involve:

1. Update `underscore` function
2. Manually go through all the steps, find where we work with columns and change `__` to `_` everywhere

It's not yet clear whether it's worth it, we might revisit this in the future.

**Comment by pabloarosado** [comment]
We could just do 1, run all steps and see which ones fail. Maybe they are not too many. We could start by fixing just the ones that fail.
New datasets would then use the single underscore criterion. And, eventually, as old datasets get updated, we could manually change the names of the variables in the new version, and, for consistency, we could optionally also change the names of the previous.

**Comment by larsyencken** [comment]
Closing this one as "wontfix", since it's not very high prio to do, but if someone wants to try improving it they're most welcome to.
