### ISSUE TITLE
GBD datasets missing data files

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#508]
## Problem

The GBD datasets no longer build correctly from scratch, since there are no valid data files for the three GBD entries.

What seems to have happened is that, in this change https://github.com/owid/walden/commit/6fdb4dc689a29591ed27c5c69b3270e55eb1ede5:

- We removed the `owid_data_url` that the pipeline was depending on 
- We added a `source_data_url` that did not point to a valid data file, instead it pointed to some swagger docs
- The pipeline on production had a cached copy of the old file; since the `md5` did not change, the cached copy was still valid, so we didn't see an immediate break
    - But we could no longer build it from scratch, you get an error

## Background

Walden JSON files have three fields relating to data files:

- `owid_data_url`: (required) a link to our copy of the exact data file the ETL will use
- `source_data_url` (optional) a link to the original upstream URL of the exact data file that the ETL will use; for APIs this file does not exist, it is always blank
- `md5`: the checksum of the file the ETL will use, both of the above URLs should point to a file with this checksum

## Error when building from scratch

```
4. walden://ihme_gbd/2019/gbd_risk...
  | 2022-09-24 05:44:46,931 - [bugsnag] WARNING - No API key configured, couldn't notify
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/.venv/bin/etl", line 5, in <module>
  | main_cli()
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
  | return __callback(*args, **kwargs)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/command.py", line 123, in main_cli
  | main(**kwargs)  # type: ignore
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/command.py", line 151, in main
  | run_dag(
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/command.py", line 240, in run_dag
  | time_taken = timed_run(lambda: step.run())
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/command.py", line 247, in timed_run
  | f()
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/command.py", line 240, in <lambda>
  | time_taken = timed_run(lambda: step.run())
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/etl/steps/__init__.py", line 441, in run
  | self._walden_dataset.ensure_downloaded(quiet=True)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/vendor/walden/owid/walden/catalog.py", line 196, in ensure_downloaded
  | files.download(url, filename, expected_md5=self.md5, quiet=quiet)
  | File "/var/lib/buildkite-agent/builds/build-1-3/our-world-in-data/etl-master-garden/vendor/walden/owid/walden/files.py", line 89, in download
  | raise ChecksumDoesNotMatch(
  | owid.walden.files.ChecksumDoesNotMatch: for file downloaded from https://unstats.un.org/sdgapi/swagger/:
  | walden index checksum = 1cc78351acd8d1dcea960880ac87ce26
  | downloaded checksum = c7a7c3df04afd45a702055073051b42f
 ```

**Comment by larsyencken** [comment]
Heads up for @spoonerf. I'll try to hotfix it.

@lucasrodes Something similar happened in your walden files where `source_data_url` pointed to swagger docs instead of to a valid data file, I removed it in walden now but you'll need to fix your scripts so that the next update you do with them doesn't re-add the swagger link there.

**Comment by lucasrodes** [comment]
> @lucasrodes Something similar happened in your walden files where source_data_url pointed to swagger docs instead of to a valid data file, I removed it in walden now but you'll need to fix your scripts so that the next update you do with them doesn't re-add the swagger link there.

Hi @larsyencken, thanks for the heads up. Are we talking about UN WPP files?

**Comment by spoonerf** [comment]
Thanks for fixing @larsyencken!

**Comment by larsyencken** [comment]
@spoonerf No sweat! Just a heads up, I had to make these files public to make this work. If they shouldn't be public, please let me know and we can turn it into a private step instead!

```
# make the ihme_gbd 2019 files in walden publicly accessible
s3cmd setacl --acl-public 's3://walden/ihme_gbd/2019/*
```

**Comment by larsyencken** [comment]
@spoonerf The full details for a private record look something like:

- In the Walden record, set:
  - `is_public` should be `false`
  - `owid_catalog_url` to a S3 url like `s3://walden/ihme_gbd/2022/gbd_cause.feather`
- When uploading the file to S3, don't use `--acl-public`; by default files uploaded are private and only staff will be able to access them
