### ISSUE TITLE
Mypy fails to typecheck with Python 3.10

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#510]
```
==> Checking formatting
  | All done! ✨ 🍰 ✨
  | 431 files would be left unchanged.
  | ==> Checking import sorting
  | ==> Linting
  | ==> Checking types
  | .venv/bin/mypy --exclude='etl/steps\|walkthrough/.*_cookiecutter'  etl backport walkthrough tests
  | .venv/lib/python3.10/site-packages/numpy/__init__.pyi:636: error: Positional-only parameters are only supported in Python 3.8 and greater
 ```

This is a known issue that will be fixed in a later `mypy` release: https://github.com/python/mypy/issues/13627

**Comment by larsyencken** [comment]
This is not important except that it's a necessary step for Python 3.10 support, which we will want at some stage.

**Comment by Marigold** [comment]
(Leaving a note that it's breaking [owid-datautils-repo](https://github.com/owid/owid-datautils-py) too)

**Comment by larsyencken** [comment]
This is no longer an issue since we've moved off of `mypy`.
