### ISSUE TITLE
Updating psutil fails when running make test

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#516]
Currently running into this error when running `make test`

<img width="934" alt="Screenshot 2022-09-26 at 14 04 54" src="https://user-images.githubusercontent.com/10774728/192283901-9243bc3b-dcf2-4981-8c9f-b841e82f07bf.png">

**Comment by Marigold** [comment]
@spoonerf can you try running `pip install psutil==5.9.2` and paste the error here? The error from poetry is quite strange and I can't replicate it.

**Comment by spoonerf** [comment]
Sure! It is: 


(.venv) fionaspooner@Fionas-MBP etl % pip install psutil==5.9.2
Collecting psutil==5.9.2
  Downloading psutil-5.9.2.tar.gz (479 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.8/479.8 KB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/fionaspooner/Documents/OWID/repos/etl/.venv/bin/python -m pip install --upgrade pip' command.

**Comment by Marigold** [comment]
@spoonerf I couldn't replicate it, but found [this thread](https://github.com/pypa/packaging-problems/issues/573). Could you please try `pip install setuptools --upgrade` and then `pip install psutil==5.9.2` again? (You could also try reinstalling [pyenv python](https://github.com/pypa/packaging-problems/issues/573#issuecomment-1057825325), but hopefully that won't be necessary)

**Comment by spoonerf** [comment]
That worked! 🥳 

I'm getting this warning now - not sure if that's anything to worry about but otherwise make test all ran perfectly. Thanks!!

Collecting setuptools
  Using cached setuptools-65.4.0-py3-none-any.whl (1.2 MB)
WARNING: Error parsing requirements for etl: Invalid URL: vendor/owid-catalog-py

**Comment by Marigold** [comment]
Don't worry... and keep your fingers crossed :). If something like this happens again, remove the entire `etl/.venv`, update `poetry self update`, then `pip install --upgrade pip` and try again.
