### ISSUE TITLE
Typing checks fails because of empty folders

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#522]
I'm often working with different git branches, and I may start some ETL steps in one branch, and some other steps in another branch. But when moving from one branch to the other, git keeps all created folders (even if they are empty). Then, running `make test` fails at the typechecking level because `There are no .py[i] files in directory`. So I'm wondering, is this specific test necessary? If so, is there a work around?

**Comment by Marigold** [comment]
This is weird, we already exclude all folders without `.py` files [here](https://github.com/owid/etl/blob/master/scripts/typecheck_steps.sh#L14). Could you please post more info? Also changing the line in `typecheck_steps.sh` from

```
only_dirs_with_python_files | xargs -n 1 -P 0 .venv/bin/mypy
```

to

```
only_dirs_with_python_files | cat
```

and running `make test` again could give us useful info.

**Comment by pabloarosado** [comment]
I have [this branch](https://github.com/owid/etl/tree/add-carbon-pricing-steps), where I created a folder `rff`. When I change to any other branch, the folder `rff/2022-09-14` stays empty (well, it actually, it has a `__pycache__` folder with `.pyc` files, but removing it doesn't change anything). If I remove the subfolder `2022-09-14`, the folder `rff` is ignored and `make test` does not fail. So the problem seems to be that subfolders are not excluded (even if they don't have any `.py` file inside). So `only_dirs_with_python_files()` should search recursively for any `.py` files (or at least one level deeper, to account for the version of the dataset).
