### ISSUE TITLE
walden occasionally audit freezes in CI

### ISSUE THREAD

**Issue by Marigold** [owid/etl#523]
Running `poetry run python owid/walden/audit.py` sometimes [times out in Gitub actions](https://github.com/owid/etl/actions/runs/3126716232/jobs/5072533354). I couldn't reproduce it locally where it runs in a couple seconds.

**Comment by larsyencken** [comment]
Closing this as "wontfix", since we're gonna remove Github CI in favour of buildkite, which isn't experiencing that problem.
