### ISSUE TITLE
Grapher steps are being executed without `--grapher` option

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#532]
## Problem

When you run the bare `etl` command, it tries to build grapher steps as well, and fails due to a lack of MySQL. 

## Expected behaviour

It should not build grapher steps unless `--grapher` is used.

## Workaround

Use `--exclude=grapher`

**Comment by larsyencken** [comment]
Ah, no sweat. Perhaps `--no-grapher-channel` should be the default though?

**Comment by Marigold** [comment]
We're gonna use have grapher step independent on MySQL [soon](https://github.com/owid/etl/pull/538). Should `etl` then build even the grapher channel by default? I'd say yes, if we wanted to build only garden we could run `etl garden`. Then we could get rid of `--no-grapher-channel` altogether.

**Comment by larsyencken** [comment]
Agree with you @Marigold , now that we're not resolving entity ids in the grapher channel (and thus don't need MySQL there), then it should build by default.
