### ISSUE TITLE
Add a new script to autogenerate a YAML FASTT file for customization

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#537]
## Idea

@pabloarosado suggested that we write a script that will take a table, e.g. a feather file in garden, and autogenerate the matching YAML file that we use to customise FASTT. This would make it much faster to do the FASTT customisation step.

**Comment by larsyencken** [comment]
Marking this as "nice to have", but it's also something we could do very quickly (e.g. 1h).

**Comment by Marigold** [comment]
Just noting that we now have CLI command  `etl-metadata-export` which generates YAML file from feather for customisation. Not sure if this is exactly what Pablo wanted, but it could always be improved.

**Comment by pabloarosado** [comment]
Yes, exactly, I think that tool is already very useful (thanks Mojmir!). We can think of different ways in which we can improve it, but for now, I think we can close this issue.
