### ISSUE TITLE
Standardised names for harmonised fields

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#549]
## Problem

We harmonise data so that we can join on it. But we don't use the same words for the same columns, so actually there is no machine-readable way of knowing that we can do this join.

## Proposed solution

First part: always use standard names and standard types (and enforce those types with a check)

- `geo`: for countries, regions and world
- `year`: for years
- `date`: for dates (we do not do this in backported data)
- `gender`: for situations where we have harmonized it

Second part: add to the variable metadata a boolean to say it was harmonised

- This solves the issue of allowing a `gender` column that is custom to the dataset and not harmonised
- The column can contain extra entity values (e.g. new regions not in the master set), but the flag just means that it's compatible to attempt a join on

**Comment by larsyencken** [comment]
@pabloarosado Thoughts?

**Comment by pabloarosado** [comment]
It makes sense.
