### ISSUE TITLE
Proposal: support hierarchies in variable metadata

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#550]
## Problem

For data visualisation, we want to know the hierarchical relationships between categorical variables.

- E.g. countries and regions
- E.g. rollups of all sorts ("Male" is a subset of "Both genders")
- E.g. disease codes in health data
- Other domains as well? (energy?)

## Possible ways to encode them

- An extra variable that encodes them (child -> parent)
- A n:m table mapping (parent -> child) and allowing a child to have multiple parents
  - E.g. "Sweden" in both "Europe" and "High income countries"
- The table could also be provided in the variable metadata

**Comment by larsyencken** [comment]
Killer features for this:

- Treemaps
- Drill-up drill-down support in grapher/explorers

If we were ready to move on those, then we'd revisit this one at that time.

**Comment by ritikBhandari** [comment]
Hi @larsyencken!
I found this project really interesting and I want to contribute in whatever way I can.
To start with, let me know if this issue is still open for discussion. I would love to work on this.
