### ISSUE TITLE
Deprecate `data_helpers.calculate_regions_sums` function

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#551]
We should stop using `data_helpers.calculate_region_sums`, because:
1. Even if you specify a list of REGIONS, in the end it's going to include in the output dataframe as many regions as there are in the `countries_regions` table of the `reference` dataset. For example, even if `High-income countries` is not specified in REGIONS it will be added to your data.
2. I don't think it's a good idea to create by default the aggregate for `World`. The reason why we create our own aggregates is because there are different definitions of continents. But there is only one definition of the World. So, unless your dataset does not have data for World (which is unusual) I'd avoid creating our own aggregate.

Instead we should use the `owid.datautils.geo.add_region_aggregates`. However this function also needs to be improved, but this should be a separate issue.

* [x] Remove `etl.data_helpers` module (since `calculate_regions_sums` is the only function in the module).
* [x] Adapt all code that uses `calculate_regions_sums` to use the corresponding function in datautils.

**Comment by Marigold** [comment]
It's only used in one dataset `owid/latest/key_indicators`. We should definitely move it to the step and remove `data_helpers` to make sure it's not being used by anyone else. This function was specifically tailored to the population in `key_indicators`, so if we switch it for `add_region_aggregates` we need to make sure we're getting the same numbers (we could use `compare` to compare both datasets).

**Comment by lucasrodes** [comment]
@Marigold @pabloarosado I'll be removing it from `owid/latest/key_indicators` in short!

**Comment by lucasrodes** [comment]
I have removed the dependency on `data_helpers.calculate_region_sums`  from `owid/latest/key_indicators` pipeline.

It should now be safe to delete.

**Comment by larsyencken** [comment]
Who wants to delete it now? 😄

**Comment by lucasrodes** [comment]
will address this in #682
