### ISSUE TITLE
Automate grapher upserts (=deploys) on merge to master

### ISSUE THREAD

**Issue by Marigold** [owid/etl#574]
## Problem

Right now we're doing manual deploys with `ENV=.env.prod etl mystep --grapher`. After moving data from `data_values` to parquet, we now have to merge PR first, let ETL rebuild and republish and then manually deploy (which is gonna upsert metadata like variables to mysql).

## Solution

Run `etl --grapher` on production server to automatically upsert everything to mysql.

## Issues

1. This would make it impossible to manually deploy from local (because deploy would overwrite dataset checksum and production run of ETL would try to overwrite it), only commits to `master` would trigger deployment
2. Automatic ETL deploy could run several minutes (there's backporting and such running every time, but we could make it faster)
3. Would this work with variable matching?

**Comment by Marigold** [comment]
@pabloarosado any feedback? I feel like it could be useful, but also quite inconvenient at times.

**Comment by pabloarosado** [comment]
Hi @Marigold, I'm not sure, I'll have to try the new workflow myself (using local grapher, staging and production) to see how everything goes and what could be problematic.

**Comment by larsyencken** [comment]
Estimating this one as 3 days, because although we could switch it on in 2 seconds, the thinking and discussion before that 2 seconds would take some time.

**Comment by Marigold** [comment]
Notes from tech tea:
- we can't do it on staging because charts can't be migrated to live, it's more convenient to push new dataset to live and create charts there
- review process happens before merging PR and needs some back and forth between authors and data team
- notifications about finished ETL builds in Slack to make it less mysterious
- maybe we can trigger ETL from local for specific dataset to get around running all ETL steps
- we could also **move ETL runs from analytics to buildkite** and push to grapher as an action after merging to master
- exploration / validation notebooks living in data steps? could be useful for reviewers
  - should it be notebook or jupytext that generates HTML?

PR review process:
- sanity checks can be time consuming
- checking with notebooks (plotly express for quick viz)
-

**Comment by Marigold** [comment]
Since we've been talking about this more recently, I think it's time to give it a try. We're in a much better position now having buildkite, ops and confidence in running grapher steps.

The most common objection to automatic deploys is that we would be forced to wait for reviews and wouldn't be able to review data in grapher, run variable matching etc. While I'm not yet sure what's the best solution, we could run automatic deploys for **existing datasets** and allow manual deploys for new datasets (manually deploying existing dataset wouldn't work because automatic deploy would overwrite manual deploy after seeing different checksum - we'll see how limiting this is).

As a precursor to this task we have to make sure that our master is consistent with what we have in grapher. My guess is that we'll have to **reupsert all datasets**. We should be careful when doing that, so the plan is to

1. Deploy all datasets on staging
2. Compare datasets from staging to live (using `datadiff` or `compare`)
3. Manually deploy all datasets on live

Then we can enable automatic deploys (which is really just adding line `etl --grapher` to buildkite that runs after merging to master).

@pabloarosado any objections? Do you think this could be a good start? (Comparing datasets will take some time, so no rush)
