### ISSUE TITLE
Field `published_by` should be mandatory, to avoid sources not appearing in the SOURCES tab

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#601]
It seems that the sources' name does not appear in the grapher chart's SOURCES tab. The field that does appear is `published_by`. But we have datasets that only have source name in the metadata, and not `published_by`, which leads to charts where the SOURCES tab actually does not mention the source.
So we could:
1. Make `published_by` a mandatory field in the sources metadata.
2. Let `published_by` copy the content of `source_name` if the former is empty.

I suppose option 1 implies changing several datasets, and it also implies more work when creating the metadata. So maybe 2 is a better option.

I think a better solution (for the future) could be to rename the source's `name` field `short_reference` and the `published_by` field `full_reference`. The mandatory field should actually be `full_reference`, and `short_reference`, if not given, would copy `full_reference`.

**Comment by danyx23** [comment]
Discussed this in tech tea, @Marigold already submitted a PR. Seems like a pragmatic workaround for now, the data catalog project will probably bring more structure and clarity into this area of our data model in the medium term.
