### ISSUE TITLE
Merge quickstart from README and from docs

### ISSUE THREAD

**Issue by Marigold** [owid/etl#604]
We have instructions in two places - [README](https://github.com/owid/etl/blob/master/README.md) and the [quickstart](https://github.com/owid/etl/blob/master/docs/quickstart.rst). It's not clear which one should be used, we should merge README  into `docs` and link it from there.

(There's also `walkthrough` that has its own instructions how to create new steps. Ideally we'd reuse as many sections from `docs` as possible.)

**Comment by danyx23** [comment]
I think it would make sense to:
* remove the stuff at the top of the readme that is giving the overview and quick start
* instead point users to the https://docs.owid.io/projects/etl/en/latest/index.html url at the top of the ETL readme
* keep the lower part of the readme around for now that has more specific instructions etc that we have not converted over to readthedocs yet
