### ISSUE TITLE
`data://garden/faostat/2022-05-17/faostat_ef` breaking on master

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#606]
See: https://buildkite.com/our-world-in-data/etl-full-public-rebuild-nightly-master/builds/37#018435ab-eec2-488a-9bde-91a81037b70e/6-3876

Confirmed locally, getting this error: 

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lars/Documents/owid/etl/etl/steps/grapher/faostat/2022-05-17/versions.csv'
```

**Comment by Marigold** [comment]
@pabloarosado that's my fault, it's caused by moving the grapher directory. [This line](https://github.com/owid/etl/blob/master/etl/steps/data/grapher/faostat/2022-05-17/shared.py#L33) needs to be fixed. Should I take care of it?

**Comment by pabloarosado** [comment]
Thanks @Marigold I'm already on it. Yes, I think that's the line that needs to be changed to `data/grapher`, it's just taking a while to re-run all steps on my computer :-).
