### ISSUE TITLE
Github action for mirroring to engineering project occasionally failing

### ISSUE THREAD

**Issue by Marigold** [owid/etl#616]
We've started getting the following error from CI ([sample run](https://github.com/owid/etl/actions/runs/3394487141/jobs/5643110772))
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1550888/200003212-c90ac4d3-ac56-46df-8812-dc24abd6a03c.png">

Not sure if this is github or us, keeping it open until we figure it out. Restarting CI usually helps.

**Comment by larsyencken** [comment]
Marking it as "nice to have", but if it happens a lot we might need to set up an auto-retry or otherwise rethink how we do this.

**Comment by larsyencken** [comment]
The problem was that we were hitting the maximum number of items that the projects can take. Github released an auto-archiving workflow which can be enabled with a few clicks, and that's now enabled for both the Overview and Engineering projects. That will have fixed this issue.
