### ISSUE TITLE
Disk space usage requirements of ETL build server

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#649]
## Context

We are moving more things to a dedicated large server, `foundation-1`.

Foundation has 3TB of disk available, of which the ETL build system with 12 agents currently uses 1TB (33%).

This is not a problem today, but as we put more things onto containers, we will want to keep an eye on the available disk space.

## Todo

- [x] Nov 30: Set ZFS deduplication on across all containers (`sudo zfs set dedup on lxd/containers`, check with `sudo zpool list`)
- [ ] Dec 15: Check ZFS deduplication rate / disk usage

**Comment by larsyencken** [comment]
It actually looks like ZFS is doing active deduplication on the spot, it's reached a dedup rate of 1.17x and climbing.

**Comment by larsyencken** [comment]
It's good to remember that we have this on. We should disable it for a DB container if we end up moving the live db there.

**Comment by ikesau** [comment]
@larsyencken it's december 15th 🙂 

is everything within acceptable parameters here?
