### ISSUE TITLE
Fast-track: commit generated files to ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#651]
## What

Fast-track tool should have an option to automatically commit generated files to ETL repo.

## Why

Committing datasets makes it possible to update them once they're in ETL and it's generally a good practice (having uncommitted stuff in production ETL wouldn't be transparent).

### How

We can have two DAG files - one that would be committed and one that would be ignored. We then decide where to put it. (There might be some minor technical issues, but I couldn't think of a better approach).

**Comment by Marigold** [comment]
After thinking this through I believe we should be committing everything. We'll at least have history in git in addition to Google Sheets history. Users should use **DRAFT title** and private dataset during development and then remove the DRAFT prefix and make it public when the dataset is ready. Having drafts on staging wouldn't make sense because creating charts there won't be transferred to production.

**Comment by ikesau** [comment]
Hey @Marigold - it's unclear to Daniel and me whether this task concerns committing the generated code, or (some kind of) data, or both. Can you please clarify? 🙂

**Comment by Marigold** [comment]
This is about committing code. Fast-track generates YAML file with metadata and python script that runs ETL. The question was whether we should be committing it to ETL even if dataset is still in DRAFT mode. The answer is likely **yes**. Having commits about DRAFT datasets is ok (only metadata is gonna change) and it helps us track history in git (in addition to Google Sheets).

(Data is never committed. Input data = snapshots are pushed to S3 with DVC though.)

**Comment by danyx23** [comment]
@Marigold  has already implemented this by now.
