### ISSUE TITLE
Create etl tool to check if all datasets are using the latest versions of their dependencies

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#659]
Currently, if a new version of a dataset is created, other datasets that have the former as a dependency don't get automatically updated (which is correct). But we should have a way to visualize which datasets need to be updated because a dependency has changed.

**Comment by Marigold** [comment]
You can use `generate_graph my-graph.dot --filter stepname` to create graph visualisation!

## Alternative

_An alternative answer I wrote before I realised we have `generate_graph`... we could still make it happen if we find that CLI is easier to work with._

This is partly possible with `--downstream` flag, though it also shows upstream dependencies (and dependencies of them).

For instance `etl snapshot://aviation_safety_network/2022-10-14/aviation_statistics.csv --dry-run --force --downstream` returns

```
Running 10 steps:
1. snapshot://aviation_safety_network/2022-10-14/aviation_statistics.csv...
2. walden://worldbank_wdi/2022-05-26/wdi...
3. snapshot://aviation_safety_network/2022-10-12/aviation_statistics_by_period.csv...
4. snapshot://aviation_safety_network/2022-10-12/aviation_statistics_by_nature.csv...
5. data://meadow/aviation_safety_network/2022-10-14/aviation_statistics...
6. data://meadow/worldbank_wdi/2022-05-26/wdi...
7. data://meadow/aviation_safety_network/2022-10-12/aviation_statistics...
8. data://garden/worldbank_wdi/2022-05-26/wdi...
9. data://garden/aviation_safety_network/2022-10-14/aviation_statistics...
10. data://grapher/aviation_safety_network/2022-10-14/aviation_statistics...
```

which is not that useful. Although if we had `--upstream/--no-upstrem` it would be possible then.

**Comment by pabloarosado** [comment]
Thanks, `generate_graph` seems to be useful to see upstream/downstream dependencies. But what I suggested is to identify any possible outdated dependency (of any dataset). It would then be useful to be able to filter if you are only interested in a particular dataset or dependency.

**Comment by Marigold** [comment]
Makes sense. It shouldn't be hard, we just have to get ETL graph as a dictionary and then find those outdated versions. Sounds like an "audit" of sorts. This issue https://github.com/owid/etl/issues/525 could also be part of that audit.
