### ISSUE TITLE
Making dataset 4129 private broke ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#670]
Someone has recently made [dataset with id 4129](https://owid.cloud/admin/datasets/4129) private and it broke our ETL because step `data://garden/country_profile/2022/overview` depends on it. I made it public again to fix ETL. Any idea what was the reason? Should we be more careful when making datasets private or do we also need it automated?

(@lucasrodes @spoonerf was it perhaps you?)

**Comment by lucasrodes** [comment]
not me AFAIK!

**Comment by spoonerf** [comment]
Not me either - it seems like we do need some kind of warning or system for stopping people deleting or making private datasets that are used in the etl. I guess as we do more remixing of datasets and having multiple versions of datasets this is problem that will only get worse :(

**Comment by Marigold** [comment]
Thanks both. We have "warning" system aka ETL errors sent to Slack :). Just wanted to check with you to see who's (or maybe what's?) causing this. Keeping this open in case this happens again.

**Comment by ikesau** [comment]
We'll close this for now to take the discussion to slack. If we want to work to address this issue specifically we can reopen the ticket 🙂
