### ISSUE TITLE
Migrate Walden datasets from DAG to Snapshots

### ISSUE THREAD

**Issue by Marigold** [owid/etl#672]
This would involve migrating all ingest scripts from Walden and rerunning them to get them into DVC. Though it would be nice to get rid of Walden dependency and be consistent, it looks like a lot of work for no practical reason. Some Walden datasets have been uploaded manually and some source URLs might have expired (or changed), so trying to rerun them again could be harder than initially thought.

An alternative is to write ingest scripts that download data from Walden and re-upload them as Snapshots. We could also link to the original Walden ingest script in case someone ever wants to replicate it (or rewrite it to use Snapshots with the new version). This would at least get rid of Walden as a dependency.

**Comment by Marigold** [comment]
@larsyencken do you have an opinion on this one? I'm more and more leaning towards the alternative where we only copy commented code from walden ingest script. That shouldn't be much work.

**Comment by larsyencken** [comment]
I'd be inclined to automatically migrate the contents of Walden to Snapshots somehow, and then to remove walden as a dependency altogether if that's possible.

You could ask the data team if there are any frequently run or high-value ingest scripts, and port the most important two or three, but in general it's probably fine to copy them across commented out.

**Comment by Marigold** [comment]
Migrating all datasets is probably not worth it due to potential errors in manual refactoring. We'd have to do thorough verification of all datasets (using `compare` tool). This might be worth doing after we have an automatic way of doing that (i.e. having something like SVG tester for ETL).

**Comment by Marigold** [comment]
Not worth it. Better to let it die slowly.
