### ISSUE TITLE
Private code for private data

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#678]
## Problem

We want to be able to work on private datasets, but in the case of an embargo, we don't want any code or metadata to be public whilst we're working on it.

## Workaround

- Embargoed private data can be worked on locally on a machine, then only merging to prod after the embargo is lifted
    - But we don't get to make use of CI, which is a shame
- Non-embargoed private data seems able to have public metadata and code

## Technical notes

- To have private code would mean having a private repo for these steps
- Private code should be able to depend on our public DAG, but maybe the public DAG shouldn't depend on the private one

**Comment by larsyencken** [comment]
This one seems like a fair bit of work for something that only comes up now and again. We may well decide not to do it.

**Comment by ikesau** [comment]
Ideally we do this before it bites us, but before we can take it on we should probably work out how many datasets would be implicated.
