### ISSUE TITLE
Change all `owid.datautils.geo` usages for `etl.data_helpers.geo`

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#691]
`geo` module is now incorporated in `etl`. We should use this version instead of `owid.datautils`:

- Update all instances where `owid.datautils.geo` is in use so they use `etl.data_helpers.geo` instead
- Check that the produced datasets aren't changed.

**Comment by lucasrodes** [comment]
Removed usage of `owid.datautils.geo` from default Garden template in walkthrough in https://github.com/owid/etl/pull/718

**Comment by pabloarosado** [comment]
Quick update, in case anyone was planning to work on this. I've changed all uses of `owid.datautils.geo` to `etl.data_helpers.geo` but now several steps fail. I'm looking into it.

**Comment by pabloarosado** [comment]
I created [this PR](https://github.com/owid/etl/pull/761) that changes (almost) all imports of `geo` in data steps from `owid.datautils` to `etl.data_helpers`. However, there are a few cases left, as explained there.

**Comment by pabloarosado** [comment]
As mentiond in [that PR](https://github.com/owid/etl/pull/761), we still have to:
* [ ] Remove the use of `owid.datautils.geo` from `tests/data_helpers/test_geo`. For some reason, when doing so, the tests fail.
* [ ] Remove uses of `add_region_aggregates` from `key_indicators`, `population` and `land_area`, and instead create a custom function just for those steps. This will avoid circular dependencies, which make ETL break.
