### ISSUE TITLE
Add version to ETL and use it to calculate step checksums

### ISSUE THREAD

**Issue by Marigold** [owid/etl#728]
## Why

If we do major upgrade to core ETL (like upgrading pandas) or owid-catalog-py, it won't be reflected in source checksums for steps and ETL won't rebuild them. It might get rebuilt later when working on something else which could be confusing. An example could be pandas upgrade or ETL refactoring.

Incrementing version that changes checksum would also trigger full ETL rebuild in the datadiff CI which would ensure our changes haven't modified anything. The question is whether runtime of full rebuild is acceptable... it is currently less than 1.5 hour which is ok to do from time to time in my opinion.

## How

Add version as an additional element to [checksum_input](https://github.com/owid/etl/blob/master/etl/steps/__init__.py#L350) method. Then increment version when doing major upgrade. We could do it in the same way as in [owid-datautils-py](https://github.com/owid/owid-datautils-py/commit/0bed883fbe5c0bd1a01d624d245da92deacaa75a).

@larsyencken do you have better ideas how to handle this or do you maybe think it's not worth doing at all?

**Comment by larsyencken** [comment]
It's not a crazy idea. A global flag could work. An alternative if you're lazy would be to use the `content-hash` in the `[metadata]` section of `poetry.lock`, which is a checksum of all dependencies. Then it would trigger a full rebuild on any change to any library version.

**Comment by Marigold** [comment]
> Then it would trigger a full rebuild on any change to any library version.

Interesting idea, though it's probably too much (especially for working locally). Thanks for confirmation, I'll see how it feels on next major update.

**Comment by larsyencken** [comment]
We have a first implementation now in prod: https://github.com/owid/etl/pull/740

Closing this for now. We can always reopen if the current solution doesn't prove to be enough.
