### ISSUE TITLE
Enhance: use specific git revisions in dependencies

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#73]
## Problem

The ETL is built to be totally reproducible. But, this abstraction fails when it comes to tracking git repositories, where we always just use the latest `master`. This means you can't rewind your ETL repository two weeks and get the two weeks ago view of the data.

## Proposed solution

Instead of tracking `master`, we should always track a specific version, and have a cron job (Github action?) that polls Github repositories and pushes update commits to the DAG. This way you regain the ability rewind in time and see what the data used to look like.

**Comment by larsyencken** [comment]
As @Marigold noted, an upstream Github change in open numbers broke the ETL just recently. This has become important to look at again now.

**Comment by Marigold** [comment]
In the end it was a bug in `frictionless` package, not in upstream data. Still, this might happen quite easily so perhaps better to do it sooner than later.
