### ISSUE TITLE
faostat: API change breaks faostat_fbsc and prevents the ETL from building

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#76]
During ETL of `faostat_fbsc`, an assertion fails on this line:

<img width="1511" alt="Screen Shot 2022-02-01 at 13 27 00" src="https://user-images.githubusercontent.com/36012/151968251-07bcc9ba-771d-46e8-b568-b5b10bd6f440.png">

**Comment by MarcelGerber** [comment]
@lucasrodes and I looked into this at some point.
This is @lucasrodes:

> 1. Although the bulk data comes from walden, the additional meta data (tables meta_item, meta_area, etc.) do not come from Walden. Instead they are added in the meadow step calling an FAO API.
> 2. This is very not-ideal, instead these tables should be also added in the walden step. So we have a complete frozen picture
> 3. However, we did not do this in Walden because a small restructuring of Walden is required and we did not prioritize this. Small refactoring = allowing Walden to have several source data files (currently it only has one).

The FAO updated their dataset at some point, and so some definitions between the data file sourced from walden and the data sourced from the FAO API diverged.

**Comment by larsyencken** [comment]
Ah, the lack of multi-file support strikes! https://github.com/owid/walden/issues/5

**Comment by lucasrodes** [comment]
Thanks for raising it!

I can look into this later this week and fix it for the time being. However, I expect this error to pop up again as FAO updates the metadata files.

**Comment by larsyencken** [comment]
The current workaround is to build the ETL without fao data `.venv/bin/etl --exclude=fao`

**Comment by larsyencken** [comment]
@Marigold Just making a note that we should chat together about how the ETL runs, and about ways to get it running more reliably
