### ISSUE TITLE
Reading parquet is inefficient because of metadata size

### ISSUE THREAD

**Issue by Marigold** [owid/etl#783]
Metadata makes a significant portion of our parquet size. For instance `grapher/worldbank_wdi/2022-05-26/wdi/wdi.parquet` is 35mb of data and 5mb of metadata. The problem is that Duckdb always reads **all metadata** no matter how many columns we select. So even if we want to read just one field out of a thousand, we'll always have to read these 5mb of metadata for all fields.

This is the reason why we are having performance issues with duckdb & parquet. Range requests to R2 actually work well.

This could be fixed by storing metadata outside parquet file or compressing it somehow.. I've created [an issue in duckdb repo]( https://github.com/duckdb/duckdb/issues/5931) with examples.

**Comment by larsyencken** [comment]
As far as I know, we could just delete the code that adds metadata to the Parquet header, and make it more like feather.
