### ISSUE TITLE
Allow placeholders in metadata yaml files

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#791]
Currently, every time we update an existing dataset, we need to do some manual changes to the metadata file, for example, in years and dates. This is prone to error, and, if we ever want to be able to automatically update datasets, we should avoid it.

I think one solution (the only one?) would be to accept placeholders in yaml files, e.g.
```yaml
dataset:
  title: Some dataset (Institution, %%year%%)
```
Or something like that. Then, the function `dataset.update_metadata` would fill the placeholders with the appropriate information from the dataset, or it would ingest them as arguments.

**Comment by Marigold** [comment]
Nice idea, this could be really useful. With this we could also add parameters at the top of the YAML file and use them later inline, e.g.

```yml
parameters:
  a: 1
  b: 2
  
...
  description: %%a%% and %%b%%
```

that could be used to clean up meta file [like this](https://github.com/owid/etl/blob/master/etl/steps/data/garden/ophi/2022-12-13/multidimensional_poverty_index.meta.yml#L75).

**Comment by larsyencken** [comment]
Typically in Python you use Jinja2 for templating and curly braces, it might be a good angle.

**Comment by larsyencken** [comment]
Marking it as "nice to have" until we get around to automating updates.

The idea is that the YAML file on-disk is always read using something that fills basic template slots.

**Comment by Marigold** [comment]
Tried to use Jinja2 as a templating engine, but it's not as convenient as I was hoping for. Here is an example of multi-line strings from this [real example](https://github.com/owid/etl/pull/1002)

```yaml
{% set description_ethnic_group %}
The Ethnic Power Relations dataset defines ethnicity as any subjectively experienced sense of commonality based on the belief in common ancestry and shared culture. Given this definition, an ethnic group (i.e. a group of individuals sharing a common ethnicity) is included in the EPR Core dataset if it is politically relevant at least once in the sample period. An ethnic group is classified as politically relevant if at least one political organization claims to represent it in national politics or if its members are subjected to state-led political discrimination.
{% endset %}

{% set description_egip %}
An ethnic group in power (EGIP) is a politically relevant ethnic group which has access to power, in one of these options:
  <ul>
    <li>The group rules alone:</li>
      <li>Monopoly: Elite members hold power in the executive to the exclusion of members of all other ethnic groups.</li>
      <li>Dominance: Elite members hold dominant power in the executive, but there is some limited inclusion of "token" members of other groups who however do not have real influence on decision making.</li>
    <li>The group shares power:</li>
      <li>Senior Partner: Representatives of the group participate as senior partners in a formal or informal power-sharing arrangement. By power sharing means any arrangement that divides executive power among leaders who claim to represent particular ethnic groups and who have real influence on political decision making.</li>
      <li>Junior Partner: Representatives participate as junior partners in government, reflected in the number and importance of the positions controlled by group members.</li>
  </ul>
{% endset %}


tables:
  ethnic_power_relations:
    variables:
      egip_groups_count:
        title: Number of ethnic groups in power (EGIP)
        description: |
          Count variable indicating the number of EGIP groups in this country.
          {{- description_ethnic_group | indent(10) }}
          {{- description_egip | indent(10) }}
```

There are two annoying things:
* Jinja2 definitions are highlighted as linting errors and it breaks linting for the entire file (we use JSON schema for YAML files). This could be fixed by having it defined in a different file
* Need to manually specify `indent(n)` for every string

This is probably not worth implementing until we have a real need for it. So far we've been able to live without it.

**Comment by Marigold** [comment]
I'm thinking that using 
```
parameters:
  a: 1
  b: 2
  
...
  description: %%a%% and %%b%%
```
and expanding parameters **after** loading YAML file (i.e. going through all its nodes) would be pretty nice.

**Comment by pabloarosado** [comment]
Hi @Marigold, thanks for looking into this. I think in the end what we need is to have metadata files that don't have hardcoded versions and dates. This way, if we update a data step, we don't have to manually go through the metadata yaml file, look for instances of, say, "2023-02-22", and replace them. So, if what you are suggesting implies writing all parameters at the beginning of the yaml, that doesn't fully solve the problem (although it's much easier to replace some strings only at the very beginning of the file than having to look through the entire file).

**Comment by Marigold** [comment]
We could have both - get parameters from YAML and from version or dataset metadata and then expand them. By the way if you have a dataset that would benefit from this, mention it here please.

**Comment by pabloarosado** [comment]
Yes, both would be even better! I think pretty much all datasets that use a metadata yaml file would benefit from it. Every time you see a version or a year hardcoded in a file, that will need to be manually edited on the next update (same for publication date and date accessed). If, however, year and version were placeholders, those quantities could be extracted from the dataset, and they would need to be manually inputted only when executing our (yet to be built) "walkthrough update" tool.

**Comment by Marigold** [comment]
[This project](https://github.com/childsish/dynamic-yaml) has already done something very similar. Worth trying to see if we hit any roadblocks.
