### ISSUE TITLE
Mismatch between Datasets path and metadata

### ISSUE THREAD

**Issue by Marigold** [owid/etl#793]
There are tens of datasets with metadata different from their path. Dataset's URI is computed from metadata as `[channel]/[namespace]/[version]/[short_name]`. Path could theoretically determine all these fields in metadata, but we don't enforce it and if users don't set it explicitly there's gonna be a mismatch. This is annoying because lots of our tools depend on dataset URIs (`datadiff` or `compare`) and we use either metadata or path assuming they match.

Here are some problematic datasets I found

```
URI `garden/hmd/2022-12-07/hmd` does not match dataset path `garden/hmd/2022-12-07/life_tables`
URI `garden/homicide/None/homicide_long_run_omm` does not match dataset path `garden/homicide/2023-01-03/homicide_long_run_omm`
URI `garden/irena/2022-10-20/renewable_electricity_capacity_and_generation` does not match dataset path `garden/irena/2022-10-20/renewable_electricity_capacity`
URI `garden/irena/2023-01-04/renewable_electricity_capacity_and_generation` does not match dataset path `garden/irena/2023-01-04/renewable_electricity_capacity`
URI `garden/malnutrion/2022-10-18/malnutrition` does not match dataset path `garden/malnutrition/2022-10-18/malnutrition`
URI `garden/met_office_hadley_centre/2023-01-02/near_surface_temperature_global` does not match dataset path `garden/met_office_hadley_centre/2023-01-02/near_surface_temperature`
URI `garden/owid/2023-01-23/covid19` does not match dataset path `garden/owid/latest/covid`
URI `garden/rff/2022-09-14/emissions_weighted_carbon_price__economy` does not match dataset path `garden/rff/2022-09-14/emissions_weighted_carbon_price`
URI `garden/rff/2022-10-11/emissions_weighted_carbon_price__economy` does not match dataset path `garden/rff/2022-10-11/emissions_weighted_carbon_price`
URI `garden/wpp/2019/standard_projections` does not match dataset path `garden/un/2019/un_wpp`
URI `meadow/andrew/2019-12-03/co2_mitigation_curves_2celsius` does not match dataset path `meadow/andrew/2019-12-03/co2_mitigation_curves`
URI `meadow/aviation_safety_network/2022-10-12/aviation_statistics_by_period` does not match dataset path `meadow/aviation_safety_network/2022-10-12/aviation_statistics`
URI `meadow/gcp/2022-09-29/global_carbon_budget_global` does not match dataset path `meadow/gcp/2022-09-29/global_carbon_budget_additional`
URI `meadow/hmd/2022-12-07/hmd` does not match dataset path `meadow/hmd/2022-12-07/life_tables`
URI `meadow/met_office_hadley_centre/2023-01-02/near_surface_temperature_global` does not match dataset path `meadow/met_office_hadley_centre/2023-01-02/near_surface_temperature`
URI `meadow/papers/2016-04-01/farmer_lafond_2016` does not match dataset path `meadow/papers/2023-01-04/farmer_lafond_2016`
URI `meadow/papers/2009-03-01/nemet_2009` does not match dataset path `meadow/papers/2023-01-04/nemet_2009`
URI `meadow/wpp/2019/standard_projections` does not match dataset path `meadow/un/2019/un_wpp`
URI `grapher/cait/2022-08-10/greenhouse_gas_emissions_by_sector` does not match dataset path `grapher/cait/2022-08-10/all_ghg_emissions`
URI `grapher/cait/2022-08-10/methane_emissions_by_sector` does not match dataset path `grapher/cait/2022-08-10/ch4_emissions`
URI `grapher/cait/2022-08-10/carbon_dioxide_emissions_by_sector` does not match dataset path `grapher/cait/2022-08-10/co2_emissions`
URI `grapher/cait/2022-08-10/nitrous_oxide_emissions_by_sector` does not match dataset path `grapher/cait/2022-08-10/n2o_emissions`
URI `grapher/gcp/2022-09-29/global_carbon_budget_global` does not match dataset path `grapher/gcp/2022-09-29/global_carbon_budget_additional`
URI `grapher/homicide/None/homicide_long_run_omm` does not match dataset path `grapher/homicide/2023-01-03/homicide_long_run_omm`
URI `grapher/malnutrion/2022-10-18/malnutrition` does not match dataset path `grapher/malnutrition/2022-10-18/malnutrition`
URI `grapher/met_office_hadley_centre/2023-01-02/near_surface_temperature_global` does not match dataset path `grapher/met_office_hadley_centre/2023-01-02/near_surface_temperature`
URI `grapher/rff/2022-09-14/emissions_weighted_carbon_price__economy` does not match dataset path `grapher/rff/2022-09-14/emissions_weighted_carbon_price`
URI `grapher/rff/2022-09-14/world_carbon_pricing` does not match dataset path `grapher/rff/2022-09-14/world_carbon_pricing_any_sector`
URI `grapher/rff/2022-10-11/emissions_weighted_carbon_price__economy` does not match dataset path `grapher/rff/2022-10-11/emissions_weighted_carbon_price`
URI `grapher/rff/2022-10-11/world_carbon_pricing` does not match dataset path `grapher/rff/2022-10-11/world_carbon_pricing_any_sector`
URI `explorers/emdat/2022-11-24/natural_disasters` does not match dataset path `explorers/emdat/2022-12-07/natural_disasters`
URI `explorers/owid/2022-05-17/food_explorer` does not match dataset path `explorers/owid/latest/food_explorer`
URI `explorers/un/2022-07-11/un_wpp` does not match dataset path `explorers/un/2022/un_wpp`
```

The typical step looks like this

```
ds_garden = Dataset.create_empty(dest_dir, metadata=ds_meadow.metadata)
...
ds_garden.save()
```
The most common error happens when meadow has a different short name or version and we don't update it with `ds_garden.metadata.version = xxx` (e.g. we're combining two meadow datasets, one has name `renewable_electricity_capacity_and_generation` and the output is `renewable_electricity_capacity`, but we don't change it).

We can set those attributes either in code with `ds_garden.metadata.version` or in the YAML file.

Here are a couple of ways we could fix this:

1. Set metadata from `dest_dir` when creating a dataset with `Dataset.create_empty(dest_dir)`
2. Set metadata from `dest_dir` when saving a dataset with `ds_garden.save()`
3. Keep it explicit, but raise an error or at least a warning in `ds_garden.save()` if they don't match

`Dataset` is currently a pretty general class that allows saving datasets to any path. We could either be strict and enforce `[channel]/[namespace]/[version]/[short_name]` structure or be a bit more benevolent and set metadata only when the path matches the structure.

cc @larsyencken @pabloarosado

**Comment by larsyencken** [comment]
Good find! I had been aware of this but had forgotten. In some sense it was inevitable since we weren't enforcing it in any way.

I had thought, we can just catch it in CI, but actually you can't see it until you've run every step, so it has to be caught at  run time as in your suggestions.

I think the main question is how much we want to couple `owid-catalog` to the `etl`.

- If we want to couple them, we would modify `Dataset.save()` to solve this problem (raise error).
  - We would probably prefer in time to move them into the same repo as well

- If we want them decoupled, we would modify `DataStep.run()` to do the check immediately after running a step and raise an error there.

Originally I'd been thinking that the could be quite different, and that we might end up writing other scripts that manipulate datasets outside the ETL. 1y+ on and it seems that's not a use case we care about. 

I'm now in favour of (3) coupling them more and raising an error in `Dataset.save()`.

**Comment by pabloarosado** [comment]
Thanks for looking into this @Marigold. I'm thinking of an alternative, which would keep owid-catalog and etl decoupled. We could have a function in `etl.helpers`, which could be used like, e.g.,
```
ds_garden = create_dataset(path=dest_dir, tables=[tb_garden], default_metadata=ds_meadow.metadata)
```
and would:
* Create an empty Dataset on dest_dir, loading a "default metadata" (as fallback metadata).
* Get channel, namespace, version and short name from dest_dir, and add it to the metadata.
* If there is a metadata file adjacent to the step, load it and overwrite existing fields in metadata.

Would any of this make sense? If so, it could reduce significantly the redundant code in the steps.

**Comment by Marigold** [comment]
> I'm now in favour of (3) coupling them more and raising an error in Dataset.save(). Basically we'd be saying: you may read from a catalog in any number of places, but it's got to have this particular folder structure behind it.

@larsyencken The annoying thing about having to explicitly set them is that you end up with a boilerplate code like this pretty much everywhere

```python
from etl.helpers import Names

# way to extract metadata from module path
N = Names(__file__)

ds_garden = Dataset.create_empty(dest_dir, metadata=ds_meadow.metadata)
ds_garden.metadata.version = N.version
ds_garden.metadata.short_name = N.short_name
ds_garden.metadata.namespace = N.namespace
ds_garden.save()
```

You can check out [this PR](https://github.com/owid/etl/pull/794) with manual fixes for the problems above. Almost all of it would be unnecessary if we set it implicitly (and we could get rid of much more code).

> ds_garden = create_dataset(path=dest_dir, tables=[tb_garden], default_metadata=ds_meadow.metadata)

@pabloarosado This looks very neat, it's nice to have only a single function for everything. The only disadvantage is when your Tables don't fit all in memory and you want to add them one by one with `ds_garden.add(table)`. We could always go low level or pass iterator though, so it's not a real disadvantage.

My idea was to add regex pattern to `Dataset` that would be extracting metadata from paths. I.e.

```python
@dataclass
class Dataset:
    path: str
    metadata: "DatasetMeta"
    structure: str = r"(?P<channel>\w+)\/(?P<namespace>\w+)\/(?P<version>\w+)\/(?P<short_name>\w+)$"

    def __init__(self, path: Union[str, Path], structure: str = None) -> None:
       ...
       
    def create_empty(cls, path):
       groups = re.search(path, self.structure)
       meta.namespace = groups.namespace
       ....
```

If you wanted a general Dataset you would just use empty `structure`. One advantage is that it would be applied to all existing steps and wouldn't add yet another helper function. I'm not married to this though.
