### ISSUE TITLE
Nightly full rebuild failed due to missing covid-19 snapshot

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#804]
## Problem

Had a failure overnight rebuilding the full dataset. It also failed on retry now.

https://buildkite.com/our-world-in-data/etl-full-private-rebuild-nightly-master/builds/159#01860045-b9d7-431b-8d03-409ff6d08ef8

```
dvc.exceptions.CheckoutError: Checkout failed for following targets:
  | /var/lib/buildkite-agent/builds/etl-build-1-1/our-world-in-data/etl-full-private-rebuild-nightly-master/data/snapshots/backport/latest/dataset_5442_covid_19__decoupling_of_metrics_config.json
```

## Possible causes

For some reason, the backporting did not push the file to the private remote

**Comment by larsyencken** [comment]
- I ssh'd on to `etl-prod-1`, which had the missing file.
- I did `dvc push -r private <filename>` which pushed that file to private snapshots.
- I confirmed I could fetch the file locally now
- I kicked off another rebuild

**Comment by Marigold** [comment]
Thanks @larsyencken, I'll go through logs and check what happened.

**Comment by Marigold** [comment]
Hm, the [original error](https://app.bugsnag.com/our-world-in-data/etl/errors/63d60ccac3683e000aa1c57d?event_id=63d60cca00ad179e92520000&i=sk&m=nw) doesn't give us more any more hints. I'll try to run it again manually and wait for the next error like this if I don't find the reason.

**Comment by larsyencken** [comment]
No worries, it seems to be passing again, closing this for now.
