### ISSUE TITLE
Document prod setup

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#805]
When looking through an issue today (#804), I realised I had no idea how our production services are running now (in particular, how and where backporting runs).

We should have a sub-page in our docs under "Architecture" either called "Ops" or "Server setup" that documents it.

Here's my first-level understanding as a diagram:

```mermaid
graph LR

subgraph hetzner[hetzner FSN1]
subgraph foundation-1
  subgraph etl-prod-1
    fast-track-service
    walkthrough-service
    buildkite-agent
  end
end
end

subgraph digitalocean[digitalocean NYC3]
  subgraph s3
    owid-catalog
  end
end

subgraph digitalocean2[digitalocean LON1]
  subgraph owid-live-db
    mysql
  end
end

github --> buildkite --> buildkite-agent --> owid-catalog
fast-track-service --> google-sheets
fast-track-service --> owid-catalog
fast-track-service --> mysql
```

**Comment by Marigold** [comment]
Will do! Speaking of ops, would you mind checking out [my ops PR](https://github.com/owid/ops/pull/42#issuecomment-1385301598) that contains recipe for etl-prod-1?

**Comment by Marigold** [comment]
Backporting runs as part of the [etl-prod.sh](https://github.com/owid/ops/blob/main/templates/etl-prod/etl-prod.sh#L23) script right before running the actual ETL. That means it's triggered either after merging to master or every 6 hours. This was consistent with how we used to run it before. Having a separate service would be nicer, though need some boilerplate code.

I've tried to put it into your diagram

```mermaid
flowchart LR

subgraph hetzner[hetzner FSN1]
  subgraph foundation-1
    subgraph etl-prod-1
      subgraph buildkiteagent[buildkite-agent]
        bulk-backport
        build-and-publish
        update-lfs-catalog
      end
      fast-track-service
      walkthrough-service
    end
  end
end

subgraph digitalocean[digitalocean NYC3]
  subgraph s3
    owid-catalog
  end
end

subgraph digitalocean2[digitalocean LON1]
  subgraph owid-live-db
    mysql
  end
end

github --> buildkite --> buildkiteagent
bulk-backport --> mysql
build-and-publish --> owid-catalog
update-lfs-catalog

google-sheets --> fast-track-service
fast-track-service --> owid-catalog
fast-track-service --> mysql
```

**Comment by larsyencken** [comment]
Ah, yeah, I saw it in `etl-prod.sh`. I didn't realise you dropped the backporting-as-a-service that used to watch MySQL for changes and backport anything that came up. Given all the headaches it caused, that's a totally good move.
