### ISSUE TITLE
Eagerly publish JSON data files for every variable

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#807]
## What

Publish a JSON data file for every variable in MySQL, regardless of whether it is used in a chart.

## Why? / Why now?

- As part of the Data Pages project, we want to be able to make grapher charts with no dedicated grapher page

## Considerations

- To build grapher charts without dedicated grapher pages, we will need access to _both_ variable data and variable metadata

**Comment by Marigold** [comment]
Here's what I've done so far https://github.com/owid/etl/pull/778, but I guess it's gonna change after more shaping.
