### ISSUE TITLE
Eagerly publish JSON **metadata** files for every variable

### ISSUE THREAD

**Issue by Marigold** [owid/etl#814]
Parent issue https://github.com/owid/etl/issues/759

## What

Publish a JSON **metadata** file for every variable in MySQL, regardless of whether it is used in a chart. The typical variable metadata looks like this

```json
{
  "id": 418655,
  "name": "Deaths - Stroke - Sex: Both - Age: 50-69 years (Number)",
  "unit": "deaths",
  "description": "",
  "createdAt": "2022-04-30T10:56:45.000Z",
  "updatedAt": "2022-10-10T14:32:55.000Z",
  "coverage": "",
  "timespan": "1990 - 2019",
  "datasetId": 5599,
  "shortUnit": "",
  "columnOrder": 0,
  "originalMetadata": "{}",
  "datasetName": "IHME - Global Burden of Disease - Deaths and DALYs - Institute for Health Metrics and Evaluation  (2022-04)",
  "type": "int",
  "nonRedistributable": false,
  "display": {},
  "source": {
    "id": 22603,
    "name": "Institute for Health Metrics and Evaluation, Global Burden of Disease (2019)",
    "dataPublishedBy": "Global Burden of Disease Collaborative Network. Global Burden of Disease Study 2019 (GBD 2019) Results. Seattle, United States: Institute for Health Metrics and Evaluation (IHME), 2021.",
    "dataPublisherSource": "Institute for Health Metrics and Evaluation, Global Burden of Disease (2019)",
    "link": "http://ghdx.healthdata.org/gbd-results-tool",
    "retrievedDate": "2021-09-22",
    "additionalInfo": ""
  },
  "dimensions": {
    "years": {
      "values": [
        { "id": 1990 },
        { "id": 1991 }
      ]
    },
    "entities": {
      "values": [
        { "id": 278896, "name": "North America (WB)", "code": null },
        { "id": 1, "name": "United Kingdom", "code": "GBR" },
        { "id": 2, "name": "Ireland", "code": "IRL" }
      ]
    }
  }
}
```
Note that since every variable from a dataset has its own file, there'll be a lot of duplication from entities and years between files and the final "dataset" is gonna be much larger than the corresponding parquet file.

## Why

* Moves baking logic to ETL (baking wouldn't have to touch data values any more)
* Enables creation of grapher charts without having access to metadata in MySQL
* Reduces number of files in our static build

## Considerations

1. Public / private datasets - currently all our data JSON files are public which is ok because we're not publishing metadata. If we start publishing it too, we'd have to be more careful
2. Metadata changes more often than data. Any changes from Admin might take a few minutes to propagate to S3. Also files on S3 have 1 hour cache on Cloudflare (we could avoid CDN when baking)

I'm not sure if this is worth doing at the moment. Would it make more sense to first start with data JSON files and then do metadata separately?

**Comment by Marigold** [comment]
Some notes from our discussion with @danyx23:
1. ETL could be pushing metadata to S3 that only comes from ETL and doesn't use metadata modified in admin. Such admin metadata would be overriding S3 metadata and would be stored in MySQL. During baking we'd pull S3 metadata, apply overrides and save it locally (i.e. `metadata.json` would come from local bake, whereas `data.json` would come from S3)
2. Pushing `dimensions` in metadata to S3 now would let us remove the logic in baking that needs to load data values (though we might as well push all metadata after we resolve the public/private question)
3. We wanted to avoid having a service somewhere in between ETL and admin that would be updating metadata based on updatedAt timestamps. It'd be nicer to have ETL and admin more isolated (see "overriding" in 1.)

**Comment by larsyencken** [comment]
> Also files on S3 have 1 hour cache on Cloudflare (we could avoid CDN when baking)

On this part, we should be able to set `Cache-control` headers via object metadata in Spaces: https://docs.digitalocean.com/products/spaces/how-to/set-file-metadata/

It can probably be set to something much shorter than 1h.

**Comment by Marigold** [comment]
@larsyencken good idea, I'll set it to 5 minutes for now. I was also thinking that this could be a good use case for R2 and we wouldn't have to worry about CDN and caching anymore (we'd have to run some performance tests first though to make sure it's really distributed).

**Comment by Marigold** [comment]
Done.
