### ISSUE TITLE
`walkthrough charts`: Navigation improvements

### ISSUE THREAD

**Issue by paarriagadap** [owid/etl#819]
### One-liner
Small navigation problems when using `walkthrough charts`

### Environment

- `python -V`: 3.11.1
- Operating system: MacOs Ventura
- Working with local, staging or live: Live

### Context & details

- [x] There is a navigation problem with the dropdown menus: the use of the scroll of the mouse is not possible and can make the search of a dataset or a variable more difficult. See video:

https://user-images.githubusercontent.com/63430031/216636786-46c6c6c6-f778-4418-b61c-c2475d529e60.mov

- [ ] When the variable match is completed, the link to get to the Chart approval tool is not right (**Next steps**): http://127.0.0.1:8082/None/suggested-chart-revisions/review
It needs to be replaced by this: https://owid.cloud/admin/suggested-chart-revisions
![image](https://user-images.githubusercontent.com/63430031/216635559-cae7031c-e75a-4d1c-bab6-59f170c6ccaa.png)

**Comment by lucasrodes** [comment]
keep this issue

**Comment by lucasrodes** [comment]
the first listed issue was raised again in #1091

**Comment by Marigold** [comment]
Fixed by updating pywebio

**Comment by paarriagadap** [comment]
Thank you @Marigold ! There was another error in this issue, related to the link at the end of the process:

> - [ ] When the variable match is completed, the link to get to the Chart approval tool is not right (Next steps): http://127.0.0.1:8082/None/suggested-chart-revisions/review
> It needs to be replaced by this: https://owid.cloud/admin/suggested-chart-revisions

I suppose it easy to fix, but it's still there

**Comment by Marigold** [comment]
Oh thanks @paarriagadap , totally missed it. Will fix it tomorrow.

**Comment by lucasrodes** [comment]
@paarriagadap please let me know if this still happens with the new chart revision version.

**Comment by paarriagadap** [comment]
@lucasrodes It works! I'll close the issue then, thank you so much!
