### ISSUE TITLE
Tracking issue: migrate active imports from `importers` to the `etl`

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#823]
## Datasets

- [ ] `bp_statreview`
- [ ] `climate_change`
- [ ] `cow`
- [ ] `edstats`
- [ ] `global_hunger_index`
- [ ] `ihme_gbd`
- [ ] `ihme_sdg`
- [ ] `imf_weo`
- [ ] `migration`
- [ ] `natural_resources`
- [ ] `population`
- [ ] `povcal`
- [ ] `povstats`
- [ ] `sipri`
- [ ] `standard_importer`
- [ ] `standard_revisions`
- [ ] `un_sdg`
- [ ] `un_wpp`
- [ ] `vdem`
- [ ] `who_gho`
- [ ] `worldbank_wdi`

**Comment by lucasrodes** [comment]
Regarding `un_wpp`, we currently have the 2022 version in ETL. The 2019 version is no longer being used (it is archived in the database).

https://github.com/owid/etl/blob/380d5e3f63d786f267e1e70926ebc07e876097fd/dag/main.yml#L12-L17

https://github.com/owid/etl/blob/380d5e3f63d786f267e1e70926ebc07e876097fd/dag/main.yml#L123-L124

**Comment by larsyencken** [comment]
Thanks @lucasrodes, could you push a commit to `importers` pruning it? That way the `importers` repo acts as a TODO list of things outstanding.
