### ISSUE TITLE
Helper function `create_dataset` will not work for explorer steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#825]
I think `create_dataset` will not work for explorer steps, given that you have to specify `ds_explorer.add(tb_garden, formats=["csv"])`. I suppose one solution would be to include `formats` as an argument of `create_dataset`.
Additionally (not totally sure if it's a good idea), `create_dataset` could add the `formats=["csv"]` by default if the step is an explorer step.

**Comment by Marigold** [comment]
Passing `formats` works well, doing it implicitly could be tricky. Since this is a one-liner, I'm gonna wait until someone does it as part of their explorer work.
