### ISSUE TITLE
Create a walkthrough for explorer steps

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#828]
There are walkthroughs for meadow, garden and grapher steps, but not for explorer.
It should be easy to create cookiecutter templates for a simple explorer step, and the walkthrough script.

**Comment by Marigold** [comment]
@paarriagadap once you make your Notion page "Creating Data Explorers" public, could you paste the link here? It's gonna be really useful to link to your doc in walkthrough explorers.
