### ISSUE TITLE
walkthrough: walkthrough charts throwing an error on UN SDG dataset

### ISSUE THREAD

**Issue by spoonerf** [owid/etl#835]
### One-liner
`walkthrough charts` is throwing an error: 'Error: Some (or all) variable IDs in [457173] are not variables to be updated!' I'm not sure how to deal with. 

### Environment

- `python -V`: 3.11.1
- Operating system: Mac OS 13.0.1
- Working with local, staging or live: local and staging

### Context & details

When running `walkthrough charts` on the UN SDG dataset it is tripping up on one variable.

[Old dataset ↗](https://staging.owid.cloud/admin/datasets/5669/)
Name: un_sdg__2022_07_07
ID: 5669

[New dataset ↗](https://staging.owid.cloud/admin/datasets/5863/)
Name: United Nations Sustainable Development Goals (2023)
ID: 5863

I think the issue is that the [variable on staging wrongly has no data ](https://staging.owid.cloud/admin/variables/457173) in it - [the same variable has data on live](https://owid.cloud/admin/variables/457173). I'm not really sure how that could have happened? 

![Screenshot 2023-02-14 at 09 57 07](https://user-images.githubusercontent.com/10774728/218701636-7c7efe4c-febb-4ecb-a73b-1f01ac9514b2.png)

**Comment by spoonerf** [comment]
I don't actually think this is a walkthrough issue now, more something weird happening on staging. 

Should I  try and remove the chart using the affected variable on staging and see if it works?

**Comment by Marigold** [comment]
> I think the issue is that the [variable on staging wrongly has no data ](https://staging.owid.cloud/admin/variables/457173)in it - [the same variable has data on live](https://owid.cloud/admin/variables/457173). I'm not really sure how that could have happened?

Our staging can get out of sync from live over time, it's not synced automatically. When that happens, you can run ssh onto staging and run `cd staging && make refresh` to refresh MySQL database. I'm running it now ⌛

**Comment by Marigold** [comment]
I refreshed staging but that didn't work. The problem is that only variables with charts **that are not tagged as private** are synced to staging. The [chart in question](https://staging.owid.cloud/admin/charts/1973/edit) is private.

> Should I try and remove the chart using the affected variable on staging and see if it works?

I guess why not? An alternative would be to run ETL grapher un_sdg against staging, but that could take a long time.

**Comment by spoonerf** [comment]
Ah interesting - I think that private tag is an accidental tag so have removed it. Will run the refresh on staging again now. Thanks for taking a look into it!

**Comment by spoonerf** [comment]
Weird, it is still not synced. I'll delete it off staging and see if that helps the walkthrough.

**Comment by Marigold** [comment]
> Weird, it is still not synced. I'll delete it off staging and see if that helps the walkthrough.

The reason is that `make refresh` uses MySQL dumps that are only created once a night. Anyway, deleting should help.

**Comment by spoonerf** [comment]
Ah okay - thanks! Will close this now as we know the culprit is private charts.
