### ISSUE TITLE
Adapt `harmonize` to write new aliases to both the old and new regions dataset

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#845]
## Overview

Adapt `harmonize` to write new aliases to both the old and new regions dataset.

When writing aliases to the new `regions` dataset, there is no need to create a new dataset version. If a new alias is added to `regions`, ETL will trigger changes in many other datasets, but I think this shouldn't happen often, and it's not a big issue.

## Background

- We created a new `regions` dataset that is meant to replace `countries_regions`, though we're not using it yet
- We're currently blocked with `regions` pending a decision whether its the way we want to go

**Comment by Marigold** [comment]
Done.
