### ISSUE TITLE
`grapher/un_sdg/2022-07-07/un_sdg` dataset is missing section 11.6.1

### ISSUE THREAD

**Issue by Marigold** [owid/etl#854]
When trying to rerun grapher import of UN SDG dataset `etl grapher/un_sdg/2022-07-07/un_sdg --grapher` I ran into two problems.

1. Section 11.6.1 is not in data even though we use one of its variables [in a chart](https://owid.cloud/admin/charts/2076/edit)
2. Some variable names have switched dimensions in their titles, for instance [variables from this chart](https://owid.cloud/admin/charts/5270/edit) have names like `16.1.2 - Number of total conflict-related deaths, by sex, age and cause of death (Number) - VC_DTH_TOTN - Planted explosives and unexploded ordnance (UXO) - Both sexes - All age ranges or no breaks by age`, but ETL is creating variables with name `16.1.2 - Number of total conflict-related deaths, by sex, age and cause of death (Number) - VC_DTH_TOTN - All age ranges or no breaks by age - Planted explosives and unexploded ordnance (UXO) - Both sexes` (note position of `Both sexes`). Is it possible that dimensions ordering is not consistent?

It is possible that we've made some updates to UN SDG code and didn't upload it to grapher. With automatic deploys we need to make sure our code and grapher are in sync.

@spoonerf do you have any idea why 1. happens (and maybe even 2.)? I can fix 2. by changing the code, but I'm lost when it comes to 1.

**Comment by spoonerf** [comment]
That's super weird - I can't think of anything of the top of my head but I can take a look into it and try and figure out what happened (or what past me did). Sorry!

**Comment by Marigold** [comment]
@spoonerf don't worry then if you don't know from the top of your head. I'll take a quick look first.

**Comment by spoonerf** [comment]
@Marigold - [this is the culprit](https://github.com/owid/etl/blob/a9de217eae37e1ba19e6581e8af204914b1f9c74/etl/steps/data/garden/un_sdg/2022-07-07/un_sdg.py#L305) for 1, "EN_REF_WASCOL" shouldn't be there. I can't remember why I added it - massive apologies!

**Comment by Marigold** [comment]
The second culprit was caused by different sorting of dimensions from what we have in grapher. Changing it would be a pain, so it's better to wait for the new version and then archive the old dataset.

**Comment by spoonerf** [comment]
Should be sorted in #802

**Comment by spoonerf** [comment]
Hey @Marigold - I think this should be sorted now, I have updated the UN SDG dataset and archived the problematic one. 

Not sure if [this line](https://github.com/owid/etl/blob/master/dag/main.yml#L74) needs updating?

Sorry for the troubles!
