### ISSUE TITLE
pypoetry failing to install mysqlclient

### ISSUE THREAD

**Issue by Zoophobus** [owid/etl#864]
pypoetry keeps on failing to install when executing the make test. This is after following your installation recommendations on an Ubuntu system (22.04.1). The following is the start of the error message that I receive.
`• Installing mysqlclient (2.1.1): Failed

  CalledProcessError

  Command '['/........./workspace/WiSE/owid/etl/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/........./workspace/WiSE/owid/etl/.venv', '--no-deps', '/......./.cache/pypoetry/artifacts/2d/90/d6/339cd2c929c6d8a54167285d71ca5d4c6996063ebeba2e43a6d5e3f698/mysqlclient-2.1.1.tar.gz']' returned non-zero exit status 1.`
The latter part of the second section of "this" error message reads:
`   × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [27 lines of output]
        /bin/sh: 1: mysql_config: not found
        /bin/sh: 1: mariadb_config: not found
        /bin/sh: 1: mysql_config: not found
`

Looking around it suggested that the sql c library is absent and causes these problems, however it is available on my system, just not within this environment. Can someone help me to fix this?

**Comment by Marigold** [comment]
@Zoophobus this looks like MySQL client is missing on your system. Could you try installing it with `sudo apt install mysql-client` (or perhaps `sudo apt install libmysqlclient-dev`) and then try again?

**Comment by Zoophobus** [comment]
Hi thanks for responding, unfortunately it's not that simple, below is the response
`~$ sudo apt-get install mysql-client
[sudo] password for zoo: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mysql-client is already the newest version (8.0.32-1ubuntu22.04).
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
`

**Comment by Zoophobus** [comment]
The same for the dev packages!
`... install libmysqlclient-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libmysqlclient-dev is already the newest version (8.0.32-1ubuntu22.04).
libmysqlclient-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
`

**Comment by Marigold** [comment]
This could be because the `mysql` executable is not in your system's PATH. I assume `which mysql` is not giving you any path, right? You'll have to find where is mysql installed and add it to your path with `export PATH=$PATH:/path/to/mysql/bin`. (Try e.g. `sudo find / -name mysql_config` to find the path)

**Comment by Zoophobus** [comment]
Sorry to be a pain again, however the output of `which mysql` is the `/usr/bin/mysql` path. I've setup mysql previously for some django projects, so I'm really quite stumped as to what is occurring here, although that it's something stupid I think is now a given

**Comment by Zoophobus** [comment]
Hi Marigold,

Thanks for the help, miraculously after coming back to this and just re-entering `poetry install` the mysqlclient for the local pip environment was installed `Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing mysqlclient (2.1.1)

Installing the current project: etl (0.1.0)
`
I'm not sure exactly what changed in the meantime, regardless though this is working (ish) so I won't jinx it. (Although now I have a new import error with the libstdc++ library). So while I'll close this issue be warned that I may well be back soon
