### ISSUE TITLE
Deleting datasets with fast-track

### ISSUE THREAD

**Issue by Marigold** [owid/etl#881]
It's currently not easily possible to delete datasets uploaded via fast-track. It has been requested [by authors](https://owid.slack.com/archives/C0193RW5E2J/p1676990186926129?thread_ts=1676969225.479169&cid=C0193RW5E2J). In addition to deleting dataset in DB we should also remove files from ETL generated by fast-track.

It makes sense to add it to fast-track itself as an additional "Delete" button when user selects an existing dataset (with confirmation pop-up).

**Comment by larsyencken** [comment]
Won't do anything about it right now, but if we get more requests we can schedule it.
