### ISSUE TITLE
Grapher deploy can overwrite manually edited variables metadata

### ISSUE THREAD

**Issue by Marigold** [owid/etl#893]
## Problem

Datasets pushed via ETL should be non-editable. Otherwise users might change metadata manually and ETL could then overwrite it back on next automatic (or manual) deploy.

Dataset metadata from non-`owid` namespace can't be edited, but you can still edit its variables that are saved to `display` column. An [example](https://staging.owid.cloud/admin/variables/576757)
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1550888/223740435-40c034e8-bcb4-455d-81b3-04efefa8b832.png">

You can edit everything for datasets under `owid` namespace. Only `Key Indicators` are currently there.

## Proposal 1 - make everything non-editable

Everything would need to be done in ETL. This means creating a PR, changing YAML metadata file and merging (which triggers automatic deploy) or pushing to master directly. Would it be annoying for authors? (I'll be working with @bastianherre to see how much pain can he endure).

## Proposal 2 - don't update `display` if it has been changed manually

We could detect if `display` has been manually updated and don't update it in ETL deploy. However, this might bite us when e.g. we release new version of a dataset and remap everything to new variables (thereby losing the old display).

This is related to the idea of separating ETL from admin and overriding immutable ETL metadata by metadata from admin (cc @danyx23).

**Comment by larsyencken** [comment]
@Marigold to create a new grapher ticket to prevent admin update of display for variables from the ETL.

**Comment by Marigold** [comment]
All fields in admin have been made non-editable.
