### ISSUE TITLE
Migrate etl to a new server

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#91]
Currently the `etl` runs every 6 hours on the OWID internal server `live`. But it requires so much memory for some Pandas operations that the machine runs out, and kills MySQL which ends up restarted.

We would like to move the `etl` to a new machine, which could be same as for `analytics`, and have it operate and publish from there.

**Comment by larsyencken** [comment]
Added swap space yesterday on the live machine to buy us some time.

**Comment by Marigold** [comment]
FYI peak memory consumption of `etl` was ~10GB on analytics server.
