### ISSUE TITLE
Data: drop Latin America from `countries_regions.csv`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#92]
Latin America was recently dropped in favour of South America in the importers repo https://github.com/owid/importers/commit/f410c7f4f8035cfaa4ecf9d04f107c9c94dce382. We should update our [countries_regions.csv](https://github.com/owid/etl/blob/master/data/reference/countries_regions.csv) to reflect the change.

There's a script that creates `countries_regions.csv` we should merge and generate it automatically https://github.com/owid/etl/tree/countries-regions-reference/etl/scripts/countries-regions.

**Comment by danielgavrilov** [comment]
@Marigold Is this potentially already merged and fixed?

**Comment by Marigold** [comment]
It is, sorry it took so long. Closing this now.
