### ISSUE TITLE
Flunet updates sometimes contains invalid rows

### ISSUE THREAD

**Issue by Marigold** [owid/etl#925]
We're now updating our flue net automatically, however the snapshots we download occasionally contain invalid rows and we get error

```
# ParserError: Error tokenizing data. C error: Expected 49 fields in line 50053, saw 56
```

If you print those invalid lines with

```python
def foo(line):
    print(line)

pd.read_csv("data/snapshots/who/latest/flunet.csv", on_bad_lines=foo, engine='python')
```

you'd get two invalid lines with wrong number of rows

```
['AFR', 'YR', 'SH', 'FLU_MID_AFR', 'COD', 'Democratic Republic of the Congo', '2021-01-18', '2021', '3', '2021-01-17', '2021', '3', 'NOTDEFINED', '25', '25', '2', '', '0', '', 'NOTDEFINED', '1753', '865', '0', '0', '8', '0', '', '0', '', '0', '', '8', '', '', '0', '', '0', '4', '4', '12', '', '3', '', '', '', '', '', '', '0', '', '', '', '', 'RU', '201337', '201337']
['EUR', 'NH', 'NH', 'FLU_SW_EUR', 'MLT', 'Malta', '2018-02-19', '2018', '8', '2018-02-18', '2018', '8', 'SENTINEL', '0', '', '0', '0', '0', '', '', '0', '', '', '', '0', '', '', '0', '', '0', '0', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '3', '', '', '', '', '', '', '', '', 'ParaInflu 1', '', 'It seems that Influenza A[/H1](https://file+.vscode-resource.vscode-cdn.net/H1) started slowly in South of the country (2 A[/H1](https://file+.vscode-resource.vscode-cdn.net/H1) in Gabes, Sfax and Djerba) , in total 6 A[/H1](https://file+.vscode-resource.vscode-cdn.net/H1) viruses were isolated and we wait for seology to confirm the subtype.', 'TN', '200546', '200546']
```

@spoonerf any idea what should we do? We could ignore them (assuming there are only a few) or abort automatic update if we see that the file is unreadable.

**Comment by Marigold** [comment]
It's also strange that some successful downloads of fluid are way smaller than they should be (~130mb). This [snapshot has for instance](https://github.com/owid/etl/blob/master/snapshots/who/latest/fluid.csv.dvc#LL24C9-L24C17) just ~25mb. I checked it and it only has 165099 lines compared to expected 865988.

**Comment by spoonerf** [comment]
Looks like the hotfix (#926) is working well. I asked the WHO about the stability of the files but they dodged the question. This makes me think that the stability of the files could be an ongoing issue. 

@Marigold - do you think we need a different solution to this for the longer term? Would grabbing the data in smaller chunks help, e.g. getting a country at a time?

From my point of view, I think the current fix is good solution, it would just be good to be alerted if the most recent datapoint is more than a month old meaning the data hasn't been successfully fetched in quite some time.

**Comment by Marigold** [comment]
@spoonerf agree, the current solution seems to be "working" (= not breaking ETL). We should track [buildkite jobs](https://buildkite.com/our-world-in-data/etl-flunet-update-master) and make sure there's at least one successful download once in a while. I'm setting a reminder to check it in a week.

**Comment by danyx23** [comment]
@Marigold can this issue be closed? You mentioned a buildkite job, did you add this or decide against it?

**Comment by Marigold** [comment]
> make sure there's at least one successful download once in a while

There's a buildkite job already, and it passes every couple of days. It's not perfect, but I think we can close this.
