### ISSUE TITLE
Propagate source checksums all the way into grapher

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#94]
## Problem

We would like to know which data in grapher is out of date compared to the ETL, without re-running an upsert to grapher. This gives us important information about what's changed, information that's especially important if we believe that upserts to grapher will always be done manually. For example, if we recalculate our population dataset, we may wish to have an indicator which datasets that depend on it need updating in Grapher.

## Proposed solution

One solution is to propagate the `source_checksum` mechanism that the ETL uses, and to maintain in MySQL a mapping of which checksum is the latest used by a dataset. With such a mechanism, it could be cheap to check what data in MySQL is out of date, and list that to the user.

**Comment by Marigold** [comment]
Just a note for my future self -  all updates to grapher are now done manually, so this is not such a big issue, but if we start pushing to grapher automatically then we absolutely have to do this since every push to grapher takes ~10s (because of `data_values`).

**Comment by larsyencken** [comment]
More context from our chat:

- The ETL is "smart" and only rebuilds what needs rebuilding
- But the upsert to grapher is not smart right now, it always upserts everything
- The smarts are based on checksums
  - You never need to rebuild something if the checksums haven't changed (see `checksum_input()`, `checksum_output()`, `is_dirty()` in `etl/steps/__init__.py`)
- This ticket would make it smart, by adding checksums of the data to MySQL
  - That way, the next time you go to upsert, you can see that nothing has changed, and skip it

Open ideas:

- Could we continuously deploy data from the ETL to grapher, not make it so manual?
  - Probably we can, and should, if the ETL is stable enough and used often

Open questions:

- When you upsert over the top of an existing dataset, are variable ids preserved? (charts will refer to data by `variableId`, so once we have a chart, we cannot delete a variable without deleting the chart first)
- Where would the checksum live in the database?
  - Since ETL steps cover one whole dataset at a time, then the checksum would be added to the `datasets` table in MySQL (field to be added via a db migration script in the `grapher` repo)

**Comment by wcox13** [comment]
So here is the rough plan on this:

1) Write a migration in grapher to add a `latestChecksum`. I think it's best for this to be non-null, defaulting to zero or something, since we should always have a checksum
2) Update `db_utils#upsert_dataset` to write the additional column, which is easily accessed in that scope with `dataset.metadata.source_checksum`
3) Once both changes are deployed, run a full `etl --grapher` in prod to populate the real checksums / overwrite the default zero value for all datasets. Since `upsert_dataset` is called on each `etl blah --grapher`, this should work fine

Does this sound OK?

**Comment by wcox13** [comment]
> Note that not all datasets come from ETL (only about 800 out of 3000) and not all future datasets will have checksum (and computing checksums retroactively would be a pain). We could have either zero with non-null constraint or just have nulls. Is there any practical difference?

Oh, yeah nulls are fine if not all datasets have checksums, I thought they did 👍  Thanks

> Just be careful that source_checksum is checksum of inputs for a given step. You might need something more like checksum_output

Good point - If I'm understanding these correctly, I'm not sure it matters which checksum to use, since outputs should change if and only if inputs change. @larsyencken do you have an opinion on this?

**Comment by larsyencken** [comment]
This one looks done.
