### ISSUE TITLE
bug: error when 'dataset' is not defined in metadata, KeyError: 'dataset'

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#996]
Sometimes, we do not want to define the field `dataset` in a Garden step. This might be because we have already defined the dataset in previous stages (Snapshot or Meadow).

Ideally, not defining the field `dataset` should signal that we want ETL to propagate whatever it has from before.

However, this fails at the moment with a `KeyError` error. Example of error:

```
ds_garden = create_dataset(dest_dir, tables=[tb_garden], default_metadata=ds_meadow.metadata)
  File "/home/lucas/repos/etl/etl/helpers.py", line 138, in create_dataset
    ds.update_metadata(N.metadata_path)
  File "/home/lucas/repos/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 157, in update_metadata
    self.metadata.update_from_yaml(metadata_path, if_source_exists=if_source_exists)
  File "/home/lucas/repos/etl/vendor/owid-catalog-py/owid/catalog/meta.py", line 178, in update_from_yaml
    dataset_sources = annot["dataset"].get("sources", []) or []
KeyError: 'dataset'
```

A current workaround is to define `dataset: {}` in the metadata YML file.

[[Related slack thread](https://owid.slack.com/archives/C0193RW5E2J/p1678285523104049?thread_ts=1678285467.182689&cid=C0193RW5E2J)]

**Comment by Marigold** [comment]
@lucasrodes you might have an old version of catalog. This has been [fixed about a month ago](https://github.com/owid/owid-catalog-py/commit/1707546a8f07ac263e6dee81e3cabf8c6b724d62).

**Comment by lucasrodes** [comment]
@Marigold, thanks for your help. Indeed, I had an old `owid-catalog-py` version. To update I simply ran:

```
cd vendor/owid-catalog-py
git pull
```
